In [2]:
import pandas as pd

In [3]:
rewards = pd.read_csv("/Users/Jiwon/Documents/GitHub/final_project/data/IVE_광고적립.csv")

In [4]:
rewards

,rwd_idx,ads_idx,ads_code,mda_idx,pub_sub_rel_id,dvc_idx,advid,click_key,show_cost,adv_cost,rwd_cost,earn_cost,click_date,regdate,ctit
0,238304818,413490,CFZ6lzEmeD,22,27496512,32947806,09b6a808-4f76-4584-87c5-626f21f472a0,b0e22dba943810794d25c993dff425c4e16d0744,190,190,120,120,2025-07-26 00:00:31,2025-07-26 00:05:02,271
1,238304829,413490,CFZ6lzEmeD,22,27496512,47387244,ba4fd0c8-4f06-4dfa-9c3f-c6b39ee7066e,0679ff4c6a14beba296e44d7ffdd88129f42ffbf,190,190,120,120,2025-07-26 00:00:32,2025-07-26 00:08:17,465
2,238304816,413490,CFZ6lzEmeD,22,27496512,32425124,64c675d0-8edd-4478-9906-a806651fdf92,68eb28d636724061da21e490a1afff6a39cd78f7,190,190,120,120,2025-07-26 00:00:42,2025-07-26 00:04:43,241
3,238304817,413490,CFZ6lzEmeD,22,27496513,34006545,a08ebb04-e70a-4492-89d4-17fa96bf8c75,37da42f12b6f732d8c8bf1a609c01e569b7f8a09,190,190,120,120,2025-07-26 00:00:54,2025-07-26 00:04:45,231
4,238304802,133653,rl8ud4uNQC,801,1,56867331,dbe54f40-41b5-4423-ae2f-048fd6ecf5af,624b1bbc57c9ea81005c74e1956d48e76d974816,260,260,97,195,2025-07-26 00:01:07,2025-07-26 00:02:04,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475026,239780599,356956,1UNE1La9yv,270,1,35431157,56296bc1-c155-4fa7-9888-72b195653deb,3dc358e1a2b6a3480ba45dc65f81a308bc6c5e70,10,5,3,3,2025-08-25 11:32:34,2025-08-25 11:32:44,10
1475027,239780621,445907,0gEJGntDo3,794,1,62076634,d46f85a9-e8e0-4017-8354-e93b0ffc5ffe,d3a189157fc1c3b458b44e485a38ad544b89402d,170,170,15,30,2025-08-25 11:32:37,2025-08-25 11:34:29,112
1475028,239780617,446855,yrwq08KCov,563,1,60605730,666272a3-4181-4635-84e7-de1df1008ace,c752e95c5a236c8799cbcf4dc516b7e09e1afda7,18,18,14,14,2025-08-25 11:32:47,2025-08-25 11:33:55,68
1475029,239780609,446837,2hznDD8Yx3,371,1,46271340,c91a2823-8a33-4d36-8900-966448fd0e56,4dc015e177c38a9d2d0cf65d2b2e146e79352683,13,13,9,9,2025-08-25 11:33:07,2025-08-25 11:33:15,8
1475030,239780612,356956,1UNE1La9yv,270,1,61667811,729dcecc-2369-4ead-88f4-0e8544c5e63f,ffbad59341e1268406e2e45f18dac5b7ee21a4e1,10,5,3,3,2025-08-25 11:33:22,2025-08-25 11:33:36,14

In [5]:
ads = pd.read_csv("/Users/Jiwon/Documents/GitHub/final_project/data/IVE_광고목록.csv")

/var/folders/6n/tjcbrygj54s39y61m4r7ymrr0000gq/T/ipykernel_88157/1411436255.py:1: DtypeWarning: Columns (12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  ads = pd.read_csv("/Users/Jiwon/Documents/GitHub/final_project/data/IVE_광고목록.csv")

In [6]:
pd.set_option('display.float_format', lambda x: f'{x:f}')

In [7]:
print("===== 고유값 개수 =====")
print (rewards.nunique())
print()

print("===== null 값 개수 =====")
print("null 개수 : ", rewards.isnull().sum())
print("null 비중 : ", rewards.isnull().mean())
print("\n 광고 식별자만 null 값 가짐\n")

print("===== info =====")
print(rewards.info())
print()

print("===== decribe =====")
print(rewards.describe())

===== 고유값 개수 =====
rwd_idx           1475031
ads_idx              8379
ads_code            18701
mda_idx               174
pub_sub_rel_id       4062
dvc_idx            642059
advid              642164
click_key         1475031
show_cost             178
adv_cost              177
rwd_cost              343
earn_cost             282
click_date         881394
regdate            871979
ctit                18551
dtype: int64

===== null 값 개수 =====
null 개수 :  rwd_idx              0
ads_idx              0
ads_code             0
mda_idx              0
pub_sub_rel_id       0
dvc_idx              0
advid             7171
click_key            0
show_cost            0
adv_cost             0
rwd_cost             0
earn_cost            0
click_date           0
regdate              0
ctit                 0
dtype: int64
null 비중 :  rwd_idx          0.000000
ads_idx          0.000000
ads_code         0.000000
mda_idx          0.000000
pub_sub_rel_id   0.000000
dvc_idx          0.000000
advid            0.004862
click_key        0.000000
show_cost        0.000000
adv_cost         0.000000
rwd_cost         0.000000
earn_cost        0.000000
click_date       0.000000
regdate          0.000000
ctit             0.000000
dtype: float64

 광고 식별자만 null 값 가짐

===== info =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475031 entries, 0 to 1475030
Data columns (total 15 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   rwd_idx         1475031 non-null  int64
 1   ads_idx         1475031 non-null  int64
 2   ads_code        1475031 non-null  object
 3   mda_idx         1475031 non-null  int64
 4   pub_sub_rel_id  1475031 non-null  int64
 5   dvc_idx         1475031 non-null  int64
 6   advid           1467860 non-null  object
 7   click_key       1475031 non-null  object
 8   show_cost       1475031 non-null  int64
 9   adv_cost        1475031 non-null  int64
 10  rwd_cost        1475031 non-null  int64
 11  earn_cost       1475031 non-null  int64
 12  click_date      1475031 non-null  object
 13  regdate         1475031 non-null  object
 14  ctit            1475031 non-null  int64
dtypes: int64(10), object(5)
memory usage: 168.8+ MB
None

===== decribe =====
               rwd_idx        ads_idx        mda_idx   pub_sub_rel_id  \
count   1475031.000000 1475031.000000 1475031.000000   1475031.000000
mean  239042983.839559  420134.498482     419.332570  25797059.266720
std      425938.446114   82625.689183     265.017095  44503654.045392
min   238304802.000000    9716.000000      12.000000         1.000000
25%   238674222.500000  435909.000000     303.000000         1.000000
50%   239043054.000000  440525.000000     396.000000         1.000000
75%   239411848.500000  444350.000000     563.000000  33306660.000000
max   239780622.000000  446909.000000    1061.000000 144682688.000000

              dvc_idx      show_cost       adv_cost       rwd_cost  \
count  1475031.000000 1475031.000000 1475031.000000 1475031.000000
mean  50579799.805650     391.324734     391.075579     151.780335
std   11897231.126098    4641.859857    4641.356824     321.050036
min          0.000000       0.000000       0.000000       1.000000
25%   42612825.000000     170.000000     170.000000      15.000000
50%   54535366.000000     180.000000     180.000000     150.000000
75%   60850049.500000     280.000000     280.000000     240.000000
max   62076634.000000  252560.000000  252560.000000   25000.000000

           earn_cost           ctit
count 1475031.000000 1475031.000000
mean      159.297658    1060.343629
std       321.611117   18927.725319
min         1.000000       0.000000
25%        30.000000      44.000000
50%       150.000000      81.000000
75%       240.000000     143.000000
max     25000.000000 2444653.000000

In [8]:
# adv_cost(광고 소진금액), earn_cost(매체사 수익금액) 만 남기기

rewards = rewards.drop(columns=['show_cost','rwd_cost'])

In [9]:
rewards.describe()

,rwd_idx,ads_idx,mda_idx,pub_sub_rel_id,dvc_idx,adv_cost,earn_cost,ctit
count,1475031.000000,1475031.000000,1475031.000000,1475031.000000,1475031.000000,1475031.000000,1475031.000000,1475031.000000
mean,239042983.839559,420134.498482,419.332570,25797059.266720,50579799.805650,391.075579,159.297658,1060.343629
std,425938.446114,82625.689183,265.017095,44503654.045392,11897231.126098,4641.356824,321.611117,18927.725319
min,238304802.000000,9716.000000,12.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,238674222.500000,435909.000000,303.000000,1.000000,42612825.000000,170.000000,30.000000,44.000000
50%,239043054.000000,440525.000000,396.000000,1.000000,54535366.000000,180.000000,150.000000,81.000000
75%,239411848.500000,444350.000000,563.000000,33306660.000000,60850049.500000,280.000000,240.000000,143.000000
max,239780622.000000,446909.000000,1061.000000,144682688.000000,62076634.000000,252560.000000,25000.000000,2444653.000000

In [10]:
'''
rwd_idx : 적립 row 고유키
ads_idx : 광고 키
ads_code : 광고 코드
mda_idx : 광고를 소비한 매체 번호
pub_sub_re_id : 광고를 소비한 매체의 하위 매체
dvc_idx : 디바이스키
advid : 디바이스 아이디
click_key : 클릭키
adv_cost : 광고 단가
earn_cost : 매체사 단가
click_date : 광고참여일시
regdate : 광고 참여완료일시
ctit : 지연시간(초)
'''

'\nrwd_idx : 적립 row 고유키\nads_idx : 광고 키\nads_code : 광고 코드\nmda_idx : 광고를 소비한 매체 번호\npub_sub_re_id : 광고를 소비한 매체의 하위 매체\ndvc_idx : 디바이스키\nadvid : 디바이스 아이디\nclick_key : 클릭키\nadv_cost : 광고 단가\nearn_cost : 매체사 단가\nclick_date : 광고참여일시\nregdate : 광고 참여완료일시\nctit : 지연시간(초)\n'

In [11]:
# 날짜관련데이터 테이트타임으로 타입 변환

rewards['click_date'] = pd.to_datetime(rewards['click_date'])
rewards['regdate'] = pd.to_datetime(rewards['regdate'])

In [12]:
rewards

,rwd_idx,ads_idx,ads_code,mda_idx,pub_sub_rel_id,dvc_idx,advid,click_key,adv_cost,earn_cost,click_date,regdate,ctit
0,238304818,413490,CFZ6lzEmeD,22,27496512,32947806,09b6a808-4f76-4584-87c5-626f21f472a0,b0e22dba943810794d25c993dff425c4e16d0744,190,120,2025-07-26 00:00:31,2025-07-26 00:05:02,271
1,238304829,413490,CFZ6lzEmeD,22,27496512,47387244,ba4fd0c8-4f06-4dfa-9c3f-c6b39ee7066e,0679ff4c6a14beba296e44d7ffdd88129f42ffbf,190,120,2025-07-26 00:00:32,2025-07-26 00:08:17,465
2,238304816,413490,CFZ6lzEmeD,22,27496512,32425124,64c675d0-8edd-4478-9906-a806651fdf92,68eb28d636724061da21e490a1afff6a39cd78f7,190,120,2025-07-26 00:00:42,2025-07-26 00:04:43,241
3,238304817,413490,CFZ6lzEmeD,22,27496513,34006545,a08ebb04-e70a-4492-89d4-17fa96bf8c75,37da42f12b6f732d8c8bf1a609c01e569b7f8a09,190,120,2025-07-26 00:00:54,2025-07-26 00:04:45,231
4,238304802,133653,rl8ud4uNQC,801,1,56867331,dbe54f40-41b5-4423-ae2f-048fd6ecf5af,624b1bbc57c9ea81005c74e1956d48e76d974816,260,195,2025-07-26 00:01:07,2025-07-26 00:02:04,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475026,239780599,356956,1UNE1La9yv,270,1,35431157,56296bc1-c155-4fa7-9888-72b195653deb,3dc358e1a2b6a3480ba45dc65f81a308bc6c5e70,5,3,2025-08-25 11:32:34,2025-08-25 11:32:44,10
1475027,239780621,445907,0gEJGntDo3,794,1,62076634,d46f85a9-e8e0-4017-8354-e93b0ffc5ffe,d3a189157fc1c3b458b44e485a38ad544b89402d,170,30,2025-08-25 11:32:37,2025-08-25 11:34:29,112
1475028,239780617,446855,yrwq08KCov,563,1,60605730,666272a3-4181-4635-84e7-de1df1008ace,c752e95c5a236c8799cbcf4dc516b7e09e1afda7,18,14,2025-08-25 11:32:47,2025-08-25 11:33:55,68
1475029,239780609,446837,2hznDD8Yx3,371,1,46271340,c91a2823-8a33-4d36-8900-966448fd0e56,4dc015e177c38a9d2d0cf65d2b2e146e79352683,13,9,2025-08-25 11:33:07,2025-08-25 11:33:15,8
1475030,239780612,356956,1UNE1La9yv,270,1,61667811,729dcecc-2369-4ead-88f4-0e8544c5e63f,ffbad59341e1268406e2e45f18dac5b7ee21a4e1,5,3,2025-08-25 11:33:22,2025-08-25 11:33:36,14

In [13]:
rewards[rewards['ctit']>=2000000]

,rwd_idx,ads_idx,ads_code,mda_idx,pub_sub_rel_id,dvc_idx,advid,click_key,adv_cost,earn_cost,click_date,regdate,ctit
18955,239719827,168828,CxZ48rIVgS,343,11082141,58340625,eeca111d-28a8-4c4b-a1ec-b42a283a3845,39d91507f52ced11be3913bd27f209ff57215f2d,11818,8160,2025-07-26 07:22:21,2025-08-23 14:26:34,2444653
41364,239268085,384133,RAMxbBaXMS,539,144296957,60136156,9f1efe9a-2bc1-4b54-9c92-573c55791a60,0cf9c4d1793d402bc1d656958de41a3e0a4113eb,1000,750,2025-07-27 01:24:28,2025-08-19 16:10:03,2040335
64330,239669021,431126,FS6DsZPo9z,270,1,54511321,5efa8110-f3a4-443e-b674-a1b944674470,bbbea430e5397cd0364ebe052502de9d8be5fd74,0,249,2025-07-27 15:48:12,2025-08-22 22:30:42,2270550
113898,239568581,96793,I8Px5zK2kJ,270,1,53928376,cbcf2037-b4e8-4bd2-9857-57e00f62395a,3dc9efbf770362995fa0c58b5e2765d2607d516d,0,280,2025-07-29 04:39:50,2025-08-21 18:21:06,2036476
148716,239717943,364671,c9GnZgmq9s,645,1,61752825,0e4c05ce-9c50-4082-935b-90f923bf03b3,1e924d5e35f096f9c768bbb0d15497337f477b98,9600,7000,2025-07-30 22:32:38,2025-08-23 13:00:12,2039254
191244,239759483,372307,oj212GwFsd,14,140199523,55053779,889ae5a8-830f-42ff-8d69-dcc7c8f39f7d,6e323e36caca6d15fd37a3df262ed460d749d87e,15600,11700,2025-08-01 07:27:25,2025-08-24 18:05:45,2025500

In [14]:
rewards[rewards['mda_idx']==539]

,rwd_idx,ads_idx,ads_code,mda_idx,pub_sub_rel_id,dvc_idx,advid,click_key,adv_cost,earn_cost,click_date,regdate,ctit
452,238306623,391165,VfoZmzvPFX,539,138362162,61072839,5d55a5a5-4029-4822-a1af-7f0e08a31847,c80fc7f9cd175f7d6f3c8996550c4775b0c9c202,280,180,2025-07-26 00:25:22,2025-07-26 00:48:02,1360
459,238305587,412426,yuRe4YoPuZ,539,135848306,44860380,aae899c9-5a8d-44dd-9772-3d9a70958c16,5ea01ad3b06c31aef07b28bfba43fd11b5869e61,180,160,2025-07-26 00:25:48,2025-07-26 00:34:37,529
465,238306894,391165,VfoZmzvPFX,539,144303596,60191722,e1f154cb-cc07-4486-ba14-a37e691d65ac,b218697c7f2f4cabf8f7902a99ea059e6b91a5bf,280,180,2025-07-26 00:26:01,2025-07-26 00:49:02,1381
737,238305473,412426,yuRe4YoPuZ,539,2563205,61698624,92c18b31-8fc7-4fc2-b101-febde9487b2e,0f9f67ffd882d6dcbb5ae2fd4281e350ecc0e18f,180,160,2025-07-26 00:32:18,2025-07-26 00:32:31,13
760,238305515,412426,yuRe4YoPuZ,539,138362162,61686819,e7465d37-8b7d-4523-ac8a-7e284d9eddc8,0b75a98dadfce32cb4dab6d5ac9cf9b2c8523406,180,160,2025-07-26 00:32:48,2025-07-26 00:33:23,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474861,239780488,334542,3RWdqVuBes,539,138362162,60953002,01e99edb-233a-4f45-a47d-f4dff1a4f812,b3a506af01da86338d2ed61d9f781bf950076d8c,1500,1000,2025-08-25 11:14:57,2025-08-25 11:21:13,376
1474887,239780498,334542,3RWdqVuBes,539,138362162,61955996,eb2ff5ec-a2c6-4c96-a60b-48c1b9b3b90f,737a37f06b43a035fe7f911d729ee39fc793e586,1500,1000,2025-08-25 11:17:58,2025-08-25 11:22:15,257
1474941,239780602,334543,dPdD08CEBi,539,138362162,46706738,6825f696-9168-4b6a-a862-775174fe6bd5,a5356dfd521006cdd31b3a06da596bf38eb21428,1500,1000,2025-08-25 11:23:29,2025-08-25 11:32:55,566
1474942,239780553,334540,3klpQP05kc,539,138362162,60953002,01e99edb-233a-4f45-a47d-f4dff1a4f812,e4fcb054680526849d408f9221b16374f26be8d5,1500,1000,2025-08-25 11:23:35,2025-08-25 11:27:50,255
1474944,239780568,334543,dPdD08CEBi,539,138362162,56852596,be5dce35-93c0-4169-a3bc-89b17a438761,53c0d6d672adee7ab6f36318220fe2f34e3bcae2,1500,1000,2025-08-25 11:23:41,2025-08-25 11:29:27,346

In [15]:
vote = ads[ads['ads_idx']==127906]

In [16]:
vote.to_csv("vote_sample.csv")

In [17]:
ads[ads['ads_idx']==441013]

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
439354,441013,DBnAFWELCR,1,1666,1212387,3,13,포춘쿠키 (1일 1회 재참여 가능),포춘쿠키 (1일 1회 재참여 가능),https://i.imgur.com/WXJLV3Q.png,...,0,100,7,2,2,2764300,ADS_CODE_DAILY_UPDATE,N,2025-08-06 10:12:22,N

In [18]:
device = rewards.groupby('dvc_idx').agg({'advid':'nunique'}).reset_index()

In [19]:
device

         dvc_idx  advid
0              0      0
1           1954      1
2           2048      1
3           4222      1
4          12412      1
...          ...    ...
642054  62076627      1
642055  62076629      1
642056  62076631      1
642057  62076632      1
642058  62076634      1

[642059 rows x 2 columns]

In [20]:
ads[ads['ads_idx']==435921]

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
434262,435921,yVK2kd2LpI,1,618,1202083,9,6,﻿드래곤 블러드: 레이더,﻿드래곤 블러드: 레이더,https://i.imgur.com/SAdWfTV.png,...,0,100,2,0,286,2735400,NONE,N,2025-07-24 15:20:11,N

In [21]:
rewards[rewards['adv_cost']<=rewards['earn_cost']]

,rwd_idx,ads_idx,ads_code,mda_idx,pub_sub_rel_id,dvc_idx,advid,click_key,adv_cost,earn_cost,click_date,regdate,ctit
18,238396237,435921,yVK2kd2LpI,270,1,61441961,031ac21a-69d4-47af-9e74-5c8f604d1db1,6bb38a798b366824144afd6ce9756bf1acb79200,0,200,2025-07-26 00:05:07,2025-07-28 09:07:56,205369
86,238398011,435921,yVK2kd2LpI,270,1,47952092,5598d504-8ca4-440f-81d0-fdc31d8f47d2,d31cce5d98e109433073638cc3bba2e6f7eb6272,0,200,2025-07-26 00:12:02,2025-07-28 09:56:16,207854
130,238406316,435921,yVK2kd2LpI,270,1,48174136,6dfba535-d7c7-4b6c-8d9c-77ef8226d9d6,0bc2e9e0cbd48f8e9c0e8efd5e1a8cff127ae0ac,0,200,2025-07-26 00:13:31,2025-07-28 16:46:59,232408
487,238397157,435921,yVK2kd2LpI,270,1,48801874,390ff309-0fe0-4194-8bc3-9f565b4806c4,016608ec807f7b6f4b529050dabfcee0eb43bccd,0,200,2025-07-26 00:26:45,2025-07-28 09:33:07,205582
3838,238396165,350415,9VIbFmxcD8,270,1,53561962,18123059-9eb3-4b4f-8535-292de7ff32bf,f0a48cb15b3ec3f7d92791e8101d861f7c7073f2,0,249,2025-07-26 01:09:18,2025-07-28 09:05:46,201388
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474648,239780194,22081,6KpGaxV4ot,270,1,60206234,3c116c53-e8d0-4184-913b-25a05200ddee,d78aa66842782aa57001f8ec8ed4aca7db4354d1,0,374,2025-08-25 10:48:51,2025-08-25 10:49:28,37
1474668,239780213,441013,DBnAFWELCR,371,1,58742443,72e41464-f383-4f8e-9999-1d6221376c39,d0d5b54ed0432a944fe24e322a1a8b3d0efd510d,2,2,2025-08-25 10:51:19,2025-08-25 10:51:30,11
1474669,239780222,435910,wLM4t3Yi65,787,1,0,NaN,7e87a893785887d678ab20675386fc8c7554b60c,2,2,2025-08-25 10:51:38,2025-08-25 10:52:02,24
1474757,239780315,435910,wLM4t3Yi65,785,1,52937461,A20B550F-6CCD-4492-91CF-6CBD860A9F30,75c5adf826ff0b771c92805f768d5a1a98f72008,2,2,2025-08-25 11:01:55,2025-08-25 11:02:17,22
1474782,239780344,441013,DBnAFWELCR,54,144682688,62076494,c65f25de-0023-4577-893a-d9d89ce234fa,4a8ccf6195377c361fce1b981bc86c624b636e30,2,2,2025-08-25 11:05:07,2025-08-25 11:05:20,13

In [22]:
ads = pd.read_csv("/Users/Jiwon/Documents/GitHub/final_project/data/IVE_광고목록.csv")

/var/folders/6n/tjcbrygj54s39y61m4r7ymrr0000gq/T/ipykernel_88157/1411436255.py:1: DtypeWarning: Columns (12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  ads = pd.read_csv("/Users/Jiwon/Documents/GitHub/final_project/data/IVE_광고목록.csv")

In [24]:
ads[ads['ads_idx']==435921]

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
434262,435921,yVK2kd2LpI,1,618,1202083,9,6,﻿드래곤 블러드: 레이더,﻿드래곤 블러드: 레이더,https://i.imgur.com/SAdWfTV.png,...,0,100,2,0,286,2735400,NONE,N,2025-07-24 15:20:11,N

In [25]:
ads[ads['ads_idx']==436643]

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
434984,436643,drcbDlOweT,81,1597,1222152,3,5,PLAYTIME - 게임으로 돈 벌기,"PLAYTIME - 게임으로 돈 벌기,pro.cashtree,2612429",https://cdn.mychips.io/thumbnail/28a64816c3edd...,...,0,100,2,13320,10000,2467400,NONE,Y,2025-07-25 18:53:56,N

In [26]:
ads[ads['delyn']=='Y']

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
7,1142,zQ76Efhdj3,9,0,0,3,0,데저트스톰_사전예약(desert_storm_cpa),"데저트스톰_사전예약(desert_storm_cpa),,3281",http://img.shallweadcorp.com/AdImage/Campaign_...,...,0,100,2,650,590,22100,NONE,Y,2017-01-05 11:31:16,Y
14,1180,ngo2OKJYga,0,32,0,1,1,지하철종결자,"지하철종결자,kakao44c6187801b61d99667c6c68852ed5a3://,",https://lh5.ggpht.com/1Wpnz4mt5wYxilWF2njQtc2w...,...,0,100,1,1,1,987900,NONE,Y,2017-01-11 16:47:10,Y
26,1220,YAxjTA2iP5,1,64,0,1,1,메탈크래쉬,"메탈크래쉬,com.chaplingame.metal.kor,",http://imgur.com/is9g8KQ,...,0,100,3,200,150,988900,NONE,Y,2017-01-19 18:34:22,Y
456,2039,28SaZM6shd,6,10,6652,3,0,핀크 가입 이벤트,"핀크 가입 이벤트,com.finnq.f1,adc608c9f297e0a4fd202a7...",https://lh3.googleusercontent.com/KgthZ-ko-J1W...,...,0,100,3,700,595,670700,NONE,Y,2017-12-08 15:06:55,Y
475,2058,yGoECaidUz,1,84,0,1,1,변호사님닷컴,"변호사님닷컴,,",https://i.imgur.com/nQs6SP5.png,...,0,100,1,190,150,1005400,NONE,Y,2017-12-15 13:21:11,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439413,441072,VPtZb3BS8m,57,84,0,3,8,[클릭메이트-단골맺기] 홍선수,"[클릭메이트-단골맺기] 홍선수,af85d514-917f-40d7-bc0d-25ed3...",https://s3.ap-northeast-2.amazonaws.com/com.ga...,...,0,100,7,200,150,2757200,NONE,Y,2025-08-06 14:16:36,Y
440342,442001,E5RRhoL1eT,8,50,0,1,2,초월자 키우기,"초월자 키우기,com.playgames.transcender,75246003",https://static.adbrix.igaworks.com/adpopcorn/2...,...,0,100,2,170,120,2758500,NONE,Y,2025-08-08 16:54:36,Y
442692,444351,dY7jZ77yka,15,1672,1218845,1,2,[원스토어] 조조의 꿈,"[원스토어] 조조의 꿈,com.teamquest.Threekingdoms_GP",https://i.imgur.com/TYzuYah.jpeg,...,0,100,3,180,120,2760700,NONE,Y,2025-08-14 15:33:46,Y
442693,444352,MnWcfxDVbK,15,1672,1218853,2,2,조조의 꿈,조조의 꿈,https://i.imgur.com/TYzuYah.jpeg,...,0,100,1,280,180,2760800,NONE,Y,2025-08-14 15:33:53,Y
443038,444697,EbBjfvoNFa,48,1673,0,3,8,커넥트 CONNECT (여성),"커넥트 CONNECT (여성),com.jaehyuck.connect",https://i.imgur.com/PpBQs8g.png,...,20,34,2,1600,1000,2761500,NONE,Y,2025-08-16 15:14:02,Y

In [27]:
ads['ads_rejoin_type'].nunique()

3

In [28]:
rewards.to_csv("수정_광고적립.csv", index=False)

In [29]:
ads['ads_sdate'] = pd.to_datetime(ads['ads_sdate'],errors='coerce')

In [30]:
ads['ads_sdate']

0        2016-12-01 00:00:00
1        2016-12-29 00:00:00
2        2016-12-29 00:00:00
3        2017-01-01 00:00:00
4        2017-01-01 00:00:00
                 ...
445255   2025-08-25 11:08:15
445256   2025-08-25 11:12:12
445257   2025-08-25 11:12:16
445258   2025-08-25 11:00:00
445259   2025-08-25 11:00:00
Name: ads_sdate, Length: 445260, dtype: datetime64[ns]

In [31]:
ads_head = ads.head(200)

In [32]:
ads_head.to_csv("광고목록.csv")

In [33]:
ads

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
0,160,tr71opm6C1,6,10,13604,1,1,리니지레드나이츠,"리니지레드나이츠,com.ncsoft.redknights,ecaab3f9d2616f6...",https://lh3.googleusercontent.com/oDGXxngO9oOP...,...,0,100,2,170,150,982800,NONE,Y,2017-04-06 13:19:53,N
1,284,xlNpfkgtLX,6,10,13605,1,1,강철의함대:Ocean Overlord,"강철의함대:Ocean Overlord,com.gamepub.lw.g,a370ab70...",http://nextapps-nas.aws.appang.kr/icon/2016122...,...,0,100,2,180,160,987200,NONE,Y,2017-01-10 10:37:22,N
2,292,7Hj8V5QKiy,6,10,13606,1,1,스노우 SNOW,"스노우 SNOW,com.campmobile.snow,5b892d7e0cff73621...",http://nextapps-nas.aws.appang.kr/icon/2016092...,...,0,100,2,160,160,987300,NONE,Y,2017-01-02 12:51:34,N
3,304,1RfxHJcuEe,6,10,13607,2,1,서머너즈 워: 천공의 아레나,"서머너즈 워: 천공의 아레나,com.com2us.smon.normal.freeful...",http://nextapps-nas.aws.appang.kr/icon/EecpHzP...,...,0,100,2,230,210,931000,NONE,Y,2017-03-30 17:05:23,N
4,306,l3GyilYEVk,6,10,23543,1,1,하이마트,"하이마트,com.himart.main,8230c6a95581533fad10b0e3b...",http://nextapps-nas.aws.appang.kr/icon/2016032...,...,0,100,2,170,140,1155100,NONE,Y,2017-06-12 15:24:46,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445255,446914,qy1HUatIL9,85,1631,1223705,3,4,한식뷔페&카페 봄날,"한식뷔페&카페 봄날,search@120270",https://i.imgur.com/XdcGFx7.jpeg,...,0,100,7,16,10,1369920,ADS_CODE_DAILY_UPDATE,N,2025-08-25 11:08:15,N
445256,446915,UKnGFJUnmg,84,1623,1223706,3,4,용융소금,"용융소금,12335",https://adwize.co.kr/common_img/reward/GNSQ_IC...,...,0,100,7,15,10,1369919,NONE,N,2025-08-25 11:12:12,N
445257,446916,g3lUg3nuxR,86,1655,1223708,3,4,1kg 원두커피 블렌드 7종 맛있는 당일로스팅 고소한 납품 도매 납품 홀빈 180244,1kg 원두커피 블렌드 7종 맛있는 당일로스팅 고소한 납품 도매 납품 홀빈 1802...,https://cashplan-r2.uk/quiz-mission.png,...,0,100,7,18,12,1369918,ADS_CODE_DAILY_UPDATE,Y,2025-08-25 11:12:16,N
445258,446917,0GLHsRVZNv,57,84,1223711,3,8,[가입하기] 슈퍼티비,"[가입하기] 슈퍼티비,870fd97e-ac5d-45d8-be70-e47649f56f52",https://s3.ap-northeast-2.amazonaws.com/com.ga...,...,0,100,7,300,225,2764400,NONE,Y,2025-08-25 11:18:35,N
445259,446918,k2YLVkNAuO,57,84,1223710,3,8,[가입하기] 나인티비,"[가입하기] 나인티비,25801869-3c50-4f4f-94d4-246153690745",https://s3.ap-northeast-2.amazonaws.com/com.ga...,...,0,100,7,300,225,2764500,NONE,Y,2025-08-25 11:18:54,N

In [34]:
delyn = ads[ads['delyn']=='Y']

In [35]:
delyn.to_csv("삭제여부y.csv")

In [36]:
rewards[rewards['ads_idx']==17793]

Empty DataFrame
Columns: [rwd_idx, ads_idx, ads_code, mda_idx, pub_sub_rel_id, dvc_idx, advid, click_key, adv_cost, earn_cost, click_date, regdate, ctit]
Index: []

# 광고 참여 정보 분석

In [37]:
participate = pd.read_csv("/Users/Jiwon/Documents/GitHub/final_project/Jiwon/수정_광고참여정보.csv")

In [ ]:
web = participate[participate['dvc_idx']==0]

In [ ]:
web['mda_idx'].nunique()

21

In [ ]:
web

,click_key,ads_idx,dvc_idx,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip
478,00020a6283bd4ed1782a6761eb385472ac54522f,130275,0,980,1,88275,3490,2025-07-30,23,2025-07-30 23:16:27,2025-08-29,NaN,3.37.30.21
697,0002f2005851ccb5c7de76b397ea20ef029f1490,444244,0,654,144677817,2000,1000,2025-08-15,6,2025-08-15 06:34:29,2025-09-14,MOBILE,211.36.140.31
752,0003294b3c83b0a68b3395ac71ab1d81488c32d0,444244,0,654,144677810,2000,1000,2025-08-15,10,2025-08-15 10:03:14,2025-09-14,MOBILE,211.177.115.17
1645,00069b1235251c14f3bf1dd8179a80e7894b2cdd,73878,0,654,137882873,4000,3200,2025-07-26,11,2025-07-26 11:57:00,2025-08-25,MOBILE,211.216.25.28
2481,0009db33d369bab564bba210f35257ec5679fe32,73878,0,654,144677820,4000,3200,2025-08-04,5,2025-08-04 05:41:07,2025-09-03,MOBILE,211.234.192.120
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16853262,fff9ad76da724e0449c887fef42be627fa6f9487,73878,0,654,144677820,4000,3200,2025-08-03,19,2025-08-03 19:05:26,2025-09-02,MOBILE,211.234.195.38
16853290,fff9bf88cced6a10ac415a423e9e487690ace50b,429485,0,980,1,87120,3400,2025-08-11,12,2025-08-11 12:10:57,2025-09-10,NaN,44.223.88.80
16854286,fffdbb9e7d038ce2da77812f7d779e71105417ec,73878,0,654,144677826,4000,3200,2025-08-21,21,2025-08-21 21:24:41,2025-09-20,MOBILE,124.197.144.241
16854439,fffe52a04fd8531fd9e545359ae255d688af26a9,73878,0,654,144678068,4000,3200,2025-08-19,21,2025-08-19 21:10:39,2025-09-18,MOBILE,211.36.130.186
16854729,ffff85abde1cbbfa4ba9d16c8af82f1035cce925,444244,0,654,144677810,2000,1000,2025-08-15,17,2025-08-15 17:41:06,2025-09-14,MOBILE,27.162.117.93

In [ ]:
web['mda_idx'].unique()

array([ 980,  654,  714,  540,  583,  755, 1055, 1042,  769,  480,  978,
        787,  481,   73, 1023,  437, 1050,  539, 1049,  398,  710])

array([0])

In [ ]:
participate[participate['mda_idx']==980]['dvc_idx'].unique()

1

In [ ]:
participate[participate['mda_idx']==654]['dvc_idx'].unique()

1

In [ ]:
participate[participate['mda_idx']==1055]['dvc_idx'].unique()

array([0])

In [ ]:
participate[participate['mda_idx']==787]['dvc_idx'].unique()

array([0])

In [ ]:
web_info = web.merge(ads, on='ads_idx', how='left')

In [ ]:
pd.set_option('display.max_columns', None)  # 모든 컬럼 표시
pd.set_option('display.width', None)        # 가로 폭 제한 없음
pd.set_option('display.max_colwidth', None) # 컬럼 내용 길이 제한 없음

In [ ]:
web_info['ads_name'].unique()

array(['[블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스', '국가통합바이오빅데이터구축사업 참여 사전신청',
       '굿툰 7일 무료체험', '실버 등급 패키지', '류현진 데이렉스 엑소좀겔 마사지 크림 50g',
       'KWDA 가챠이벤트 1만 투표권', '[일반] 10만 투표권 + 1만 보너스',
       '[일반] 30만 투표권 + 4만 보너스', '[일반] 5만 투표권', '[일반] 1만 투표권', '로보주식플러스',
       '[쎄븐업플러스]철갑상어 건강즙 70ml 30포', '블랙 등급 패키지',
       '짐스낵 다이어트 간식 프로틴 단백질 쿠키 과자', '[동원] 리챔 더블라이트 200g X 8캔',
       '골드 등급 패키지', '[실버] 5만 투표권 + 500 등급 보너스',
       '면세점입점 나틴다 승무원팩트 실키커버 21호', '[록키스] 아쿠아 부스트 옴므 올인원 2개',
       '[골드] 30만 투표권 + 4만 보너스 + 6,000 등급 보너스', 'H.point 회원가입',
       '[블랙] 5만 투표권 + 1,500 등급 보너스', '충청남도 X(트위터)',
       '굿매너 뽑아쓰는 키친타올 3겹(100매×9팩)',
       '[실버] 10만 투표권 + 1만 보너스 + 1,000 등급 보너스', '[실버] 1만 투표권 + 100 등급 보너스',
       '원데이즈유 콜라겐 하이드로겔 아이패치 60매', '[블랙] 10만 투표권 + 1만 보너스 + 3,000 등급 보너스',
       '[실버] 30만 투표권 + 4만 보너스 + 3,000 등급 보너스', '고잔갈비 안산본점',
       '오스틴제약 비타 이뮨 플래티넘 골드 15병', '[뉴바이오]덴타골드치약 200gx2개 세트',
       '매드라운드 에고이즘 오드퍼퓸 30ml', '아론샵 홀드맥스 헤어젤 120ml',
       '[테스트] [블랙] 10만 투표권 + 1만 보너스 + 3,000 등급 보너스', '맛다움 해물짬뽕 450g',
       '퍼니트 하루하나 유기농 레자몽 14포', '날엔퍼퓸 날엔세트 (코튼+우드 SET)',
       '스퀘어가든 퓨어 네이비 빨래바구니', '주식투자 정보서비스', '뉴네이처 알티지오메가3파워 1400 60캡슐',
       '토마스 풀 전기 드립포트 1.2L ', '코오롱 쎈류신에너지파워 1,000mg 120정',
       '스치듯 포레스트 고체향수 15g', '뷰티앤소프트 화장지 (30m x 30롤)', '[정답입력] 올림픽공원 맛집',
       '굿매너 피톤치드 화장지 (30m x 30롤)', '화곡원 국산 하루힘차(흰민들레+대추) 30티백',
       '아론샵 원스텝 스트레이트 펌 매직약 150ml', '평거동 맛집', '뉴스캐시',
       '키친플래그 오일 스프레이 4종 세트', '[골드] 10만 투표권 + 1만 보너스 + 2,000 등급 보너스',
       '헬스케어', '나틴다 알로에베라 딥 클렌징폼 130ml', 'KB다이렉트 운전자보험',
       '2+1 한돈 간장 돼지불고기 800g+400g', '초전동 맛집', '마법선생 네기마!',
       '스템샷 안티 헤어로스 세럼(탈모방지헤어에센스)', '햄튼 네오블 마블코팅 후라이팬 24CM',
       '코오롱제약 닥터 독일 리놀렌산 송침유VIP', '맛다움 프리미엄 짜장 350g',
       '[독일 제너] 실리콘 우드 키친툴 8종 세트', '엑소머 더 넥스트 셀 부스팅 니들 톡스 볼륨샷',
       '2+1 간장 양념소불고기 800g+400g', '화곡원 여주해죽순돼지감자차 30티백',
       '[수앤리빙]마뜨앙 여행용 기내형캐리어 20인치', '이프티 모로실 다이어트 모로오렌지 15포',
       '충청남도 카카오스토리 소식받기', '제주탄산수 탄산오름 250ml 12병(혼합)', '웰로 고향사랑기부', '닭갈비',
       '[삼성] 체인미 산양유단백콜라겐유산균', '미각기행 목전지 수제 돼지양념구이 400g',
       '[블랙] 1만 투표권 + 300 등급 보너스', '엘루자이 포맨 페로몬 향수 50ml',
       '스위스 몽크로스 프라젠 BBQ 전기그릴', '독일 코겔 원터치 진공 쌀통 바로락 5kg',
       '[이엔비]유기농 레몬즙 20g X 14포', '똑똑보카 룰렛이벤트!',
       '굿매너 롱앤소프트 화장지 (40m x 30롤)', '라에스떼 셀워터샷 샤인 미스트',
       '[청담 헤어샵] 아론샵 실크 리페어 샴푸 1L', '유유제약 마시는 관절건강 MSM 30포',
       '청담 아론샵 실크 리페어 트리트먼트 1L', '매드라운드 카타르시즘 오드퍼퓸 30ml',
       '백년약방 염색 가인(천연 염색제) /내츄럴블랙', '미각기행 목동 곤이알찜 550g x 2팩',
       '셰퍼 글라스 에어 프라이어 JSK-N3005', '[정답입력] 부산요트투어', '[수앤리빙] 마호가니 사각도마',
       '청담 아론샵 실크 홀드 스프레이 120ml', '토마스 풀 패밀리 3in1 멀티 와이드 그릴',
       '미세먼지 알리미 직과금', '[가이타이너] 자우버 프로 보풀제거기',
       '아이나비 힙합독 방향제 ICD-H3+아로마오일', '[골드] 1만 투표권 + 200 등급 보너스',
       '더화이트 대용량 화장지 (27m x 36롤)', '황후지화 24K 골드 프레스티지 리페어 7종',
       '김소형 보감탕 30포 [쇼핑백포함]', '순수달 1종 주방세제 4L x 2개',
       '미노벨 노벨패스 7일 무료체험 이벤트', '[씨피큐 메가라이프] 기억력개선 120캡슐 특가',
       '토마스 풀 3D 백허그 목/어깨 안마기', '키친플래그 스테인레스304 냄비 3종 세트',
       'US 스킨아우라히알루론비타 60캡슐', '[퀴즈] 여수돌산카페', '송정골 언양식 바싹불고기 한판 180g*3봉',
       '[마이픽] 캠핑 웨건 (검정)', '나틴다 콜라겐 수분채움 미스트 100ml',
       '코오롱제약 쎈 유단백 추출물 콘드로이친N플러스', '나틴다 아우라 퍼펙트 커버 쿠션 21호',
       '셰퍼 에디번 전기 그릴 JSK-N4005', 'Tubble 파워클린 다목적 세정티슈 60매',
       '동원 웰로 오트밀 참깨치킨 3개+단호박3개', 'KB다이렉트 자동차보험 가입',
       '[동원] 밀크팡 산양유프로틴 70g x 20개', '더 퍼스트 프리미엄 골드 스팀 헤어팩 마스크',
       'US 아쿠아셀 오메가3 1300mg 60캡슐', '[뉴네이처] 다이렉트 다이어트N유산균',
       '라끄시안 올인원 페이셜 로션 150ml', '빨간통 뉴엑소덴 분말치약1세트 3통(3개월분)',
       '앤씨 식물성 NMN365 파이토 플러스 30정', '라끄시안 화이트 퍼퓸 핸드크림 100ml',
       '플라리떼 달라이룸 오드퍼퓸 30ml', '로니웰 유기농 레몬즙100 14포 x 2세트',
       '엠트리 Dr.5.8 톤업 선크림 1+1 특가', '더 편한 크리스탈 베개',
       '[정답입력]포항시 북구 영일대 요리주점', '바로로그인 가입 이벤트',
       '코스모팜 루테인 아스타잔틴180캡슐(6개월분)', '아르기닌 앤 마카 의성 흑마늘 30포',
       '앙샹테 엠보 물티슈 80매 x 5팩', '코스모팜 브레인1088 120정(2개월분)', '스마트 안티피싱 서비스',
       '새우표 완도 오리지널 전장김 20봉', '신차장기렌트카', '[해든]물냉면+함흥냉면 총 20인분',
       '[여드름성 피부특화] 카밍 리프래쉬 클렌징 폼', '백년 약방 코뻥 코힐밤',
       '일초픽 감자토너패드 180ml (70매)', '[국내제조] 보보랑 다짜요 야채 나물짤순이',
       '붓처스컷 뉴욕 스트립스테이크+크림 스피니치소스', '보안플러스 무료체험', '[하림] 마늘후랑크 12개',
       'KWDA 가챠이벤트 30만 투표권', '홍여진 온몸愛 찜질박사 1EA',
       '김수미가 추천하는 엘린까사 함마톤 스텐3종냄비', '안심보호', '보령파워 MBP 락토페린 120정(4개월분)',
       '독일몬타 도깨비냄비 24cm(5~6인용 세트)', '몬타 5분 점보솥밥 플러스 3-4인용',
       '범죄알리미 (무료체험)', '동국제약 영묘사향 경력고 골드 30포+쇼핑백',
       '[고운삼] 발효홍삼 산삼배양근 활력진골드 앰플', 'KB다이렉트 자동차보험',
       '닥터로니 하이드라 에이 앰플 50ml', '배곧맛집', '뉴프리 로얄 자연을 담은 순녹용 골드 30포',
       '아띠코스 24k 골드 앰플 50ml', '알로하 시어서커 베개커버', '쿨링조이 냉감 바디필로우',
       '[우디니]락토페린 산양유 단백질 밸런스100포', '[사보텐] 콰트로 치즈카츠 3팩',
       '나틴다 리얼매직커버 선비비크림 50g', '[고단백 칼슘우유] 오트오브맘 바나나 24팩', '탑툰',
       '아다바트 팔토시 팔목형(혼성)_화이트', '미각기행 목동 소내장탕 650g x 3팩',
       '라에스테 셀코어샷 바이탈 로즈 앰플 50ml', '신한 SOL페이 퀴즈팡팡 퀴즈 풀면',
       '이희 퀸즈골드 케라틴 키퍼 120ml', '나틴다 매직 헤어커버 스틱 (내추럴브라운)',
       '[메디카코리아]히밥 HEEFIT 곡물발효효소', '[동의삼] 구증구포 흑도라지 발효흑삼고',
       '트리사 스위스명품 플렉시블 액티브 칫솔 10P', '국물 닭한마리 볶음탕 1.4kg',
       '8월 환급금 평균 960만원(신규 한정)', '서울약사신협 프리미엄 6년근 흑삼진액 30포',
       '셀트리온 셀린온 레티펩 링클업 크림', '원데이즈유 미백 미녀크림 더블유(리뉴얼) 50ml', '미툰 7일 무료체험',
       '셰퍼 피크닉 와인잔 글라스 2pcs', '키친플래그 3단 타포린 분리수거함',
       '[골드] 5만 투표권 + 1,000 등급 보너스', '코스모팜 면역 프로알파칸 120정(4개월분)',
       '퍼니트 워너비 알파CD 알파시클로덱스트린14포', '순수달 세탁세제 대용량 2.5L (총10리터)',
       '키친플래그 스테인레스304 슬라이드 채반', '[신신제약] 선라이더 선 스크린 스틱 바',
       '동국 혈당케어 앤씨 레몬 딥 발효효소 30포', '몬타 싹풀려 집중강타 안마기',
       '이상복 경주빵 800g(40gx20개입)', '퍼니트 먹는 레티놀C 1000 2g x 30포',
       '[동원] 면발의신 동치미 물냉면+오이비빔냉면', '[염증성 통증케어] 큐리신 PF크림 120ml',
       '영국 토마스풀 로망스 티포트 1L 화이트', '대웅생명과학 헬스온 프리미엄 눈마사지기 플러스',
       '대원제약 엘라스틴 콜라겐 2g x 30포', '[동원] 루피는 참치마요 100g x 10캔',
       '2+1 한돈 마라 돼지불고기 800g+400g', '휴라이프  프레스코 화장품 냉장고(6L)핑크',
       '스퀘어가든 라포레 IH 프라이팬 세트 3종', '미래에셋증권 신규고객 이벤트',
       '가이타이너 아보카도 인덕션겸용 냄비 4종세트', 'USIM스마트인증 서비스',
       '앙샹테 맑고 깨끗한 화장지 30m x 30롤', '렌지순대(오리지널맛) 165g x 4세트',
       '덴마크 유산균 프로바이오틱스 90포(선물세트)', '휴라이프 샬롱 BLDC 드라이기 그레이', 'MyOTP',
       '[고단백 고식이섬유] 오브맘 프로틴메이트14P', '포춘쿠키 (1일 1회 재참여 가능)',
       '[수앤리빙]캐리어 기내용20인치+레디백14인치', 'WHT TISSUE 천연펄프 25m x 30롤',
       '아론샵 실크 리페어 쿨샴푸 1000ml', '[김소형원방] 본초홍삼골드 70ml x 30포',
       '게임믹(7일 무료체험)', '트루클린 캡슐세제 30P (모닝머스크)', '쿨링조이 냉감 베개커버 L',
       '토마스 풀 커피메이커 0.65L', '[정답입력]법무법인대륜울산분사무소-20250725-191',
       '[지리산마천농협] 6년근 녹용홍삼진 30포', '순수달 섬유유연제 대용량2.5L (총10리터)', '올레시장 맛집',
       '토마스 풀 스텐 토스터기 WT-541 ', '아띠코스 보드란 풋크림 튜브형 100g',
       'ihee 헤어클리닉 극산성복구 애시드 클리닉', '[백년약방] 피부애착 녹유 크림 50ml',
       '제주탄산수 탄산오름 250ml 12병(감귤)', '발포로빼 발포비타민 30정 탄산다이어트',
       '코오롱제약 쎈쏘팔메토VIP 120캡슐', '동원 웰로 오트밀 단호박 285g X 6개',
       '아론샵 노워시 트리트먼트 헤어팩 200ml', '언박싱팩토리 4in1 멀티 PD 고속충전케이블',
       '스퀘어가든 플레인 캐리어 2종 세트 블랙', '황후지화 한방 3종세트 [쇼핑백 포함]',
       '서울약사신협 참진한 흑마늘 진액 30포', '영진제약 타우린L-아르기닌1000골드', '수성구 치과',
       '[퀴즈] 여행용 프리볼트 고데기', '미각기행 공주 정안 깐알밤 600g (대)',
       '[동의삼] 꿀배도라지홍삼 진액스틱 100포', '휴나인 매스틱 검 1000 스톰큐',
       '제주탄산수 탄산오름 250ml 12병(레몬)', '청담 아론샵 실크 리페어 염모제+산화제_1N',
       '[동의삼] 천녹용홍삼침향 진액스틱 100포', '[정답입력]울산 한우 떡갈비', '[동원] 야채참치 90g x 8캔',
       '테디베어 피톤치드 탈취제 500ml 본품2개 ', '포크너 부천점', '[정답입력] 신논현 맛집',
       '운세 보면 리워드+네이버페이 지급', '라에스테 퍼펙트 듀오 컨실데이션 32ml', '에어매쉬토퍼 S 화이트',
       '보령 류신단백질 프리미엄 240정(4개월분)', '포춘텔러 무료체험',
       '동원 바른어묵 냉동 얇은사각 1kg x 2봉', '오스틴제약 연어코프로테오글리칸프리미엄',
       '[수앤리빙] 마호가니 원형도마', '서울약사신협 하루 한 포 홍삼정스틱 30포',
       '[김소형] 헤밀레 락토프레쉬 앤 쑥 여성청결제', '거미입니다만, 문제라도?',
       '굿매너 아이보리 롤화장지 (22m x 36롤)', '닥터로니 하이드라 이지 크림 50g', '쭈꾸미',
       '베스트하임 UV 안심 변기 살균기,자동살균', '[뉴네이처] 알티지오메가3파워1400 60캡슐',
       '[칸투칸] 유틸리티 3-WAY 더플백 블랙', '1+1 베아르시 쿨토시+전용파우치 총 2set',
       '스퀘어가든 퍼블 식기 홈 세트 16p', '미각기행 목동알탕670g(2~3인분) x2팩 ',
       '[정답입력]서면 치킨스테이크', '메딕서 엑소머 셀 이펙터 세럼', '나틴다 데일리 퍼펙트 선크림 50g',
       '[요아럽] 올포유(All 4 U)', '보령 콘드로이친 칼마D(800mgx90정)',
       'ZETABIT 부스터 마사지건 SLG-1000', '전화번호 안심로그인 ',
       '808 넥도리 휴대용 온열 목난로(화이트)', '김소형원방 흑염소 프리미엄 70ml x 30포',
       '셰퍼 블루밍 IH 냄비 24cm', '스퀘어가든 접이식 2단 카트 JSK-N3029', '돈버는 운 - 부자되는 운',
       '충청남도 페이스북', '리치앤홈 퓨어헤븐 냉감 고무밴딩패드 Q', '오직청춘 퓨어 알로에 폼클렌징 500ml',
       '세븐맘 딥슬립 경추베개 화이트', '[퀴즈] 동래역 랍스타', '셰퍼 아이케어 눈마사지기 JSK-N4040',
       '코리아나 제니스웰 골프 퍼팩트맨 3종세트', '책상 스탠드', '진주 맛집', '[퀴즈] 굴포천역 헬스장',
       '아론샵 퍼퓸미스트(로즈앰버) 120ml', '앤씨 브로멜365 퀘르세틴 파인애플효소 30포',
       '이희 더 퍼스트 스파 테라피 세트', '바바더닷컴_N', '오직청춘 퓨어 알로에겔 300ml',
       '[테스트] [블랙] 5만 투표권 + 1,500 등급 보너스', 'G마켓 4만원 이상 구매하기 ',
       '[농심]신라면 10개+오뚜기밥 10개', '퍼니트 콜린 미오이노시톨 엽산 포 우먼 30포',
       '가이타이너 코헴무선스팀다리미GTLIR-2000', '스퀘어가든 라포레 IH 냄비세트 3종',
       '몰트 가방포함  Q(퀸) 그레이', '[반전립스틱] 나틴다 매직 타투 트윙클 립스틱',
       '호텔식 네스트 경추베개 화이트', '[정답입력] 이유식', '셰퍼 아쿠아 무드등가습기 JSK-N4076',
       '[아이리버] 종아리 EMS 마사지기 CE010', '코오롱제약 화이트 리포좀 비타민C', '대추차',
       '[체지방감소 인정] 오브맘 다이어트유산균30P', '[정답입력] 동래 랍스터 맛집',
       '밴디 양방향 미끄럼방지 실내 욕실화(그레이)', '진주고깃집', 'AT스탁플러스',
       '[디라이프] 글라스뷰 에어프라이어 3.5L', '[뉴트리하버]모로오렌지 C3G 프리미엄 60정',
       '세이스킨 오로라플러스플라즈마 피부관리기 화이트', '[정답입력] 애월 맛집',
       ' 어글리파스텔 니치향수 자아 55ml', '휴리엔 가정용 음식물처리기 HD-017',
       '[비욘드오리진] 멀티비타민미네랄 플러스', '[스템샷] 탈모 케어  안티로스 앰플 3개입',
       '네이처프리 카무트효소1500 프리미엄 180정', '신한라이프 마케팅동의 이벤트',
       '원데이즈유 포어 타이트닝 토너 150ml', '띠운세 (1일 1회 재참여 가능)',
       '2+1 블랙앵거스 양념 LA갈비1kg+500g', '연세생활건강 당당컷 다이어트 60정', 'T올케어 보험 가입',
       '[독일 제너] 톱날과도 2종 색상랜덤', '새우표 프리미엄 명인 완도김 선물세트',
       '니봇 4 in 1 멀티믹서기 JSK-N4012', 'WHT TISSUE 천연펄프 18m x 30롤',
       '메디트리 순 유기농 레몬즙 50포', '닥터로니 바이오 비타민 비나인 앰플 50ml', '평생총운 가입 이벤트',
       '라에스떼 셀토닝샷 그래핀 필링 패드', '밸런스어게인 흑삼 기황단 30환(쇼핑백포함)',
       '[가이타이너] 퓨어클린 침구 진공청소기', '[청춘떡방]찹살떡 10개입+햄치즈 설기10개',
       '[동의삼] 생생녹용침향단 3.75g X 32환', '[강남 헤어샵] 아론샵 아르간 에센스100ml',
       '동국 이너락토 프로바이오틱스VL8 (30캡슐)', '매드라운드 나르시즘 오드퍼퓸 30ml',
       '[면세점입점] 나틴다 매직 타투 골드립스틱', '굿매너 퓨어앤베이직 화장지(20m x 30롤)',
       '자연에서 온 녹차 화장지 (25m x 30롤)', '[정답입력]웨딩액자-20250729-88',
       '편백나무 홈케어 황토볼 발마사지기 _중사이즈', '[대원제약] 액상 마그네슘B 25g X 15포',
       '셰퍼 에디번 와이드 전기그릴 JSK-N4007', '키친플래그 스테인레스304 밀폐찬통 4종 8P',
       '탑운세 7일 무료체험', '[저장하기]거제 구조라리 유람선 추천', '에어매쉬토퍼 S 그레이',
       '굿매너 순백 화장지 (30m x 30롤)', '휴라이프 큐라 갈바닉 마사지기JSK-N4098',
       '셰퍼 믹스웰 블랜더(JSK-N4019)', 'G마켓 2만원 이상 구매하기 ',
       '일양약품 바이탈 NMN(엔엠엔)퀘르세틴 30정', '[정답입력]포천 소흘읍 소불고기',
       '가이타이너 슈라우프 올스텐 냄비 3종', '올데이잇 다이어트커피 체지방감소 보조제 30포',
       '코오롱제약 뼈튼튼 비타민 K2&D3 30정', '이희 헤리티지 딥 그린 샤인 미스트 150ml',
       '아띠코스 포르셀 워터 글라이드 마사지 젤', '[동원천지인]6년근홍삼정에브리원 10g 30포',
       '셰퍼 올플레임 IH 세라믹 후라이팬 28cm', '[동원] 양반 귀리쌀죽 400g x 6개', '체크플러스',
       '달콤한 레몬어트 유기농 NFC 레몬즙 14포', '몰트 가방포함  Q(퀸) 민트', '[정답입력]연남동 카페',
       '휴라이프 에브리원 헤어드라이어JSK-N4050', '미툰 코인 구매 (5천원 이상)',
       '비상교육 온리원(30세~58세 여성)', '스템삿 헤어 탈모 헤어 에센스 돌돌이',
       '이희 헤리티지 딥 그린 트리트먼트 235ml', '코오롱제약 쎈 장어활력VIP 4개월분',
       '코스모팜 리포좀 비타민C 비타민D (4개월분)', '가이타이너 자우버 플러스 핸디스팀다리미',
       '[유셀로] 이데베논 페롤릭 부스터 앰플+쇼핑백', '뉴네이처 톡스앤클렌즈 유기농애사비스틱 14포',
       '제주탄산수 탄산오름 250ml 12병(한라봉)', '[동의삼] 홍삼로얄젤리스틱 30포',
       '퍼니트 퓨어 100% NFC 레몬자몽즙 14포', '[요아럽] 내추럴 마일들 선크림 3P 세트',
       '황후지화 리본연 5종세트 [쇼핑백 포함]', '김수미가 추천하는 내열 오븐글라스락 2종',
       '일양약품 비피더스 앤 7종 복합유산균 30포', '삼척맛집', '[코리아나] 로댕 쏘 화이트업 마스크팩 20매',
       '휴대폰약속번호 서비스', '동국헬스케어 힘센 파워코끼리 3000(60포)',
       '서울약사신협 6년근 고려홍삼액진 30포', '광안리 이자카야', '[김오곤] 녹용산삼배양근 활력진 골드스틱 30',
       'K콜라겐3', '나플나플 온수더블 매트 레브 리모컨 보일러 ', '나틴다 콜라겐 수분채움 크림 200ml',
       '삼성제약 내간에밀크씨슬실리마린 60정', '[동의삼] 6년근 홍삼정 골드10g x100포',
       '신형 아이리버 윙클 블루투스 이어폰 블랙', '노쏘리 밀크티 보틀 선물세트 (10포입+보틀)',
       '슬림골드카무트®브랜드밀효소 3g X 30포', '알로하 시어서커 패드 Q',
       '리터네코 동백이 물든 시카 진정토너 300ml', '미각기행 목동 우거지 뼈해장국 1kg x 3팩',
       '기라로쉬 세미마이크로 크림샌드 세트S', '셀트리온 셀린온 바이탈 코드 옴므 스킨케어세트',
       '이뮨멀티비타민 오쏘몰\t', '코오롱제약 숫사슴 녹용 파워 골드 120정',
       '동국 가르시니아 앤씨 딥 슬림라인 42정', '모발 복구팩 아론샵 퍼펙트 헤어앰플 200ml', '헬씨 포캐스트',
       '(유료)스탁매니저 신규가입', '주식정보', '[정답입력] 제주공항 근처 맛집',
       '[100억 유산균] 덱스벡스 피부케어 30캡슐', '[정답입력]한솔주차장제습기-20250726-22',
       '도킹형 보조배터리(lite) C타입_화이트', '코리아나 진화연 골드라벨 7종세트+쇼핑백',
       '내고 계신 보험료 절약하고 홍삼선물 받아가세요.', '다함께차차차 무료체험',
       '아띠코스 24k 골드 앰플 100ml', '[정답입력] 사당역맛집', '리오쿡 실리콘백 8종 세트',
       '[삼성제약] 차전자피식이섬유분말스틱 30포', '숨은 금융포인트 통합조회 이벤트', '[퀴즈] 제주 이모카세',
       'KB다이렉트 자녀보험', '립빠미 올케어세트 [립+멀티밤SET]', '라에스테 멜라샷 퓨어 비타 C22 24g',
       '휴나인 NMN 바이탈 4X 글루타치온', '셰퍼 바디체크 인바디 체중계 블랙', '다양한 카툰 운세를 한번에!',
       '대원제약 링곤베리 글루타치온 900mgx30정', '스퀘어가든 이지포터블 캐리어 24인치 아이보리',
       '[설수련] 진 한방 농축 스킨케어 5종세트', '동원 양반 수라 보양 추어탕 460g x 6개', '해외주식정보',
       '휴나인 애사비', 'US 프로바이오포스콜리500 60캡슐', '[리더스플랜] 오비-엑스 레몬밤 다이어트',
       '립빠미 립앤칙스 멀티밤 15g', '[보령] 진한흑염소 진액스틱 10g x 60포',
       '나틴다 카밍샤벳 올인원 클렌징 밤', '서울약사신협 락토온 WHY Y케어 30포', '[정답입력]쭌곱창',
       '세인트프랑 스킨리페어 트리트먼트 30ml 크림', '영월맛집', '일초픽 핸드크림 세트 (10ml x 5개)',
       '치아건강 인사덴탑 60정(2개월분)', '제주탄산수 탄산오름 250ml 12병(플레인)',
       '이제마선생의 사상체질궁합', '휴대폰분실보호', '자동차보험 상담신청', '토정비결(7일 무료체험)',
       '토마스 풀 커피메이커 1.25L', '[정답입력] 성수동 이자카야', '쇼핑스마일케어', '오늘의집-채움',
       '[도나티] 퓨어이지팩 밀폐용기 혼합 10조세트', '[혈행 기억력 개선] 덱스벡스 혈행케어 30팩',
       '[정답입력]진주혁신도시 충무공동 삼겹살', '[김소형원방] 명품진녹고 10ml x 100포', '나의 커리어 DNA',
       '셰퍼 올플레임 IH 세라믹 궁중팬 28cm', '휴라이프 EMS 바디슬림 복부마사지기',
       '[정답입력]여수횟집-20250808-16', '이순실 카무트 누룽지 500gx3봉 총1.5k', '진주카페',
       '고이담은 골드 카무트 효소', '[정답입력]양덕동 요리주점', '클렌징폼', '[정답입력] 광주 백운동 맛집',
       '[정답입력] 신당동 맛집', '휴라이프 슬림업 바디마사지기 화이트', '피톤치드',
       '닥터로니 하이드라 톤업 크림 50g', '멀티플렉스 영화할인권 무료교환', '골드에스휘트니스 서초점', '스마트사인',
       '키친플래그 다용도 극세사 행주 5종 세트'], dtype=object)

In [ ]:
result = web_info.groupby('mda_idx')['ads_name'].agg(list).reset_index()

In [ ]:
result

,mda_idx,ads_name
0,73,"[라끄시안 올인원 페이셜 로션 150ml, 퍼니트 워너비 알파CD 알파시클로덱스트린14포, 동원 웰로 오트밀 단호박 285g X 6개, 제주탄산수 탄산오름 250ml 12병(레몬), [동원] 야채참치 90g x 8캔, 제주탄산수 탄산오름 250ml 12병(레몬), 연세생활건강 당당컷 다이어트 60정, 라에스떼 셀토닝샷 그래핀 필링 패드, 동국 이너락토 프로바이오틱스VL8 (30캡슐), 코오롱제약 닥터 독일 리놀렌산 송침유VIP, [동원] 양반 귀리쌀죽 400g x 6개, 달콤한 레몬어트 유기농 NFC 레몬즙 14포, 제주탄산수 탄산오름 250ml 12병(감귤), 제주탄산수 탄산오름 250ml 12병(한라봉), 동국헬스케어 힘센 파워코끼리 3000(60포), 라에스떼 셀토닝샷 그래핀 필링 패드, 동국 가르시니아 앤씨 딥 슬림라인 42정, [동원] 리챔 더블라이트 200g X 8캔, 제주탄산수 탄산오름 250ml 12병(혼합), 동원 웰로 오트밀 단호박 285g X 6개, 제주탄산수 탄산오름 250ml 12병(레몬), 치아건강 인사덴탑 60정(2개월분), 미각기행 목동 소내장탕 650g x 3팩]"
1,398,"[국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청]"
2,437,[바바더닷컴_N]
3,480,"[충청남도 X(트위터), 뉴스캐시, 헬스케어, 충청남도 카카오스토리 소식받기, 뉴스캐시, 똑똑보카 룰렛이벤트!, 미세먼지 알리미 직과금, 미노벨 노벨패스 7일 무료체험 이벤트, 굿툰 7일 무료체험, [퀴즈] 여수돌산카페, 스마트 안티피싱 서비스, 안심보호, 범죄알리미 (무료체험), 충청남도 카카오스토리 소식받기, 탑툰, 8월 환급금 평균 960만원(신규 한정), 미툰 7일 무료체험, 충청남도 카카오스토리 소식받기, 미래에셋증권 신규고객 이벤트, 충청남도 카카오스토리 소식받기, USIM스마트인증 서비스, 포춘쿠키 (1일 1회 재참여 가능), 게임믹(7일 무료체험), H.point 회원가입, 탑툰, 미노벨 노벨패스 7일 무료체험 이벤트, 전화번호 안심로그인 , 충청남도 페이스북, 로보주식플러스, 굿툰 7일 무료체험, 운세 보면 리워드+네이버페이 지급, G마켓 4만원 이상 구매하기 , [동원] 루피는 참치마요 100g x 10캔, 굿툰 7일 무료체험, 충청남도 페이스북, 신한 SOL페이 퀴즈팡팡 퀴즈 풀면, 운세 보면 리워드+네이버페이 지급, 운세 보면 리워드+네이버페이 지급, 헬스케어, 탑운세 7일 무료체험, 똑똑보카 룰렛이벤트!, G마켓 2만원 이상 구매하기 , 충청남도 페이스북, 포춘쿠키 (1일 1회 재참여 가능), 탑툰, 체크플러스, 뉴스캐시, 비상교육 온리원(30세~58세 여성), 포춘쿠키 (1일 1회 재참여 가능), 8월 환급금 평균 960만원(신규 한정), 휴대폰약속번호 서비스, 탑운세 7일 무료체험, 헬스케어, 똑똑보카 룰렛이벤트!, 미툰 코인 구매 (5천원 이상), 충청남도 페이스북, (유료)스탁매니저 신규가입, USIM스마트인증 서비스, 미툰 7일 무료체험, 굿툰 7일 무료체험, 주식정보, 체크플러스, 내고 계신 보험료 절약하고 홍삼선물 받아가세요., 다함께차차차 무료체험, 신한라이프 마케팅동의 이벤트, 충청남도 카카오스토리 소식받기, 운세 보면 리워드+네이버페이 지급, 숨은 금융포인트 통합조회 이벤트, 충청남도 카카오스토리 소식받기, 포크너 부천점, 다양한 카툰 운세를 한번에!, 운세 보면 리워드+네이버페이 지급, 뉴스캐시, 충청남도 X(트위터), 굿툰 7일 무료체험, 굿툰 7일 무료체험, AT스탁플러스, 헬스케어, 뉴스캐시, 탑운세 7일 무료체험, MyOTP, 휴대폰분실보호, 뉴스캐시, 자동차보험 상담신청, 미툰 코인 구매 (5천원 이상), 신한 SOL페이 퀴즈팡팡 퀴즈 풀면, 충청남도 X(트위터), 똑똑보카 룰렛이벤트!, 미툰 7일 무료체험, 쇼핑스마일케어, 나의 커리어 DNA, 미세먼지 알리미 직과금, 국가통합바이오빅데이터구축사업 참여 사전신청, 신한 SOL페이 퀴즈팡팡 퀴즈 풀면, 배곧맛집, 굿툰 7일 무료체험, H.point 회원가입, 스마트사인, 주식정보]"
4,481,"[닭갈비, 배곧맛집, MyOTP, 운세 보면 리워드+네이버페이 지급, 거미입니다만, 문제라도?, 쭈꾸미, 쭈꾸미, 책상 스탠드, 아론샵 원스텝 스트레이트 펌 매직약 150ml, AT스탁플러스, 뉴스캐시, 백년 약방 코뻥 코힐밤, 광안리 이자카야, 굿툰 7일 무료체험, 전화번호 안심로그인 , 포춘텔러 무료체험, 다함께차차차 무료체험, 뉴스캐시, [퀴즈] 제주 이모카세, 쭈꾸미, 뉴스캐시, 닭갈비, 토정비결(7일 무료체험), 굿툰 7일 무료체험, 배곧맛집, 진주카페, 범죄알리미 (무료체험), H.point 회원가입]"
5,539,"[충청남도 카카오스토리 소식받기, 충청남도 카카오스토리 소식받기]"
6,540,"[H.point 회원가입, 충청남도 X(트위터), 충청남도 X(트위터), H.point 회원가입, 충청남도 카카오스토리 소식받기, H.point 회원가입, 충청남도 카카오스토리 소식받기, 충청남도 X(트위터), 충청남도 카카오스토리 소식받기, 충청남도 카카오스토리 소식받기, H.point 회원가입, H.point 회원가입, 충청남도 카카오스토리 소식받기, 충청남도 카카오스토리 소식받기, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, 충청남도 카카오스토리 소식받기, 국가통합바이오빅데이터구축사업 참여 사전신청, 충청남도 카카오스토리 소식받기, H.point 회원가입, H.point 회원가입, 충청남도 카카오스토리 소식받기, H.point 회원가입, 충청남도 카카오스토리 소식받기, 충청남도 카카오스토리 소식받기, 충청남도 카카오스토리 소식받기, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, 충청남도 카카오스토리 소식받기, H.point 회원가입, H.point 회원가입, H.point 회원가입, 충청남도 카카오스토리 소식받기, 국가통합바이오빅데이터구축사업 참여 사전신청, 충청남도 카카오스토리 소식받기, H.point 회원가입, H.point 회원가입, H.point 회원가입]"
7,583,"[H.point 회원가입, H.point 회원가입, H.point 회원가입, KB다이렉트 자동차보험, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입, H.point 회원가입]"
8,654,"[국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 로보주식플러스, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 로보주식플러스, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 로보주식플러스, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 로보주식플러스, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 국가통합바이오빅데이터구축사업 참여 사전신청, 굿툰 7일 무료체험, 굿툰 7일 무료체험, 로보주식플러스, 굿툰 7일 무료체험, 로보주식플러스, 굿툰 7일 무료체험, ...]"
9,710,"[똑똑보카 룰렛이벤트!, H.point 회원가입, 뉴스캐시]"
10,714,"[류현진 데이렉스 엑소좀겔 마사지 크림 50g, [쎄븐업플러스]철갑상어 건강즙 70ml 30포, 짐스낵 다이어트 간식 프로틴 단백질 쿠키 과자, [동원] 리챔 더블라이트 200g X 8캔, 면세점입점 나틴다 승무원팩트 실키커버 21호, [록키스] 아쿠아 부스트 옴므 올인원 2개, 굿매너 뽑아쓰는 키친타올 3겹(100매×9팩), 원데이즈유 콜라겐 하이드로겔 아이패치 60매, 오스틴제약 비타 이뮨 플래티넘 골드 15병, [뉴바이오]덴타골드치약 200gx2개 세트, 매드라운드 에고이즘 오드퍼퓸 30ml, 아론샵 홀드맥스 헤어젤 120ml, 맛다움 해물짬뽕 450g, 퍼니트 하루하나 유기농 레자몽 14포, 날엔퍼퓸 날엔세트 (코튼+우드 SET), 스퀘어가든 퓨어 네이비 빨래바구니, 뉴네이처 알티지오메가3파워 1400 60캡슐, 토마스 풀 전기 드립포트 1.2L , 코오롱 쎈류신에너지파워 1,000mg 120정, 스치듯 포레스트 고체향수 15g, 뷰티앤소프트 화장지 (30m x 30롤), 굿매너 피톤치드 화장지 (30m x 30롤), 화곡원 국산 하루힘차(흰민들레+대추) 30티백, [동원] 리챔 더블라이트 200g X 8캔, 아론샵 원스텝 스트레이트 펌 매직약 150ml, 퍼니트 하루하나 유기농 레자몽 14포, 스치듯 포레스트 고체향수 15g, 뷰티앤소프트 화장지 (30m x 30롤), 키친플래그 오일 스프레이 4종 세트, 나틴다 알로에베라 딥 클렌징폼 130ml, 2+1 한돈 간장 돼지불고기 800g+400g, 스템샷 안티 헤어로스 세럼(탈모방지헤어에센스), 햄튼 네오블 마블코팅 후라이팬 24CM, 스퀘어가든 퓨어 네이비 빨래바구니, 날엔퍼퓸 날엔세트 (코튼+우드 SET), 코오롱제약 닥터 독일 리놀렌산 송침유VIP, 맛다움 프리미엄 짜장 350g, [독일 제너] 실리콘 우드 키친툴 8종 세트, 엑소머 더 넥스트 셀 부스팅 니들 톡스 볼륨샷, 2+1 간장 양념소불고기 800g+400g, 화곡원 여주해죽순돼지감자차 30티백, [수앤리빙]마뜨앙 여행용 기내형캐리어 20인치, 이프티 모로실 다이어트 모로오렌지 15포, 제주탄산수 탄산오름 250ml 12병(혼합), 화곡원 여주해죽순돼지감자차 30티백, [삼성] 체인미 산양유단백콜라겐유산균, 키친플래그 오일 스프레이 4종 세트, 스퀘어가든 퓨어 네이비 빨래바구니, 미각기행 목전지 수제 돼지양념구이 400g, 엘루자이 포맨 페로몬 향수 50ml, 엘루자이 포맨 페로몬 향수 50ml, 스위스 몽크로스 프라젠 BBQ 전기그릴, 짐스낵 다이어트 간식 프로틴 단백질 쿠키 과자, 독일 코겔 원터치 진공 쌀통 바로락 5kg, [이엔비]유기농 레몬즙 20g X 14포, 굿매너 롱앤소프트 화장지 (40m x 30롤), 라에스떼 셀워터샷 샤인 미스트, [청담 헤어샵] 아론샵 실크 리페어 샴푸 1L, 유유제약 마시는 관절건강 MSM 30포, 짐스낵 다이어트 간식 프로틴 단백질 쿠키 과자, 청담 아론샵 실크 리페어 트리트먼트 1L, [동원] 리챔 더블라이트 200g X 8캔, 매드라운드 카타르시즘 오드퍼퓸 30ml, 백년약방 염색 가인(천연 염색제) /내츄럴블랙, 화곡원 여주해죽순돼지감자차 30티백, 미각기행 목동 곤이알찜 550g x 2팩, 셰퍼 글라스 에어 프라이어 JSK-N3005, [동원] 리챔 더블라이트 200g X 8캔, 스치듯 포레스트 고체향수 15g, 유유제약 마시는 관절건강 MSM 30포, [수앤리빙] 마호가니 사각도마, 청담 아론샵 실크 홀드 스프레이 120ml, 화곡원 여주해죽순돼지감자차 30티백, 토마스 풀 패밀리 3in1 멀티 와이드 그릴, 짐스낵 다이어트 간식 프로틴 단백질 쿠키 과자, [가이타이너] 자우버 프로 보풀제거기, 햄튼 네오블 마블코팅 후라이팬 24CM, 아이나비 힙합독 방향제 ICD-H3+아로마오일, 더화이트 대용량 화장지 (27m x 36롤), 짐스낵 다이어트 간식 프로틴 단백질 쿠키 과자, 황후지화 24K 골드 프레스티지 리페어 7종, 스위스 몽크로스 프라젠 BBQ 전기그릴, 김소형 보감탕 30포 [쇼핑백포함], 순수달 1종 주방세제 4L x 2개, 햄튼 네오블 마블코팅 후라이팬 24CM, [록키스] 아쿠아 부스트 옴므 올인원 2개, [씨피큐 메가라이프] 기억력개선 120캡슐 특가, [수앤리빙]마뜨앙 여행용 기내형캐리어 20인치, 토마스 풀 3D 백허그 목/어깨 안마기, 키친플래그 스테인레스304 냄비 3종 세트, US 스킨아우라히알루론비타 60캡슐, 송정골 언양식 바싹불고기 한판 180g*3봉, [마이픽] 캠핑 웨건 (검정), 나틴다 콜라겐 수분채움 미스트 100ml, 코오롱제약 쎈 유단백 추출물 콘드로이친N플러스, 미각기행 목전지 수제 돼지양념구이 400g, 토마스 풀 3D 백허그 목/어깨 안마기, 뷰티앤소프트 화장지 (30m x 30롤), 나틴다 아우라 퍼펙트 커버 쿠션 21호, 셰퍼 에디번 전기 그릴 JSK-N4005, ...]"
11,755,"[고잔갈비 안산본점, 평거동 맛집, [퀴즈] 여행용 프리볼트 고데기, 포크너 부천점, 진주 맛집, 진주고깃집, 책상 스탠드, 포크너 부천점, 초전동 맛집]"
12,769,"[로보주식플러스, KB다이렉트 운전자보험, KB다이렉트 자동차보험 가입, 바로로그인 가입 이벤트, KB다이렉트 운전자보험, 돈버는 운 - 부자되는 운, 굿툰 7일 무료체험, 신한라이프 마케팅동의 이벤트, T올케어 보험 가입, 평생총운 가입 이벤트, 굿툰 7일 무료체험, KB다이렉트 자녀보험, 해외주식정보, 이제마선생의 사상체질궁합, KB다이렉트 자동차보험 가입, KB다이렉트 운전자보험, 신한 SOL페이 퀴즈팡팡 퀴즈 풀면, KB다이렉트 자동차보험 가입]"
13,787,"[마법선생 네기마!, 웰로 고향사랑기부, 충청남도 카카오스토리 소식받기, 마법선생 네기마!, 마법선생 네기마!, 마법선생 네기마!, 헬스케어, 제주탄산수 탄산오름 250ml 12병(감귤), 휴나인 매스틱 검 1000 스톰큐, 마법선생 네기마!, H.point 회원가입, 헬스케어, 마법선생 네기마!, 띠운세 (1일 1회 재참여 가능), 마법선생 네기마!, 마법선생 네기마!, 띠운세 (1일 1회 재참여 가능), 마법선생 네기마!, 띠운세 (1일 1회 재참여 가능), 띠운세 (1일 1회 재참여 가능), 미툰 코인 구매 (5천원 이상), 미툰 코인 구매 (5천원 이상), 마법선생 네기마!, 띠운세 (1일 1회 재참여 가능), 미툰 코인 구매 (5천원 이상), 제주탄산수 탄산오름 250ml 12병(플레인), 마법선생 네기마!, 미각기행 목전지 수제 돼지양념구이 400g, 띠운세 (1일 1회 재참여 가능), 제주탄산수 탄산오름 250ml 12병(플레인), 마법선생 네기마!, 마법선생 네기마!, 마법선생 네기마!, 마법선생 네기마!, 골드에스휘트니스 서초점]"
14,978,"[[정답입력] 올림픽공원 맛집, 초전동 맛집, 뉴스캐시, [정답입력] 부산요트투어, [정답입력]포항시 북구 영일대 요리주점, 신차장기렌트카, 웰로 고향사랑기부, 보안플러스 무료체험, 신한 SOL페이 퀴즈팡팡 퀴즈 풀면, [정답입력]법무법인대륜울산분사무소-20250725-191, 올레시장 맛집, 수성구 치과, [정답입력]울산 한우 떡갈비, [정답입력] 신논현 맛집, 포춘텔러 무료체험, 미노벨 노벨패스 7일 무료체험 이벤트, [정답입력]서면 치킨스테이크, [퀴즈] 동래역 랍스타, 굿툰 7일 무료체험, [퀴즈] 굴포천역 헬스장, [정답입력] 이유식, 대추차, [정답입력] 동래 랍스터 맛집, 대추차, [정답입력] 애월 맛집, 굿툰 7일 무료체험, 굿툰 7일 무료체험, [정답입력]웨딩액자-20250729-88, [정답입력] 부산요트투어, [저장하기]거제 구조라리 유람선 추천, [정답입력]포천 소흘읍 소불고기, [정답입력] 부산요트투어, 똑똑보카 룰렛이벤트!, 8월 환급금 평균 960만원(신규 한정), [정답입력]연남동 카페, [정답입력] 신논현 맛집, 삼척맛집, K콜라겐3, 굿툰 7일 무료체험, 미노벨 노벨패스 7일 무료체험 이벤트, 이뮨멀티비타민 오쏘몰\t, 헬씨 포캐스트, [정답입력] 제주공항 근처 맛집, [정답입력]한솔주차장제습기-20250726-22, [정답입력] 사당역맛집, 다함께차차차 무료체험, 똑똑보카 룰렛이벤트!, 휴나인 NMN 바이탈 4X 글루타치온, 휴나인 애사비, 똑똑보카 룰렛이벤트!, 수성구 치과, [정답입력]쭌곱창, 영월맛집, K콜라겐3, G마켓 4만원 이상 구매하기 , 대추차, 삼척맛집, 내고 계신 보험료 절약하고 홍삼선물 받아가세요., [정답입력] 성수동 이자카야, 오늘의집-채움, [정답입력]진주혁신도시 충무공동 삼겹살, [정답입력]연남동 카페, [정답입력]여수횟집-20250808-16, 휴나인 애사비, [정답입력] 신논현 맛집, [정답입력]양덕동 요리주점, 클렌징폼, [정답입력] 광주 백운동 맛집, [정답입력] 신당동 맛집, 피톤치드, 멀티플렉스 영화할인권 무료교환]"
15,980,"[[블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, 실버 등급 패키지, 실버 등급 패키지, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, KWDA 가챠이벤트 1만 투표권, [일반] 10만 투표권 + 1만 보너스, [일반] 30만 투표권 + 4만 보너스, [일반] 5만 투표권, 실버 등급 패키지, [일반] 1만 투표권, [일반] 1만 투표권, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 30만 투표권 + 4만 보너스, 블랙 등급 패키지, [일반] 1만 투표권, [일반] 10만 투표권 + 1만 보너스, 실버 등급 패키지, [일반] 30만 투표권 + 4만 보너스, 블랙 등급 패키지, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 30만 투표권 + 4만 보너스, [일반] 1만 투표권, [일반] 1만 투표권, [일반] 1만 투표권, 골드 등급 패키지, [일반] 10만 투표권 + 1만 보너스, [일반] 10만 투표권 + 1만 보너스, [실버] 5만 투표권 + 500 등급 보너스, [일반] 1만 투표권, [일반] 1만 투표권, [일반] 1만 투표권, 실버 등급 패키지, 골드 등급 패키지, [일반] 1만 투표권, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 5만 투표권, 블랙 등급 패키지, [일반] 10만 투표권 + 1만 보너스, [일반] 1만 투표권, [일반] 5만 투표권, [일반] 1만 투표권, [일반] 1만 투표권, [골드] 30만 투표권 + 4만 보너스 + 6,000 등급 보너스, 실버 등급 패키지, [일반] 1만 투표권, 블랙 등급 패키지, 실버 등급 패키지, [일반] 1만 투표권, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, 골드 등급 패키지, [일반] 1만 투표권, [일반] 1만 투표권, KWDA 가챠이벤트 1만 투표권, 실버 등급 패키지, 실버 등급 패키지, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, 골드 등급 패키지, [블랙] 5만 투표권 + 1,500 등급 보너스, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 1만 투표권, [일반] 10만 투표권 + 1만 보너스, [일반] 1만 투표권, [일반] 30만 투표권 + 4만 보너스, 블랙 등급 패키지, [일반] 30만 투표권 + 4만 보너스, [일반] 5만 투표권, 블랙 등급 패키지, KWDA 가챠이벤트 1만 투표권, [실버] 10만 투표권 + 1만 보너스 + 1,000 등급 보너스, 실버 등급 패키지, 실버 등급 패키지, 블랙 등급 패키지, [일반] 1만 투표권, [실버] 1만 투표권 + 100 등급 보너스, 골드 등급 패키지, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 30만 투표권 + 4만 보너스, [일반] 1만 투표권, [일반] 5만 투표권, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 5만 투표권, [일반] 1만 투표권, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [일반] 10만 투표권 + 1만 보너스, [일반] 1만 투표권, [블랙] 30만 투표권 + 4만 보너스 + 9,000 등급 보너스, [블랙] 10만 투표권 + 1만 보너스 + 3,000 등급 보너스, [일반] 1만 투표권, [일반] 10만 투표권 + 1만 보너스, [일반] 1만 투표권, 실버 등급 패키지, 실버 등급 패키지, [실버] 30만 투표권 + 4만 보너스 + 3,000 등급 보너스, 골드 등급 패키지, [일반] 10만 투표권 + 1만 보너스, [일반] 5만 투표권, [일반] 10만 투표권 + 1만 보너스, [일반] 5만 투표권, [일반] 5만 투표권, ...]"
16,1023,[제주탄산수 탄산오름 250ml 12병(혼합)]
17,1042,"[주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스, 주식투자 정보서비스]"
18,1049,"[마법선생 네기마!, 메디트리 순 유기농 레몬즙 50포]"
19,1050,[운세 보면 리워드+네이버페이 지급]
20,1055,"[[테스트] [블랙] 10만 투표권 + 1만 보너스 + 3,000 등급 보너스, [테스트] [블랙] 5만 투표권 + 1,500 등급 보너스, [테스트] [블랙] 5만 투표권 + 1,500 등급 보너스]"

In [ ]:
rewards[rewards['dvc_idx']==0]['mda_idx'].unique()

array([ 980,  714,  654,  978,  480,  539,  540, 1050,  481,  787])

In [ ]:
web_info[web_info['mda_idx']==978]

,click_key,ads_idx,dvc_idx,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,ads_summary,ads_guide,ads_limit,ads_payment,ads_save_way,ads_day_cap,ads_sdate,ads_edate,ads_package,ads_sex_type,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
748,04752be1e262ed13c2bfad75d6089d3a4deec2ea,443482,0,978,1,18,12,2025-08-11,18,2025-08-11 18:42:24,2025-09-10,NaN,44.203.230.216,vL5QuMn20O,82,1596,1217239,3,4,[정답입력] 올림픽공원 맛집,"[정답입력] 올림픽공원 맛집,3B3vRfDI7A",https://cdn.quizclick.io/quiz/public/campaign/images/3-thumbImage_s.png,[참여 방법] \n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동 \n2. 이벤트 페이지 상세 설명 확인하여 참여 \n\n[유의사항]\n- 최초 참여자 대상입니다.\n- 7일 이내 참여해야 포인트가 지급됩니다.\n- 포인트 지급까지 최대 10분까지도 소요될 수 있습니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,네이버 플레이스 리뷰찾기,N,2025-08-11 18:41:55,9999-12-31 23:59:59,NaN,NaN,0,100,7,18,12,1369936,ADS_CODE_DAILY_UPDATE,Y,2025-08-11 18:41:55,N
1250,078c08b8d7e9b743d74b3d4b81ea3a439843157f,438971,0,978,1,20,14,2025-07-31,14,2025-07-31 14:41:20,2025-08-30,NaN,35.175.137.165,F3BLXdKy5d,84,1623,1207949,3,4,초전동 맛집,"초전동 맛집,11764",https://adwize.co.kr/common_img/reward/GNPS_ICON.jpg,[참여방법]\n- 미션 참여 방법을 꼭 확인하신 후 참여해 주세요.\n- 제공되는 가이드를 참고하시면 쉽게 정답을 찾을 수 있습니다.\n\n[주의사항]\n- 장소 또는 상품 페이지에 30초 이상 머물러 주세요.\n- 광고로 표시된 상품은 클릭하지 마세요.\n- 저장 미션 완료 후 저장을 취소하면 포인트 지급이 취소됩니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.\n- 부정 참여 적발시 모든 미션의 참여가 제한됩니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,플레이스 저장,N,2025-07-31 14:37:44,9999-12-31 23:59:59,NaN,NaN,0,100,7,20,14,1369719,NONE,N,2025-07-31 14:37:44,N
1279,07bd20cd0e5edff06636d8c1083c38c40ef8d066,355220,0,978,1,500,400,2025-08-09,1,2025-08-09 01:06:48,2025-09-08,NaN,3.84.146.87,wxkYFmuFCL,13,335,1066659,3,8,뉴스캐시,"뉴스캐시,341016",https://seimg.pincrux.com/icon/1745395246.png,"- 뉴스캐시 앱 경험 후 신규 회원가입 완료 시 리워드가 지급됩니다.\n- 앱 최초 경험, 최초 회원가입이 아닐 경우 리워드는 지급되지 않습니다.\n- 이벤트 페이지 내 입력한 전화번호와 회원가입 시 입력한 전화번호가 동일해야 리워드가 지급됩니다.",참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,회원가입,N,2025-04-23 18:00:00,2029-11-29 00:00:00,NaN,NaN,0,100,7,500,400,2544100,NONE,N,2025-04-23 18:02:34,N
2133,0cd45eb88da49cb0c53e30a609ebadecdd65a2ee,440592,0,978,1,15,10,2025-08-05,13,2025-08-05 13:04:38,2025-09-04,NaN,3.235.67.94,QMGBZ4XTJF,84,1623,1211270,3,4,[정답입력] 부산요트투어,"[정답입력] 부산요트투어,11894",https://adwize.co.kr/common_img/reward/GNSQ_ICON.jpg,[참여방법]\n- 미션 참여 방법을 꼭 확인하신 후 참여해 주세요.\n- 제공되는 가이드를 참고하시면 쉽게 정답을 찾을 수 있습니다.\n\n[주의사항]\n- 장소 또는 상품 페이지에 30초 이상 머물러 주세요.\n- 광고로 표시된 상품은 클릭하지 마세요.\n- 저장 미션 완료 후 저장을 취소하면 포인트 지급이 취소됩니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.\n- 부정 참여 적발시 모든 미션의 참여가 제한됩니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,퀴즈 맞추기,N,2025-08-05 11:08:24,9999-12-31 23:59:59,NaN,NaN,0,100,7,15,10,1369937,NONE,N,2025-08-05 11:08:24,N
4013,17c2212ed798e1576eb90bb710055af6bc2c4123,439258,0,978,1,18,12,2025-08-01,3,2025-08-01 03:52:50,2025-08-31,NaN,54.80.101.188,lDtDin6kNo,82,1596,1208488,3,4,[정답입력]포항시 북구 영일대 요리주점,"[정답입력]포항시 북구 영일대 요리주점,xIxvWVgOgm",https://cdn.quizclick.io/quiz/public/campaign/images/3-thumbImage_s.png,[참여 방법] \n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동 \n2. 이벤트 페이지 상세 설명 확인하여 참여 \n\n[유의사항]\n- 최초 참여자 대상입니다.\n- 7일 이내 참여해야 포인트가 지급됩니다.\n- 포인트 지급까지 최대 10분까지도 소요될 수 있습니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,네이버 플레이스 지도 거리 입력하기,N,2025-08-01 02:37:13,9999-12-31 23:59:59,NaN,NaN,0,100,7,18,12,1369722,ADS_CODE_DAILY_UPDATE,Y,2025-08-01 02:37:13,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41134,f33342a255d50a775c0e511dff7548b1756b2051,439462,0,978,1,15,10,2025-08-02,5,2025-08-02 05:16:38,2025-09-01,NaN,3.88.63.63,dvgEj7AugY,84,1623,1208876,3,4,클렌징폼,"클렌징폼,11835",https://adwize.co.kr/common_img/reward/GNSQ_ICON.jpg,[참여방법]\n- 미션 참여 방법을 꼭 확인하신 후 참여해 주세요.\n- 제공되는 가이드를 참고하시면 쉽게 정답을 찾을 수 있습니다.\n\n[주의사항]\n- 장소 또는 상품 페이지에 30초 이상 머물러 주세요.\n- 광고로 표시된 상품은 클릭하지 마세요.\n- 저장 미션 완료 후 저장을 취소하면 포인트 지급이 취소됩니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.\n- 부정 참여 적발시 모든 미션의 참여가 제한됩니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,퀴즈 맞추기,N,2025-08-01 14:42:23,9999-12-31 23:59:59,NaN,NaN,0,100,7,15,10,1369827,NONE,N,2025-08-01 14:42:23,N
41233,f3abac6956ce6719cbd629242eb49fa5b5d9503d,440517,0,978,1,18,12,2025-08-05,12,2025-08-05 12:56:06,2025-09-04,NaN,44.213.62.77,xIGFWGhFk8,82,1596,1211111,3,4,[정답입력] 광주 백운동 맛집,"[정답입력] 광주 백운동 맛집,pHLXwGBoiH",https://cdn.quizclick.io/quiz/public/campaign/images/3-thumbImage_s.png,[참여 방법] \n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동 \n2. 이벤트 페이지 상세 설명 확인하여 참여 \n\n[유의사항]\n- 최초 참여자 대상입니다.\n- 7일 이내 참여해야 포인트가 지급됩니다.\n- 포인트 지급까지 최대 10분까지도 소요될 수 있습니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,네이버 플레이스 리뷰찾기,N,2025-08-05 07:22:22,9999-12-31 23:59:59,NaN,NaN,0,100,7,18,12,1369937,ADS_CODE_DAILY_UPDATE,Y,2025-08-05 07:22:22,N
41419,f4cd76bfc85bda421b06dc8bedf6a141affa7c80,439256,0,978,1,18,12,2025-08-01,9,2025-08-01 09:38:22,2025-08-31,NaN,3.236.184.247,ojfIHeyBzV,82,1596,1208484,3,4,[정답입력] 신당동 맛집,"[정답입력] 신당동 맛집,2mGio8eXaT",https://cdn.quizclick.io/quiz/public/campaign/images/3-thumbImage_s.png,[참여 방법] \n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동 \n2. 이벤트 페이지 상세 설명 확인하여 참여 \n\n[유의사항]\n- 최초 참여자 대상입니다.\n- 7일 이내 참여해야 포인트가 지급됩니다.\n- 포인트 지급까지 최대 10분까지도 소요될 수 있습니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,네이버 플레이스 지도 거리 입력하기,N,2025-08-01 01:47:34,9999-12-31 23:59:59,NaN,NaN,0,100,7,18,12,1369722,ADS_CODE_DAILY_UPDATE,Y,2025-08-01 01:47:34,N
41974,f801f538f3422ec42c8891658495595a7c2a6369,437744,0,978,1,15,10,2025-07-28,15,2025-07-28 15:20:49,2025-08-27,NaN,98.80.186.185,ft8Jx5nOLK,84,1623,1205575,3,4,피톤치드,"피톤치드,11630",https://adwize.co.kr/common_img/reward/GNSQ_ICON.jpg,[참여방법]\n- 미션 참여 방법을 꼭 확인하신 후 참여해 주세요.\n- 제공되는 가이드를 참고하시면 쉽게 정답을 찾을 수 있습니다.\n\n[주의사항]\n- 장소 또는 상품 페이지에 30초 이상 머물러 주세요.\n- 광고로 표시된 상품은 클릭하지 마세요.\n- 저장 미션 완료 후 저장을 취소하면 포인트 지급이 취소됩니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.\n- 부정 참여 적발시 모든 미션의 참여가 제한됩니다.,참여 완료시점까지 완료 후 리워드 지급까지는 최대 1시간 가량 지연 될 수 있습니다.\n이미 다른 방법으로 참여한 이력이 있는 사용자는 지급 대상에서 제외됩니다.\n본 광고는 사전 공지 없이 내용이 변경 되거나 조기 종료될 수 있습니다.,NaN,NaN,퀴즈 맞추기,N,2025-07-28 15:17:40,9999-12-31 23:59:59,NaN,NaN,0,100,7,15,10,1369722,NONE,N,2025-07-28 15:17:40,N
42306,f9dc1539eeb05b9fcf977bd2290d3e31f4275f0e,17056,0,978,1,1500,1120,2025-07-31,15,2025-07-31 15:11:46,2025-08-30,NaN,13.218.191.247,9hRCH8rhtX,23,220,65336,3,8,멀티플렉스 영화할인권 무료교환,"멀티플렉스 영화할인권 무료교환,multiplex2",https://i.imgur.com/EEsvEd8.png,"전국 CGV, 롯데시네마, 메가박스 영화할인권 무료 교환\n카드사 포인트로 영화할인권 교환을 완료해주세요.\n\n[참여 방법]\n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동\n2. 이벤트 페이지 상세 설명 확인하여 참여\n3. 내포인트 조회하기 > 카드사 포인트 조회 > 카드사 포인트로 영화할인권 교환\n\n[유의사항]\n- 최초 참여자 대상입니다.\n- 7일 이내 참여해야 포인트가 지급됩니다. \n- 포인트 지급까지 최대 10분까지도 소요될 수 있습니다.\n- WIFI가 아닌 환경에서는 데이터 이용료가 발생할 수 있습니다.",NaN,NaN,NaN,영화할인권 무료교환,N,2022-05-11 16:00:00,2031-01-01 00:00:00,NaN,NaN,0,100,7,1500,1120,2342600,NONE,N,2022-05-11 16:52:39,N

# Edate 000000

In [ ]:
pd.reset_option('display.max_columns')
pd.reset_option('display.width')
pd.reset_option('display.max_colwidth')

In [ ]:
# drop dylen == y
# sdate 0000 edate 0000

In [ ]:
delyn = ads[ads['delyn']!='Y']

In [ ]:
edatezero = delyn[delyn['ads_edate']=='0000-00-00 00:00:00']

In [ ]:
df = edatezero.merge(participate, on='ads_idx', how='left')

In [ ]:
edatezero

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
67,1306,lLU3dyqi3P,15,62,0,2,1,파이널 드래곤 나이츠 실행형_aos,"파이널 드래곤 나이츠 실행형_aos,com.enjoygame.xlzjhg,1111",https://lh3.googleusercontent.com/KybE5bKufVNQ...,...,0,100,2,260,210,933000,NONE,Y,2017-04-06 14:13:53,N
81,1341,rOAourUQgw,1,109,0,3,2,프로야구 H2 사전예약,"프로야구 H2 사전예약,,",https://lh3.googleusercontent.com/NW3yM9glVbFq...,...,0,100,7,1500,1200,659100,NONE,Y,2017-03-24 10:29:58,N
123,1448,oaHWT18w24,30,80,0,2,1,여명 for kakao,"여명 for kakao,com.kakaogames.lmzgplay,1150528",https://cdn-ad-static.buzzvil.com/uploads/1489...,...,0,100,2,200,180,933400,NONE,Y,2017-05-11 13:10:24,N
124,1450,bY9l99IGOw,30,80,0,1,1,몬스터,"몬스터,com.gamepub.cl.g,1303240",https://d3aulf22blzf9p.cloudfront.net/uploads/...,...,0,100,2,160,150,996800,NONE,Y,2017-05-11 13:13:47,N
125,1452,5GgMwttXai,30,80,0,2,1,다음-Daum,"다음-Daum,net.daum.android.daum,608143",https://buzzvil.akamaized.net/adfit.image/uplo...,...,0,100,2,200,180,933500,NONE,Y,2017-05-11 13:33:33,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370994,372653,KfzMhzCv4W,1,557,0,2,2,삼국지 올스타,"삼국지 올스타,com.highbrow.games.dve",https://i.imgur.com/a2hE0UL.jpeg,...,0,100,1,280,180,2748100,NONE,Y,2025-05-30 13:10:07,N
410717,412376,gL1vFwGwZR,1,1660,0,3,8,나두기업몰,나두기업몰,https://i.imgur.com/grRbX8G.jpeg,...,0,100,2,1200,800,2752600,NONE,Y,2025-07-02 13:34:23,N
438476,440135,MEnre3naZI,1,1662,0,2,1,보스포커,"보스포커,1142939438",https://i.imgur.com/V9xckPU.png,...,0,100,1,280,180,2756700,NONE,Y,2025-08-04 17:46:45,N
442294,443953,HiAARvqMP1,1,1670,0,2,1,신트노트,신트노트,https://i.imgur.com/AYHFLoW.png,...,0,100,2,10,10,2761400,NONE,Y,2025-08-13 12:43:15,N
442588,444247,dkAdH8Eh8H,57,84,0,3,8,[답글] 대용량 토너! 미친 수분력! 72% 할인 깊다 깊어!ㅣ할인광36 [EN]_2,[답글] 대용량 토너! 미친 수분력! 72% 할인 깊다 깊어!ㅣ할인광36 [EN]_...,https://lh3.googleusercontent.com/lMoItBgdPPVD...,...,0,100,7,200,150,2731100,NONE,Y,2025-08-14 11:32:57,N

In [ ]:
ads[ads['ads_name'] == '프로야구 H2 사전예약']

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,ads_require_adid,regdate,delyn
81,1341,rOAourUQgw,1,109,0,3,2,프로야구 H2 사전예약,"프로야구 H2 사전예약,,",https://lh3.googleusercontent.com/NW3yM9glVbFq...,...,0,100,7,1500,1200,659100,NONE,Y,2017-03-24 10:29:58,N

In [ ]:
df['ads_idx'].nunique()

227

In [ ]:
df

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip
0,1306,lLU3dyqi3P,15,62,0,2,1,파이널 드래곤 나이츠 실행형_aos,"파이널 드래곤 나이츠 실행형_aos,com.enjoygame.xlzjhg,1111",https://lh3.googleusercontent.com/KybE5bKufVNQ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1341,rOAourUQgw,1,109,0,3,2,프로야구 H2 사전예약,"프로야구 H2 사전예약,,",https://lh3.googleusercontent.com/NW3yM9glVbFq...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1448,oaHWT18w24,30,80,0,2,1,여명 for kakao,"여명 for kakao,com.kakaogames.lmzgplay,1150528",https://cdn-ad-static.buzzvil.com/uploads/1489...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1450,bY9l99IGOw,30,80,0,1,1,몬스터,"몬스터,com.gamepub.cl.g,1303240",https://d3aulf22blzf9p.cloudfront.net/uploads/...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1452,5GgMwttXai,30,80,0,2,1,다음-Daum,"다음-Daum,net.daum.android.daum,608143",https://buzzvil.akamaized.net/adfit.image/uplo...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,372653,KfzMhzCv4W,1,557,0,2,2,삼국지 올스타,"삼국지 올스타,com.highbrow.games.dve",https://i.imgur.com/a2hE0UL.jpeg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,412376,gL1vFwGwZR,1,1660,0,3,8,나두기업몰,나두기업몰,https://i.imgur.com/grRbX8G.jpeg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,440135,MEnre3naZI,1,1662,0,2,1,보스포커,"보스포커,1142939438",https://i.imgur.com/V9xckPU.png,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,443953,HiAARvqMP1,1,1670,0,2,1,신트노트,신트노트,https://i.imgur.com/AYHFLoW.png,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,444247,dkAdH8Eh8H,57,84,0,3,8,[답글] 대용량 토너! 미친 수분력! 72% 할인 깊다 깊어!ㅣ할인광36 [EN]_2,[답글] 대용량 토너! 미친 수분력! 72% 할인 깊다 깊어!ㅣ할인광36 [EN]_...,https://lh3.googleusercontent.com/lMoItBgdPPVD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[df['mda_idx'].notna()]

,ads_idx,ads_code,aff_idx,adv_idx,sch_idx,ads_type,ads_category,ads_name,ads_search,ads_icon_img,...,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip
201,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,337.000000,1.000000,4224.000000,3160.000000,2025-08-08,1.000000,2025-08-08 01:27:43,2025-09-07,NaN,119.197.67.48
202,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,270.000000,1.000000,4224.000000,2212.000000,2025-08-15,0.000000,2025-08-15 00:33:39,2025-09-14,WIFI,211.235.99.203
203,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,270.000000,1.000000,4224.000000,2212.000000,2025-08-15,0.000000,2025-08-15 00:30:45,2025-09-14,WIFI,211.235.99.203
204,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,761.000000,144400642.000000,4224.000000,3160.000000,2025-08-24,10.000000,2025-08-24 10:12:20,2025-09-23,NaN,34.64.72.46
205,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,643.000000,1.000000,4224.000000,3160.000000,2025-08-13,13.000000,2025-08-13 13:32:17,2025-09-12,NaN,18.212.241.187
206,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,270.000000,1.000000,4224.000000,2212.000000,2025-07-30,3.000000,2025-07-30 03:28:11,2025-08-29,WIFI,182.221.158.246
207,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,270.000000,1.000000,4224.000000,2212.000000,2025-08-11,1.000000,2025-08-11 01:41:11,2025-09-10,WIFI,59.1.78.176
208,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,761.000000,144400642.000000,4224.000000,3160.000000,2025-08-03,18.000000,2025-08-03 18:39:42,2025-09-02,NaN,34.64.72.46
209,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,761.000000,144400642.000000,4224.000000,3160.000000,2025-08-05,22.000000,2025-08-05 22:44:16,2025-09-04,NaN,34.64.72.46
210,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,643.000000,1.000000,4224.000000,3160.000000,2025-08-22,23.000000,2025-08-22 23:19:28,2025-09-21,NaN,44.213.60.172
211,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,337.000000,1.000000,4224.000000,3160.000000,2025-08-03,12.000000,2025-08-03 12:10:02,2025-09-02,NaN,218.49.208.23
212,163147,kmATsHYwmH,76,1355,613872,3,5,Find Out: 숨은 물건 찾기,"Find Out: 숨은 물건 찾기,com.find.out.hidden.objects...",https://cf.smaad.net/419366192/111818838.png,...,270.000000,1.000000,4224.000000,2212.000000,2025-07-30,15.000000,2025-07-30 15:16:54,2025-08-29,WIFI,211.117.157.22

In [ ]:
participate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16854865 entries, 0 to 16854864
Data columns (total 13 columns):
 #   Column          Dtype
---  ------          -----
 0   click_key       object
 1   ads_idx         int64
 2   dvc_idx         int64
 3   mda_idx         int64
 4   pub_sub_rel_id  int64
 5   contract_price  int64
 6   media_price     int64
 7   click_day       object
 8   click_time      int64
 9   click_date      object
 10  exp_day         object
 11  network         object
 12  user_ip         object
dtypes: int64(7), object(6)
memory usage: 1.6+ GB

In [38]:
participate[participate['ads_idx']==321237]

Empty DataFrame
Columns: [click_key, ads_idx, dvc_idx, mda_idx, pub_sub_rel_id, contract_price, media_price, click_day, click_time, click_date, exp_day, network, user_ip]
Index: []