In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
from matplotlib_inline.backend_inline import set_matplotlib_formats

from scipy import stats
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score

### 도메인 테이블 다운

In [19]:
from google.cloud import bigquery
import pandas as pd

# 클라이언트 생성 (환경변수 GOOGLE_APPLICATION_CREDENTIALS 설정 필요)
client = bigquery.Client(project="sodium-primer-471002-n4")

# 쿼리 작성
query = """
SELECT *
FROM `sodium-primer-471002-n4.test_ad_list.plus_domain1`
"""

# 쿼리 실행 후 DataFrame으로 변환
df = client.query(query).to_dataframe()

print(df.head())

DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

In [7]:
! pip install catboost

Collecting catboost
  Using cached catboost-1.2.8-cp311-cp311-macosx_11_0_universal2.whl.metadata (1.4 kB)
Collecting graphviz (from catboost)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from catboost) (3.10.5)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from catboost) (2.2.6)
Requirement already satisfied: pandas>=0.24 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from catboost) (2.3.2)
Requirement already satisfied: scipy in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from catboost) (1.16.1)
Collecting plotly (from catboost)
  Downloading plotly-6.3.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: six in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/t2023-m0052/Documents/GitHub/final_project/.venv/lib/python3.11/site-packages (from matplotlib->catboost) (3.2.3)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.5.0-py3-none-any.whl.metadata (11 kB)
Using cached catboost-1.2.8-cp311-cp311-macosx_11_0_universal2.whl (27.8 MB)
Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-6.3.0-py3-none-any.whl (9.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 7.6 MB/s eta 0:00:00a 0:00:01 MB 7.0 MB/s eta 0:00:02
Downloading narwhals-2.5.0-py3-none-any.whl (407 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.3/407.3 kB 4.7 MB/s eta 0:00:0000:0100:01
Installing collected packages: narwhals, graphviz, plotly, catboost
Successfully installed catboost-1.2.8 graphviz-0.21 narwhals-2.5.0 plotly-6.3.0

In [8]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, roc_auc_score

### train, test 나누기

In [11]:
# 유저 확인
part_earn = pd.read_csv('/Users/t2023-m0052/Documents/GitHub/final_project/data/참여적립조인.csv')
part_earn.head()

,Unnamed: 0,click_key,ads_idx,dvc_idx,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,...,network,user_ip,rwd_idx,ads_code,advid,adv_cost,earn_cost,regdate,ctit,conversion
0,0,000000d54b9faad47ee99d6cd3cf53894dd4baa5,313780,61906528,539,144350110,6000,4500,2025-08-17,21,...,0,16.184.28.219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,000002b4d92f7648b455877c2676452efcd22a09,412426,34422806,58,46032732,180,170,2025-07-26,2,...,NaN,35.78.117.76,238313226.0,yuRe4YoPuZ,40ceb01c-9b60-4452-bacd-0e061fb18ab4,180.0,170.0,2025-07-26 02:19:21,57.0,1
2,2,0000057e97361ff3d0263aaecee34cfaa3ba30fb,443660,38366075,808,1,170,120,2025-08-12,18,...,WIFI,39.7.55.192,239017177.0,WuIp8HKmt9,73793f44-a471-4351-ae1c-d09accaf223a,170.0,120.0,2025-08-12 18:19:21,82.0,1
3,3,00000607f60139015da3ee1dd5499db3faa100dc,360192,61894110,539,144350110,6000,4500,2025-08-17,3,...,0,211.252.100.157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,0000066bc25d4a6d147c27326cf972a4de88024e,372307,61956954,539,144350110,15600,11700,2025-08-18,8,...,0,3.38.148.211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [12]:
part_earn = part_earn.drop(['Unnamed: 0', 'click_key', 'regdate'], axis=1)
part_earn.head()

,ads_idx,dvc_idx,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip,rwd_idx,ads_code,advid,adv_cost,earn_cost,ctit,conversion
0,313780,61906528,539,144350110,6000,4500,2025-08-17,21,2025-08-17 21:07:37,2025-09-16,0,16.184.28.219,NaN,NaN,NaN,NaN,NaN,NaN,0
1,412426,34422806,58,46032732,180,170,2025-07-26,2,2025-07-26 02:18:24,2025-08-25,NaN,35.78.117.76,238313226.0,yuRe4YoPuZ,40ceb01c-9b60-4452-bacd-0e061fb18ab4,180.0,170.0,57.0,1
2,443660,38366075,808,1,170,120,2025-08-12,18,2025-08-12 18:17:59,2025-09-11,WIFI,39.7.55.192,239017177.0,WuIp8HKmt9,73793f44-a471-4351-ae1c-d09accaf223a,170.0,120.0,82.0,1
3,360192,61894110,539,144350110,6000,4500,2025-08-17,3,2025-08-17 03:35:02,2025-09-16,0,211.252.100.157,NaN,NaN,NaN,NaN,NaN,NaN,0
4,372307,61956954,539,144350110,15600,11700,2025-08-18,8,2025-08-18 08:01:26,2025-09-17,0,3.38.148.211,NaN,NaN,NaN,NaN,NaN,NaN,0

In [6]:
part_earn.columns

Index(['click_key', 'ads_idx', 'dvc_idx', 'mda_idx', 'pub_sub_rel_id',
       'contract_price', 'media_price', 'click_day', 'click_time',
       'click_date', 'exp_day', 'network', 'user_ip', 'rwd_idx', 'ads_code',
       'advid', 'adv_cost', 'earn_cost', 'regdate', 'ctit', 'conversion'],
      dtype='object')

In [13]:
domain = pd.read_csv("/Users/t2023-m0052/Documents/GitHub/final_project/data/광고도메인리스트.csv")
domain.head()

,Unnamed: 0,ads_idx,ads_code,aff_idx,adv_idx,ads_type,ads_category,ads_name,ads_icon_img,ads_summary,...,ads_edate,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,regdate,domain
0,0,6508,3u4lOKJAek,13,335,3,10,스마트피싱보호,https://seimg.pincrux.com/icon/1551770735.png,"[상품소개]\n알면 피하고, 모르면 당하는 보이스피싱\n나와 소중한 가족을 안전하게...",...,9999-12-31 00:00:00,0,100,7,1400,1100,2381500,NONE,2020-04-23 17:53:01 UTC,금융
1,1,6985,SijDrtH4GV,13,335,3,7,DB손해보험 다이렉트,https://seimg.pincrux.com/icon/1575337232.jpg,[참여방법]\n- 빠르고 간편한 DB손해보험 다이렉트에서\n- 내 차 보험료를 지금...,...,9999-06-06 00:00:00,0,100,7,2700,2300,1201938,NONE,2020-06-30 15:22:59 UTC,금융
2,2,8327,k1RZftVHoW,13,335,3,10,파일썬,https://static.i-screen.kr/img/ad/icon/aff_13_...,[참여 방법]\n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동\n2. 이벤트 ...,...,9999-12-31 23:59:00,0,100,7,3200,2420,1673458,NONE,2020-11-10 11:21:43 UTC,미디어/컨텐츠
3,3,9264,EGZcaVOtlc,23,220,3,10,하나 가득담은 운전자보험가입,https://i.imgur.com/kaWiYyT.png,하나손해보험 다이렉트 운전자보험 가입시\n\n01.참여방법\n1) 계산하기 페이지를...,...,9999-12-31 23:59:59,0,100,7,11000,8250,2372800,NONE,2020-11-30 15:16:45 UTC,금융
4,4,9716,NwZZq45Kgb,6,10,3,8,베이비러브 참여 신청,https://nextapps-nas.aws.appang.kr/icon/SDl2uC...,[참여방법]\n- 페이지 이동 > 베이버러브 참여신청 완료\n- 25-55세 SKT...,...,2029-11-29 00:00:00,25,55,2,600,480,2699900,NONE,2021-01-11 16:11:27 UTC,생활

In [15]:
cl_domain = domain.drop(['Unnamed: 0','ads_icon_img', 'ads_summary'# , #'ads_sdate', 
                         #'ads_age_min', 'ads_age_max'
                         ], axis = 1)

유저 속성: user_game_ratio, user_click_rate, os_type

매체 속성: mda_avg_reward, mda_game_ratio

광고 속성: ad_reward_price, ad_domain_game, ad_ctr, 요일-전환 잘 되는, 시간-전환 잘 되는
단가
correlation 확인

['ads_category', 'ads_contract_price', 'ads_os_type', 'hour', 'weekday']

In [ ]:
# random 으로 유저 8:2로 뽑기 
part_earn['dvc_idx'].unique()
# initialize data
train_data = np.random.randint(0,
                               100, 
                               size=(100, 10))

In [ ]:
#독립/ 종속 변수 분리
X = data.drop(columns=['id','CustomerId','Surname','Exited','conversion'],axis=1).reset_index(drop=True)
y_true = data['conversion'].reset_index(drop=True)
print('전처리 완료:',X.shape,y_true.shape)
display(X.head(3))
print('----------------------------')

#테스터 분리
X_train, X_test, y_train, y_test = train_test_split(X,y_true,stratify = y_true,test_size = 0.2, random_state= 42)
print('데이터 분리 후 크기 확인 : ',X_train.shape, X_test.shape, y_train.shape, y_test.shape)

#범주형 컬럼 변수 선언
cat_features = ['ads_category','Gender']

#모델 생성 - 범주형 변수 옵션 설정 'cat_features'
model = CatBoostClassifier(random_state=42,cat_features=cat_features)

#학습
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#평가
print('ac:', accuracy_score(y_test, y_pred))
print('f1:', f1_score(y_test, y_pred))
print('recall:', recall_score(y_test, y_pred))
print('precision:', precision_score(y_test, y_pred))
print("AUC :", roc_auc_score(y_test, y_pred))

In [ ]:
X =

In [ ]:
features = []