In [142]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib_inline.backend_inline import set_matplotlib_formats
import numpy as np
import seaborn as sns
from scipy import stats
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.impute import SimpleImputer
from sklearn.metrics import adjusted_rand_score
from sklearn.metrics import calinski_harabasz_score
from typing import Dict, Optional, Tuple, Any, List
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
from lightgbm import LGBMClassifier
from sklearn.metrics import roc_auc_score, average_precision_score, precision_recall_curve
from sklearn.metrics import precision_score
import lightgbm as lgb
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.inspection import permutation_importance
from scipy import stats
from collections import defaultdict
from math import log2
from scipy.sparse import coo_matrix
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_absolute_error, r2_score
from scipy.stats import spearmanr
import re, gc, hashlib
from typing import Optional, Iterable
from time import perf_counter
from datetime import datetime, timedelta
from sklearn.metrics import ndcg_score
import warnings, math
from sklearn.linear_model import LogisticRegression

# def _rmse(y_true, y_pred):
#     return float(np.sqrt(mean_squared_error(y_true, y_pred)))

# def _spearman(y_true, y_pred):
#     c = spearmanr(y_true, y_pred).correlation
#     return float(c) if np.isfinite(c) else np.nan

# import warnings
# warnings.filterwarnings('ignore')

In [143]:
# 한글 폰트
plt.rc("font", family = 'AppleGothic')
plt.rc("axes", unicode_minus = False)

# 글씨 선명하게
set_matplotlib_formats("retina")

In [144]:
ads_sch = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/스케줄.csv')
print(f"데이터 수 : {ads_sch.shape}")
ads_sch.head()

데이터 수 : (527696, 11)

,sch_idx,ads_idx,sch_type,mda_idx_arr,sch_sdatetime,sch_edatetime,sch_adv_pay,sch_ads_pay,sch_mda_pay,sch_clk_num,sch_turn_num
0,1257478,463989,M,"562,563",2025-09-11 09:42:03,9999-12-31 23:59:59,18,18,14,99999999,14
1,1257477,463989,A,NaN,2025-09-11 09:42:03,9999-12-31 23:59:59,18,18,12,99999999,14
2,1257476,463988,M,"562,563",2025-09-11 09:42:02,9999-12-31 23:59:59,18,18,14,99999999,18
3,1257475,463988,A,NaN,2025-09-11 09:42:02,9999-12-31 23:59:59,18,18,12,99999999,18
4,1257474,463987,M,"562,563",2025-09-11 09:41:55,9999-12-31 23:59:59,18,18,14,99999999,7

In [145]:
ads_time = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/수정_시간별적립보고서(최종).csv')
print(f"데이터 수 : {ads_time.shape}")
ads_time.head()

데이터 수 : (279916, 10)

,rpt_time_date,rpt_time_time,ads_idx,mda_idx,rpt_time_clk,rpt_time_turn,rpt_time_acost,rpt_time_earn,weekday,week_type
0,2025-07-27,0,11059,398,5,0,0,0,6,주말
1,2025-07-27,0,13209,583,3,0,0,0,6,주말
2,2025-07-27,0,13928,303,3,3,510,360,6,주말
3,2025-07-27,0,13928,324,3,3,510,360,6,주말
4,2025-07-27,0,13928,340,6,6,1020,720,6,주말

In [146]:
ads_domain = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/광고도메인리스트_1년치.csv')
print(f"데이터 수 : {ads_domain.shape}")
ads_domain.head()

데이터 수 : (233408, 24)

,Unnamed: 0,domain,row_id,ads_idx,ads_code,aff_idx,adv_idx,ads_type,ads_category,ads_name,ads_icon_img,ads_summary,ads_save_way,ads_day_cap,ads_sdate,ads_edate,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,regdate
0,0,금융,153088,154946,KoM69LPFUB,8,50,3,7,어센틱금융그룹 내보험조회,https://static.adbrix.igaworks.com/adpopcorn/2...,[참여 방법]\n1. 광고 참여 버튼 터치하여 이벤트 페이지로 이동\n2. 이벤트 ...,보험조회,N,2025-02-12 10:00:00,2029-11-29 00:00:00,0,100,7,800,640,2444400,NONE,2025-02-12 10:18:46
1,21,게임,135518,137375,RBjgpLVOmR,71,910,3,8,DK모바일 리본 사전예약,https://cdnet.nasmob.com/nstation/image/202501...,사전예약 완료하고 리워드 받으세요.\n*최초 참여 시에만 리워드가 지급됩니다.\n\...,사전예약,N,2025-01-10 18:00:00,2030-01-01 00:00:00,0,100,7,200,150,2431500,NONE,2025-01-10 18:48:52
2,23,게임,427141,429013,TUSVjcBYtK,76,1355,3,5,인생존망겜(레벨 67 달성),https://cf.smaad.net/911915789/554142578.png,"톡 하면 진화! BANG 터지는 즐거움!\n\n\n족장님, \""인생존망겜\""에 오신...",레벨 67 달성,N,2025-07-11 16:23:32,9999-12-31 23:59:59,0,100,2,9600,7200,2460500,NONE,2025-07-11 16:23:32
3,31,게임,161321,163182,OLNpNxxGJm,76,1355,3,5,고블린 우드: 타이쿤 유휴 심,https://cf.smaad.net/754849948/673067161.png,새로운 중독성 있는 채굴 시뮬레이터 게임 - 고블린의 숲: 목재 거부에 준비되셨나요...,레벨15 도달,N,2025-02-27 16:00:00,9999-12-31 23:59:59,0,100,2,4480,3360,2451800,NONE,2025-02-26 17:05:49
4,34,게임,161392,163254,r78MSmvuQk,76,1355,3,5,Save the Pets,https://cf.smaad.net/776137827/461670280.jpg,항상 슈퍼히어로가 되는 꿈을 꾸셨나요? 도움이 필요한 작고 멋진 생물을 위해 하나가...,깊이 850M 도달,N,2025-02-27 16:00:00,2031-01-03 00:00:00,0,100,1,1440,1080,2450800,NONE,2025-02-26 17:57:33

In [147]:
ads_list = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/수정2_광고목록.csv')
print(f"데이터 수 : {ads_list.shape}")
ads_list.head()

데이터 수 : (445039, 21)

,ads_idx,ads_code,aff_idx,adv_idx,ads_type,ads_category,ads_name,ads_icon_img,ads_summary,ads_save_way,ads_day_cap,ads_sdate,ads_edate,ads_age_min,ads_age_max,ads_os_type,ads_contract_price,ads_reward_price,ads_order,ads_rejoin_type,regdate
0,160,tr71opm6C1,6,10,1,1,리니지레드나이츠,https://lh3.googleusercontent.com/oDGXxngO9oOP...,[앱설명]<br />[설치형] 매력만점 영웅들과 소환수들이 함께하는 취향저격 RPG...,받기,N,2016-12-01 00:00:00,9999-12-31 23:59:59,0,100,2,170,150,982800,NONE,2017-04-06 13:19:53
1,284,xlNpfkgtLX,6,10,1,1,강철의함대:Ocean Overlord,http://nextapps-nas.aws.appang.kr/icon/2016122...,"[앱설명]<br />[설치형] 한, 중, 일 아시아 유저들과 함께 대규모 해상 전투...",받기,N,2016-12-29 00:00:00,9999-12-31 23:59:59,0,100,2,180,160,987200,NONE,2017-01-10 10:37:22
2,292,7Hj8V5QKiy,6,10,1,1,스노우 SNOW,http://nextapps-nas.aws.appang.kr/icon/2016092...,"[앱설명]<br />[설치형] 셀카, 얼굴인식 스티커, 꿀잼 카메라<br /><br...",받기,N,2016-12-29 00:00:00,9999-12-31 23:59:59,0,100,2,160,160,987300,NONE,2017-01-02 12:51:34
3,304,1RfxHJcuEe,6,10,2,1,서머너즈 워: 천공의 아레나,http://nextapps-nas.aws.appang.kr/icon/EecpHzP...,[앱설명]<br />[실행형] 전 세계 5000만 소환사들을 사로잡은 명작 RPG<...,최초 오픈,N,2017-01-01 00:00:00,9999-12-31 23:59:59,0,100,2,230,210,931000,NONE,2017-03-30 17:05:23
4,306,l3GyilYEVk,6,10,1,1,하이마트,http://nextapps-nas.aws.appang.kr/icon/2016032...,새롭게 단장한 하이마트 쇼핑몰 앱!,받기,Y,2017-01-01 00:00:00,2019-11-01 00:00:00,0,100,2,170,140,1155100,NONE,2017-06-12 15:24:46

In [148]:
ads_rwd = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/수정_광고적립.csv')
print(f"데이터 수 : {ads_rwd.shape}")
ads_rwd.head()

데이터 수 : (1475031, 14)

,rwd_idx,ads_idx,ads_code,mda_idx,pub_sub_rel_id,dvc_idx,advid,click_key,adv_cost,earn_cost,click_date,regdate,ctit,cost_diff
0,238304818,413490,CFZ6lzEmeD,22,27496512,32947806,09b6a808-4f76-4584-87c5-626f21f472a0,b0e22dba943810794d25c993dff425c4e16d0744,190,120,2025-07-26 00:00:31,2025-07-26 00:05:02,271,70
1,238304829,413490,CFZ6lzEmeD,22,27496512,47387244,ba4fd0c8-4f06-4dfa-9c3f-c6b39ee7066e,0679ff4c6a14beba296e44d7ffdd88129f42ffbf,190,120,2025-07-26 00:00:32,2025-07-26 00:08:17,465,70
2,238304816,413490,CFZ6lzEmeD,22,27496512,32425124,64c675d0-8edd-4478-9906-a806651fdf92,68eb28d636724061da21e490a1afff6a39cd78f7,190,120,2025-07-26 00:00:42,2025-07-26 00:04:43,241,70
3,238304817,413490,CFZ6lzEmeD,22,27496513,34006545,a08ebb04-e70a-4492-89d4-17fa96bf8c75,37da42f12b6f732d8c8bf1a609c01e569b7f8a09,190,120,2025-07-26 00:00:54,2025-07-26 00:04:45,231,70
4,238304802,133653,rl8ud4uNQC,801,1,56867331,dbe54f40-41b5-4423-ae2f-048fd6ecf5af,624b1bbc57c9ea81005c74e1956d48e76d974816,260,195,2025-07-26 00:01:07,2025-07-26 00:02:04,57,65

In [149]:
ads_info = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/수정2_광고참여정보.csv')
print(f"데이터 수 : {ads_info.shape}")
ads_info.head()

데이터 수 : (16854865, 14)

,click_key,ads_idx,dvc_idx,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip,converted
0,000000d54b9faad47ee99d6cd3cf53894dd4baa5,313780,61906528,539,144350110,6000,4500,2025-08-17,21,2025-08-17 21:07:37,2025-09-16,0,16.184.28.219,0
1,000002b4d92f7648b455877c2676452efcd22a09,412426,34422806,58,46032732,180,170,2025-07-26,2,2025-07-26 02:18:24,2025-08-25,NaN,35.78.117.76,1
2,0000057e97361ff3d0263aaecee34cfaa3ba30fb,443660,38366075,808,1,170,120,2025-08-12,18,2025-08-12 18:17:59,2025-09-11,WIFI,39.7.55.192,1
3,00000607f60139015da3ee1dd5499db3faa100dc,360192,61894110,539,144350110,6000,4500,2025-08-17,3,2025-08-17 03:35:02,2025-09-16,0,211.252.100.157,0
4,0000066bc25d4a6d147c27326cf972a4de88024e,372307,61956954,539,144350110,15600,11700,2025-08-18,8,2025-08-18 08:01:26,2025-09-17,0,3.38.148.211,0

In [150]:
ads_join = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/참여적립조인.csv')
print(f"데이터 수 : {ads_join.shape}")
ads_join.head()

데이터 수 : (16854865, 22)

,Unnamed: 0,click_key,ads_idx,dvc_idx,mda_idx,pub_sub_rel_id,contract_price,media_price,click_day,click_time,click_date,exp_day,network,user_ip,rwd_idx,ads_code,advid,adv_cost,earn_cost,regdate,ctit,conversion
0,0,000000d54b9faad47ee99d6cd3cf53894dd4baa5,313780,61906528,539,144350110,6000,4500,2025-08-17,21,2025-08-17 21:07:37,2025-09-16,0,16.184.28.219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1,000002b4d92f7648b455877c2676452efcd22a09,412426,34422806,58,46032732,180,170,2025-07-26,2,2025-07-26 02:18:24,2025-08-25,NaN,35.78.117.76,238313226.0,yuRe4YoPuZ,40ceb01c-9b60-4452-bacd-0e061fb18ab4,180.0,170.0,2025-07-26 02:19:21,57.0,1
2,2,0000057e97361ff3d0263aaecee34cfaa3ba30fb,443660,38366075,808,1,170,120,2025-08-12,18,2025-08-12 18:17:59,2025-09-11,WIFI,39.7.55.192,239017177.0,WuIp8HKmt9,73793f44-a471-4351-ae1c-d09accaf223a,170.0,120.0,2025-08-12 18:19:21,82.0,1
3,3,00000607f60139015da3ee1dd5499db3faa100dc,360192,61894110,539,144350110,6000,4500,2025-08-17,3,2025-08-17 03:35:02,2025-09-16,0,211.252.100.157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,4,0000066bc25d4a6d147c27326cf972a4de88024e,372307,61956954,539,144350110,15600,11700,2025-08-18,8,2025-08-18 08:01:26,2025-09-17,0,3.38.148.211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [151]:
ads_segment = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/ads_segment.csv')
print(f"데이터 수 : {ads_segment.shape}")
ads_segment.head()

데이터 수 : (9517, 40)

,Unnamed: 0,ads_idx,media_count,user_count,total_clicks,total_conversions,ads_category,domain,ads_os_type,ads_order,ctit_mean,ctit_median,ads_rejoin_type,contract_price,media_price,first_click,last_click,ads_name,ads_sdate,expire,days_active,daily_avg_conversions,cvr,margin,roi,total_net_return,ads_level_detailed,daily_clicks,daily_users,scale_level,performance_level,ads_level,media_score,conv_score,clicks_score,stability_score,cvr_score,total_score,ads_size,cluster
0,0,6508,1,1,2,0,10,금융,7,2381500,NaN,NaN,NONE,1400,1100,2025-07-29 08:54:30,2025-07-29 08:55:55,스마트피싱보호,2020-04-23 17:00:00,0,1,0.0,0.0,300,0.3,0,MEDIUM,2.000000,1.000000,SMALL,LOW,SMALL_LOW,1,0,0,0,0,1,SMALL,0
1,1,6985,2,30,46,0,7,금융,7,1201938,NaN,NaN,NONE,2700,2300,2025-07-26 11:02:18,2025-08-24 05:39:13,DB손해보험 다이렉트,2020-06-30 15:00:00,0,29,0.0,0.0,400,0.2,0,MEDIUM,1.586207,1.034483,MEDIUM,LOW,MEDIUM_LOW,2,0,0,3,0,5,MEDIUM,0
2,2,8327,1,6,11,0,10,미디어/컨텐츠,7,1673458,NaN,NaN,NONE,3200,2420,2025-08-02 08:30:52,2025-08-18 22:32:25,파일썬,2020-11-10 11:21:00,0,17,0.0,0.0,780,0.3,0,MEDIUM,0.647059,0.352941,SMALL,LOW,SMALL_LOW,1,0,0,3,0,4,SMALL,0
3,3,9264,1,1,1,0,10,금융,7,2372800,NaN,NaN,NONE,11000,8250,2025-08-14 13:54:12,2025-08-14 13:54:12,하나 가득담은 운전자보험가입,2020-11-30 00:00:00,0,1,0.0,0.0,2750,0.3,0,LARGE,1.000000,1.000000,SMALL,LOW,SMALL_LOW,1,0,0,0,0,1,SMALL,0
4,4,9716,2,4,6,1,8,생활,2,2699900,74.0,74.0,NONE,600,336,2025-07-28 01:22:36,2025-07-29 07:14:36,베이비러브 참여 신청,2021-01-11 16:00:00,0,2,0.5,0.2,264,0.8,264,MEDIUM,3.000000,2.000000,MEDIUM,LOW,MEDIUM_LOW,2,0,1,1,0,4,SMALL,0

In [152]:
media_portfolio = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/media_portfolio.csv')
print(f"데이터 수 : {media_portfolio.shape}")
media_portfolio.head()

데이터 수 : (189, 50)

,Unnamed: 0,mda_idx,user_count,total_clicks,total_conversions,first_click,last_click,days_active,daily_avg_conversions,LARGE,MEDIUM,MEGA,SMALL,total_ads,MEGA_ratio,LARGE_ratio,MEDIUM_ratio,SMALL_ratio,ads_category_0_pct,ads_category_1_pct,ads_category_2_pct,ads_category_3_pct,ads_category_4_pct,ads_category_5_pct,ads_category_6_pct,ads_category_7_pct,ads_category_8_pct,ads_category_10_pct,ads_category_11_pct,ads_category_13_pct,ads_os_type_1_pct,ads_os_type_2_pct,ads_os_type_3_pct,ads_os_type_7_pct,domain_게임_pct,domain_교육_pct,domain_금융_pct,domain_기타_pct,domain_미디어/컨텐츠_pct,domain_뷰티_pct,domain_비영리/공공_pct,domain_생활_pct,domain_식당/카페_pct,domain_식음료_pct,domain_운동/스포츠_pct,domain_운세_pct,domain_의료/건강_pct,domain_채용_pct,domain_커머스_pct,expected_total_profit
0,0,12,75700,232438,82938,2025-07-26 00:00:02,2025-08-25 11:22:16,31,2675.419355,7,0,17,0,24,70.8,29.2,0.0,0.0,8.333333,12.500000,25.000000,29.166667,0.0,0.000000,0.0,0.000000,25.000000,0.000000,0.0,0.0,0.000000,70.833333,0.000000,29.166667,29.166667,0.00000,4.166667,0.000000,4.166667,0.000000,16.666667,12.500000,0.00000,16.666667,0.000000,0.000000,4.166667,0.000000,12.500000,3003668
1,1,14,31834,84763,22983,2025-07-26 00:01:22,2025-08-25 11:22:40,31,741.387097,31,5,22,1,59,37.3,52.5,8.5,1.7,0.000000,20.338983,18.644068,8.474576,0.0,25.423729,0.0,3.389831,22.033898,1.694915,0.0,0.0,42.372881,38.983051,0.000000,18.644068,44.067797,0.00000,11.864407,3.389831,8.474576,5.084746,0.000000,13.559322,0.00000,3.389831,0.000000,0.000000,3.389831,1.694915,5.084746,2733547
2,2,18,2825,5961,250,2025-07-26 00:00:49,2025-08-25 11:13:19,31,8.064516,19,0,4,0,23,17.4,82.6,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,60.869565,0.0,0.000000,30.434783,8.695652,0.0,0.0,0.000000,82.608696,0.000000,17.391304,60.869565,0.00000,13.043478,0.000000,13.043478,0.000000,0.000000,8.695652,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,4.347826,182366
3,3,22,37668,83355,35232,2025-07-26 00:00:31,2025-08-25 11:14:50,31,1136.516129,67,58,33,8,166,19.9,40.4,34.9,4.8,8.433735,6.626506,10.843373,5.421687,0.0,10.240964,0.0,6.626506,26.506024,25.301205,0.0,0.0,0.000000,40.361446,3.012048,56.626506,19.277108,0.60241,26.506024,0.000000,10.240964,1.807229,3.012048,11.445783,0.60241,4.216867,1.204819,7.831325,4.819277,1.204819,7.228916,2541770
4,4,26,402,678,70,2025-07-26 01:45:31,2025-08-25 10:22:36,31,2.258065,10,5,3,1,19,15.8,52.6,26.3,5.3,0.000000,0.000000,15.789474,0.000000,0.0,47.368421,0.0,0.000000,26.315789,10.526316,0.0,0.0,78.947368,0.000000,0.000000,21.052632,52.631579,0.00000,15.789474,0.000000,10.526316,0.000000,0.000000,10.526316,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,10.526316,2690

In [153]:
ads_new = pd.read_csv('/Users/sparta/Documents/GitHub/final_project/data/신규가상광고.csv')
print(f"데이터 수 : {ads_new.shape}")
ads_new.head()

데이터 수 : (8, 10)

,ads_idx,ads_type,ads_category,ads_name,ads_os_type,ads_contract_price,ads_media_price,ads_reward_price,ads_rejoin_type,domain
0,500000,12,11,청정원 선물세트,7,6181,4000,4000,REJOINABLE,식음료
1,500001,3,4,옹짬뽕 포항양덕본점,7,18,14,12,ADS_CODE_DAILY_UPDATE,식당/카페
2,500002,3,4,추석선물세트 (리뷰 전체보기 클릭 후 URL 제출),7,17,8,8,NONE,식당/카페
3,500003,11,3,네이버 뉴스 제주뉴스 구독,7,230,160,180,NONE,미디어/컨텐츠
4,500004,7,3,폴라베어 인스타그램 구독,1,230,160,180,NONE,커머스

In [154]:
ads_new.columns

Index(['ads_idx', 'ads_type', 'ads_category', 'ads_name', 'ads_os_type',
       'ads_contract_price', 'ads_media_price', 'ads_reward_price',
       'ads_rejoin_type', 'domain'],
      dtype='object')

In [155]:
pd.set_option("display.max_columns", None) # 열 전체 출력

In [165]:
# =========================================================
#  Ad × Media 추천 + 전환수 예측 (Decomposition: Click × CVR, OS 제외)
#  - 누수 방지: 모든 피처는 OBS에서만 생성, 라벨은 TGT
#  - 클릭: Tweedie 회귀(권장), CVR: logit 회귀
#  - 예측: yhat_turn = yhat_click × yhat_cvr
# =========================================================
# 전제: import pandas as pd, numpy as np, lightgbm as lgb, warnings
#       from typing import *
#       from sklearn.metrics import roc_auc_score
warnings.filterwarnings("ignore", category=UserWarning, module="lightgbm")

# -------------------------------
# 유틸
# -------------------------------
def _to_num(s): return pd.to_numeric(s, errors="coerce").fillna(0)
def _to_dt(s):  return pd.to_datetime(s, errors="coerce")

def _norm_cat_col(df: pd.DataFrame, col: str) -> pd.DataFrame:
    if col in df.columns:
        df = df.copy()
        df[col] = df[col].astype(str).str.strip().str.lower()
        df[col] = df[col].replace({"<na>":"__na__", "nan":"__na__", "none":"__na__", "nat":"__na__"})
    return df

def _norm_cat(s): return pd.Series(s, copy=False).astype("string").str.strip().str.lower()

def _pick_col(cols, cand):
    for c in cand:
        if c in cols: return c
    return None

def _ensure_col(df: pd.DataFrame, out_col: str, cands: List[str]) -> pd.DataFrame:
    col = _pick_col(df.columns, cands)
    df = df.copy()
    if col is None: df[out_col] = "__na__"
    else:           df[out_col] = _norm_cat(df[col])
    return df

# -------------------------------
# 1) 윈도우
# -------------------------------
def split_obs_tgt_by_dates(
    ads_time: pd.DataFrame,
    obs_start: str = "2025-07-25",
    tgt_start: str = "2025-08-20",
    obs_end: Optional[str] = None,
    tgt_end: Optional[str] = None,
    tgt_max_days: int = 6
):
    t = ads_time.copy()
    t["date"] = _to_dt(t["rpt_time_date"])
    if t["date"].isna().all():
        raise ValueError("ads_time['rpt_time_date']에 유효한 날짜가 없습니다.")
    obs_start = pd.to_datetime(obs_start).normalize()
    tgt_start = pd.to_datetime(tgt_start).normalize()
    obs_end = (pd.to_datetime(obs_end).normalize() if obs_end is not None
               else (tgt_start - pd.Timedelta(days=1)).normalize())
    last_date = t["date"].max().normalize()
    tgt_end = (pd.to_datetime(tgt_end).normalize() if tgt_end is not None
               else min(last_date, (tgt_start + pd.Timedelta(days=tgt_max_days)).normalize()))
    obs = t[(t["date"] >= obs_start) & (t["date"] <= obs_end)].copy()
    tgt = t[(t["date"] >= tgt_start) & (t["date"] <= tgt_end)].copy()
    return obs, tgt, obs_start, tgt_end, (tgt_start - pd.Timedelta(days=1)).normalize()

# -------------------------------
# 2) 시간/매체/카테고리/도메인 컨텍스트 (OBS만)
# -------------------------------
def _build_time_signals(obs: pd.DataFrame) -> pd.DataFrame:
    t = obs.copy()
    t["clk"]  = _to_num(t.get("rpt_time_clk", 0))
    t["weekday"] = _to_dt(t["rpt_time_date"]).dt.weekday  # 0~6
    wd = t.groupby(["mda_idx","weekday"], as_index=False).agg(clk=("clk","sum"))
    wd["is_weekend"] = wd["weekday"].isin([5,6]).astype(int)
    g = wd.groupby("mda_idx", as_index=False).agg(clk_total=("clk","sum"))
    w = wd.merge(g, on="mda_idx", how="left")
    day_ratio = (w.assign(ratio=w["clk"]/w["clk_total"].replace(0,np.nan))
                   .sort_values(["mda_idx","ratio"], ascending=[True,False])
                   .groupby("mda_idx").head(1)[["mda_idx","ratio"]]
                   .rename(columns={"ratio":"mda_day_ratio"}))
    weekend_ratio = (w.groupby(["mda_idx","is_weekend"], as_index=False)
                       .agg(clk=("clk","sum")).merge(g,on="mda_idx",how="left"))
    weekend_ratio["mda_weekend_ratio"] = (weekend_ratio["clk"] /
                                          weekend_ratio["clk_total"].replace(0,np.nan)).fillna(0)
    weekend_ratio = weekend_ratio[weekend_ratio["is_weekend"]==1][["mda_idx","mda_weekend_ratio"]]
    out = day_ratio.merge(weekend_ratio, on="mda_idx", how="outer").fillna(0.0)
    out["mda_idx"] = out["mda_idx"].astype(int)
    return out

def build_attr_context(obs: pd.DataFrame, ads_list_with_domain: pd.DataFrame):
    t = obs.copy()
    t["clk"]  = _to_num(t.get("rpt_time_clk", 0))
    t["conv"] = _to_num(t.get("rpt_time_turn", 0))

    # mda 전역
    mda_all = (t.groupby("mda_idx", as_index=False)
                 .agg(mda_clk_global=("clk","sum"), mda_conv_global=("conv","sum")))
    mda_all["mda_cvr_global"] = (mda_all["mda_conv_global"] /
                                 mda_all["mda_clk_global"].replace(0,np.nan)).fillna(0.0)
    mu, sd = mda_all["mda_conv_global"].mean(), mda_all["mda_conv_global"].std(ddof=0)
    mda_all["mda_pop_norm"] = (mda_all["mda_conv_global"] - mu) / (sd + 1e-9)

    # 카테고리×매체
    al = ads_list_with_domain[["ads_idx","ads_category"]].drop_duplicates("ads_idx").copy()
    al["ads_category"] = _norm_cat(al["ads_category"])
    t2 = t.merge(al, on="ads_idx", how="left")
    cat_mda = (t2.groupby(["mda_idx","ads_category"], as_index=False)
                 .agg(clk=("clk","sum"), conv=("conv","sum")))
    cat_mda["cat_cvr"] = (cat_mda["conv"]/cat_mda["clk"].replace(0,np.nan)).fillna(0.0)
    mda_tot = cat_mda.groupby("mda_idx", as_index=False).agg(mda_conv_total=("conv","sum"))
    cat_mda = cat_mda.merge(mda_tot, on="mda_idx", how="left")
    cat_mda["cat_share"] = (cat_mda["conv"]/cat_mda["mda_conv_total"].replace(0,np.nan)).fillna(0.0)

    # 도메인×매체 (ads_list 도메인 기반)
    t_dom = t.merge(
        ads_list_with_domain[["ads_idx","ads_domain"]].drop_duplicates("ads_idx"),
        on="ads_idx", how="left"
    )
    t_dom["ads_domain"] = _norm_cat(t_dom["ads_domain"])
    dom_mda = (t_dom.groupby(["mda_idx","ads_domain"], as_index=False)
                 .agg(clk=("clk","sum"), conv=("conv","sum")))
    dom_mda["dom_cvr"] = (dom_mda["conv"]/dom_mda["clk"].replace(0,np.nan)).fillna(0.0)
    mda_tot2 = dom_mda.groupby("mda_idx", as_index=False).agg(mda_conv_total=("conv","sum"))
    dom_mda = dom_mda.merge(mda_tot2, on="mda_idx", how="left")
    dom_mda["dom_share"] = (dom_mda["conv"]/dom_mda["mda_conv_total"].replace(0,np.nan)).fillna(0.0)

    # 시간 신호
    time_sig = _build_time_signals(obs)

    # (선택) 광고주 신호
    adv_ctx = None
    if "adv_idx" in ads_list_with_domain.columns:
        t_adv = t.merge(ads_list_with_domain[["ads_idx","adv_idx"]].drop_duplicates("ads_idx"),
                        on="ads_idx", how="left")
        adv_all = (t_adv.groupby("adv_idx", as_index=False)
                        .agg(adv_clk_global=("clk","sum"),
                             adv_conv_global=("conv","sum")))
        adv_all["adv_cvr_global"] = (adv_all["adv_conv_global"] /
                                     adv_all["adv_clk_global"].replace(0,np.nan)).fillna(0.0)
        mu2, sd2 = adv_all["adv_conv_global"].mean(), adv_all["adv_conv_global"].std(ddof=0)
        adv_all["adv_pop_norm"] = (adv_all["adv_conv_global"] - mu2) / (sd2 + 1e-9)
        adv_ctx = adv_all

    return {"mda_all": mda_all, "cat_mda": cat_mda, "dom_mda": dom_mda,
            "time_sig": time_sig, "adv_ctx": adv_ctx}

# -------------------------------
# 3) 학습 대상 광고
# -------------------------------
def pick_train_ads_from_tgt(tgt: pd.DataFrame, min_pos_in_tgt: int = 1,
                            max_train_ads: Optional[int] = 20000, rng_seed: int = 42) -> np.ndarray:
    t = tgt.copy()
    t["turn"] = _to_num(t.get("rpt_time_turn", 0))
    pos = (t.groupby("ads_idx")["turn"].apply(lambda s: (s > 0).sum())
             .reset_index(name="pos_cnt"))
    ok = pos[pos["pos_cnt"] >= max(1,int(min_pos_in_tgt))]["ads_idx"].astype(int).values
    if max_train_ads is not None and len(ok) > max_train_ads:
        rng = np.random.RandomState(rng_seed)
        ok = rng.choice(ok, size=max_train_ads, replace=False)
    return np.sort(ok)

# -------------------------------
# 4) 후보 생성
# -------------------------------
def create_candidates(ads_list: pd.DataFrame, mda_all: pd.DataFrame, cat_mda: pd.DataFrame,
                      topC=10, add_random=2, cat_topM=5,
                      min_active_clk=200, min_active_conv=20,
                      rng_seed=42, ad_ids_filter=None, max_per_ad=20):
    mda_active = mda_all[(mda_all["mda_clk_global"]>=min_active_clk) |
                         (mda_all["mda_conv_global"]>=min_active_conv)].copy()
    if mda_active.empty: mda_active = mda_all.copy()
    mda_ids_global = (mda_active.sort_values("mda_conv_global", ascending=False)["mda_idx"]
                      .astype(int).values)
    cat_top = (cat_mda.sort_values(["ads_category","cat_cvr"], ascending=[True,False])
                      .groupby("ads_category").head(cat_topM)[["ads_category","mda_idx"]])
    cat2top = {c: g["mda_idx"].astype(int).tolist() for c,g in cat_top.groupby("ads_category")}
    rng = np.random.RandomState(rng_seed)
    ad_ids = (np.array(ad_ids_filter, dtype=int) if (ad_ids_filter is not None and len(ad_ids_filter)>0)
              else ads_list["ads_idx"].dropna().astype(int).unique())
    ad_meta = ads_list[["ads_idx","ads_category"]].drop_duplicates("ads_idx").copy()
    ad_meta["ads_idx"] = ad_meta["ads_idx"].astype(int)
    ad_meta["ads_category"] = ad_meta["ads_category"].astype(str).str.strip().str.lower()
    ad2cat = ad_meta.set_index("ads_idx")["ads_category"].to_dict()

    pairs=[]
    for ad in ad_ids:
        base=[]
        cat = ad2cat.get(int(ad), None)
        if cat in cat2top: base.extend(cat2top[cat])
        base.extend(mda_ids_global[:min(topC,len(mda_ids_global))])
        base=list(dict.fromkeys(base))
        remain=np.setdiff1d(mda_ids_global, np.array(base, dtype=int))
        if len(remain)>0 and add_random>0:
            base.extend(rng.choice(remain, size=min(add_random,len(remain)), replace=False).tolist())
        if len(base)>max_per_ad: base=base[:max_per_ad]
        pairs += [(int(ad), int(m)) for m in base]
    out = pd.DataFrame(pairs, columns=["ads_idx","mda_idx"]).drop_duplicates()
    print(f"[Candidates] pairs={len(out):,} | ads={len(ad_ids):,} | active_mda={len(mda_active):,} | topC={topC}, rnd={add_random}, cat_topM={cat_topM}, per_ad≤{max_per_ad}")
    return out

# -------------------------------
# 5) 피처 & 라벨 (OBS 피처 / TGT 라벨)
# -------------------------------
FEAT_ALLOW = [
    # mda 전역
    "mda_clk_global","mda_conv_global","mda_cvr_global","mda_pop_norm",
    # 카테고리×매체
    "cat_cvr","cat_share",
    # 광고 가격
    "price_reward_log","price_contract_log","price_ratio",
    # 도메인×매체
    "dom_cvr","dom_share",
    # 시간 신호
    "mda_day_ratio","mda_weekend_ratio",
    # 광고주 신호
    "adv_cvr_global","adv_pop_norm",
    # 외부 포트폴리오가 있으면
    "mda_size","active_ratio","day_ratio","weekend_ratio"
]

def prepare_training_attr_only(
    obs: pd.DataFrame, tgt: pd.DataFrame, ads_list_with_domain: pd.DataFrame,
    topC=10, add_random=2, cat_topM=5, min_active_clk=200, min_active_conv=20,
    max_train_ads: Optional[int] = 20000, min_pos_in_tgt: int = 1,
    media_portfolio: Optional[pd.DataFrame] = None
):
    train_ads = pick_train_ads_from_tgt(tgt, min_pos_in_tgt=min_pos_in_tgt, max_train_ads=max_train_ads)
    actx = build_attr_context(obs, ads_list_with_domain)
    mda_all, cat_mda, dom_mda = actx["mda_all"], actx["cat_mda"], actx["dom_mda"]

    cand = create_candidates(
        ads_list=ads_list_with_domain, mda_all=mda_all, cat_mda=cat_mda,
        topC=topC, add_random=add_random, cat_topM=cat_topM,
        min_active_clk=min_active_clk, min_active_conv=min_active_conv,
        ad_ids_filter=train_ads, max_per_ad=20
    )

    df = cand.merge(
        mda_all[["mda_idx","mda_clk_global","mda_conv_global","mda_cvr_global","mda_pop_norm"]],
        on="mda_idx", how="left"
    )

    ad_meta = ads_list_with_domain[["ads_idx","ads_category","ads_reward_price","ads_contract_price","ads_domain","adv_idx"]].drop_duplicates("ads_idx").copy()
    ad_meta = _norm_cat_col(ad_meta, "ads_category")
    ad_meta = _ensure_col(ad_meta, "ads_domain", ["ads_domain","domain"])
    for c in ["ads_reward_price","ads_contract_price"]:
        ad_meta[c] = _to_num(ad_meta[c])
    ad_meta["price_reward_log"]   = np.log1p(ad_meta["ads_reward_price"])
    ad_meta["price_contract_log"] = np.log1p(ad_meta["ads_contract_price"])
    ad_meta["price_ratio"]        = (ad_meta["ads_reward_price"] /
                                     ad_meta["ads_contract_price"].replace(0,np.nan)).fillna(0.0)

    df = df.merge(ad_meta[["ads_idx","ads_category","ads_domain","adv_idx",
                           "price_reward_log","price_contract_log","price_ratio"]],
                  on="ads_idx", how="left")

    df      = _norm_cat_col(df, "ads_category")
    cat_mda = _norm_cat_col(cat_mda, "ads_category")
    df = df.merge(cat_mda[["mda_idx","ads_category","cat_cvr","cat_share"]],
                  on=["mda_idx","ads_category"], how="left").fillna({"cat_cvr":0.0,"cat_share":0.0})

    dom_mda = dom_mda.copy()
    dom_mda["ads_domain"] = _norm_cat(dom_mda["ads_domain"])
    df["ads_domain"] = _norm_cat(df["ads_domain"])
    df = df.merge(dom_mda[["mda_idx","ads_domain","dom_cvr","dom_share"]],
                  on=["mda_idx","ads_domain"], how="left").fillna({"dom_cvr":0.0,"dom_share":0.0})

    time_sig = actx["time_sig"]
    df = df.merge(time_sig, on="mda_idx", how="left").fillna({"mda_day_ratio":0.0,"mda_weekend_ratio":0.0})

    if actx["adv_ctx"] is not None:
        adv_ctx = actx["adv_ctx"].copy()
        df = df.merge(adv_ctx[["adv_idx","adv_cvr_global","adv_pop_norm"]], on="adv_idx", how="left")
    for c in ["adv_cvr_global","adv_pop_norm"]:
        if c not in df.columns: df[c]=0.0
    df[["adv_cvr_global","adv_pop_norm"]] = df[["adv_cvr_global","adv_pop_norm"]].fillna(0.0)

    if media_portfolio is not None:
        mp = media_portfolio.copy()
        cols = [c for c in ["mda_idx","mda_size","active_ratio","day_ratio","weekend_ratio"] if c in mp.columns]
        if "mda_idx" in cols: df = df.merge(mp[cols], on="mda_idx", how="left")
    for c in ["mda_size","active_ratio","day_ratio","weekend_ratio"]:
        if c not in df.columns: df[c]=0.0

    # ---- 라벨: TGT에서 클릭/전환
    tgt2 = tgt.copy()
    tgt2["clk"]  = _to_num(tgt2.get("rpt_time_clk", 0))
    tgt2["turn"] = _to_num(tgt2.get("rpt_time_turn",0))
    y_agg = (tgt2.groupby(["ads_idx","mda_idx"], as_index=False)
                   .agg(tgt_clk=("clk","sum"), tgt_turn=("turn","sum")))
    # CVR 라벨 (클릭>0인 샘플에 한해 학습)
    y_agg["tgt_cvr"] = (y_agg["tgt_turn"] / y_agg["tgt_clk"].replace(0,np.nan)).clip(0,1)
    df = df.merge(y_agg, on=["ads_idx","mda_idx"], how="left").fillna({"tgt_clk":0.0,"tgt_turn":0.0})

    # 랭커용 relevance (옵션)
    y = df["tgt_turn"].astype(float)
    rel = np.zeros(len(df), dtype=int)
    pos = y > 0
    if pos.sum()>0:
        ylog = np.log1p(y[pos])
        try:
            bins = pd.qcut(ylog, q=3, labels=False, duplicates="drop")
            rel[pos] = bins.astype(int)+1
        except ValueError:
            rel[pos] = 1
    df["relevance"] = rel
    return df, actx

# -------------------------------
# 6) 학습기들 (랭커 + 클릭회귀 + CVR회귀)
# -------------------------------
LABEL_GAIN = [0.0,1.0,4.0,12.0]

def ensure_feature_matrix(df, feat_cols):
    X = df.copy()
    for c in feat_cols:
        if c not in X.columns: X[c]=0.0
        if not np.issubdtype(X[c].dtype, np.number):
            X[c]=pd.to_numeric(X[c], errors="coerce")
    return X[feat_cols].fillna(0.0).astype(np.float32)

def downsample_negatives_per_ad(df, ratio=4, random_state=42):
    out, rng = [], np.random.RandomState(random_state)
    for ad, g in df.groupby("ads_idx", sort=False):
        pos = g[g["tgt_turn"]>0]; neg = g[g["tgt_turn"]<=0]
        if len(pos)==0: continue
        cap = len(pos)*ratio
        if len(neg)>cap: neg = neg.sample(n=cap, random_state=rng)
        out.append(pd.concat([pos,neg], ignore_index=True))
    return pd.concat(out, ignore_index=True) if out else df

def train_attr_ranker(train_df: pd.DataFrame):
    feat_cols = [c for c in FEAT_ALLOW if c in train_df.columns]
    X = ensure_feature_matrix(train_df, feat_cols)
    y = train_df["relevance"].astype(int)
    groups = train_df.groupby("ads_idx").size().astype(int).tolist()
    ranker = lgb.LGBMRanker(
        objective="lambdarank", metric="ndcg", eval_at=[5,10,20],
        learning_rate=0.05, n_estimators=1200, num_leaves=47,
        min_data_in_leaf=40, lambda_l2=1.5, subsample=0.85, colsample_bytree=0.85,
        label_gain=LABEL_GAIN, random_state=42, n_jobs=-1, verbosity=-1
    )
    ranker.fit(X, y, group=groups, sample_weight=np.ones(len(train_df)))
    return ranker, feat_cols

def train_click_regressor(train_df: pd.DataFrame, feat_cols: List[str], tweedie_p: float = 1.1):
    X = ensure_feature_matrix(train_df, feat_cols)
    y = train_df["tgt_clk"].astype(float)
    reg = lgb.LGBMRegressor(
        objective="tweedie", tweedie_variance_power=tweedie_p,
        n_estimators=1200, learning_rate=0.05, num_leaves=47,
        min_data_in_leaf=40, lambda_l2=1.5, subsample=0.85, colsample_bytree=0.85,
        random_state=42, n_jobs=-1, verbosity=-1
    )
    reg.fit(X, y)
    return reg, {"mode":"tweedie_click","twp":tweedie_p}

def _logit_clip(p, eps=1e-6):
    p = np.clip(p, eps, 1-eps)
    return np.log(p/(1-p))

def _sigmoid(x): return 1/(1+np.exp(-x))

def train_cvr_regressor(train_df: pd.DataFrame, feat_cols: List[str]):
    # 클릭>0 인 샘플만 (CVR 정의 가능)
    g = train_df[train_df["tgt_clk"]>0].copy()
    if g.empty:
        # 예외: 학습 불가 시 항상 평균 0.0을 내는 dummy
        dummy = lgb.LGBMRegressor().fit(np.zeros((1, len(feat_cols))), [0.0])
        return dummy, {"mode":"cvr_logit","fallback":True, "mean_logit":-20.0}
    X = ensure_feature_matrix(g, feat_cols)
    y = g["tgt_turn"]/g["tgt_clk"]
    y = y.clip(0,1)
    y_logit = _logit_clip(y.values)
    reg = lgb.LGBMRegressor(
        objective="regression",
        n_estimators=1200, learning_rate=0.05, num_leaves=47,
        min_data_in_leaf=40, lambda_l2=1.5, subsample=0.85, colsample_bytree=0.85,
        random_state=42, n_jobs=-1, verbosity=-1
    )
    reg.fit(X, y_logit)
    return reg, {"mode":"cvr_logit","fallback":False}

# -------------------------------
# 7) 예측 (랭커 스코어 + 클릭×CVR 예측)
# -------------------------------
def predict_all_mda_with_counts_batched(
    ranker, click_reg, cvr_reg, feat_cols, actx, ads_list_with_domain,
    K=20, batch_size=5000, max_predict_ads: Optional[int] = 20000,
    media_portfolio: Optional[pd.DataFrame] = None
) -> Dict[int, pd.DataFrame]:
    mda_all, cat_mda, dom_mda = actx["mda_all"], actx["cat_mda"], actx["dom_mda"]
    time_sig, adv_ctx = actx["time_sig"], actx["adv_ctx"]

    mda_active = mda_all[(mda_all["mda_clk_global"]>=200) | (mda_all["mda_conv_global"]>=20)]
    if mda_active.empty: mda_active = mda_all
    mda_active = mda_active[["mda_idx","mda_clk_global","mda_conv_global","mda_cvr_global","mda_pop_norm"]].copy()
    mda_active["mda_idx"]=mda_active["mda_idx"].astype(int)
    mda_active = mda_active.merge(time_sig, on="mda_idx", how="left").fillna({"mda_day_ratio":0.0,"mda_weekend_ratio":0.0})

    if media_portfolio is not None:
        mp = media_portfolio.copy()
        cols = [c for c in ["mda_idx","mda_size","active_ratio","day_ratio","weekend_ratio"] if c in mp.columns]
        if "mda_idx" in cols: mda_active = mda_active.merge(mp[cols], on="mda_idx", how="left")
    for c in ["mda_size","active_ratio","day_ratio","weekend_ratio"]:
        if c not in mda_active.columns: mda_active[c]=0.0

    ads_meta = ads_list_with_domain[["ads_idx","ads_category","ads_reward_price","ads_contract_price","ads_domain","adv_idx"]].drop_duplicates("ads_idx").copy()
    if max_predict_ads is not None: ads_meta = ads_meta.head(int(max_predict_ads))
    ads_meta = _norm_cat_col(ads_meta, "ads_category")
    ads_meta = _ensure_col(ads_meta, "ads_domain", ["ads_domain","domain"])
    ads_meta["ads_idx"] = ads_meta["ads_idx"].astype(int)
    ads_meta["ads_domain"] = _norm_cat(ads_meta["ads_domain"])
    ads_meta["ads_reward_price"]   = _to_num(ads_meta["ads_reward_price"])
    ads_meta["ads_contract_price"] = _to_num(ads_meta["ads_contract_price"])
    ads_meta["price_reward_log"]   = np.log1p(ads_meta["ads_reward_price"])
    ads_meta["price_contract_log"] = np.log1p(ads_meta["ads_contract_price"])
    ads_meta["price_ratio"]        = (ads_meta["ads_reward_price"] / ads_meta["ads_contract_price"].replace(0,np.nan)).fillna(0.0)
    if adv_ctx is not None:
        ads_meta = ads_meta.merge(adv_ctx[["adv_idx","adv_cvr_global","adv_pop_norm"]], on="adv_idx", how="left")
    for c in ["adv_cvr_global","adv_pop_norm"]:
        if c not in ads_meta.columns: ads_meta[c]=0.0
    ads_meta[["adv_cvr_global","adv_pop_norm"]] = ads_meta[["adv_cvr_global","adv_pop_norm"]].fillna(0.0)

    cat_mda_local = _norm_cat_col(cat_mda[["mda_idx","ads_category","cat_cvr","cat_share"]].copy(), "ads_category")
    dom_mda_local = dom_mda.copy(); dom_mda_local["ads_domain"] = _norm_cat(dom_mda_local["ads_domain"])

    out={}
    ad_ids = ads_meta["ads_idx"].tolist()
    for i in range(0, len(ad_ids), batch_size):
        ad_batch = ads_meta.iloc[i:i+batch_size]
        grid = ad_batch[["ads_idx","ads_category","ads_domain","price_reward_log","price_contract_log","price_ratio",
                         "adv_idx","adv_cvr_global","adv_pop_norm"]] \
               .merge(mda_active, how="cross")

        grid = grid.merge(cat_mda_local, on=["mda_idx","ads_category"], how="left") \
                   .fillna({"cat_cvr":0.0,"cat_share":0.0})
        grid = grid.merge(dom_mda_local[["mda_idx","ads_domain","dom_cvr","dom_share"]],
                          on=["mda_idx","ads_domain"], how="left") \
                   .fillna({"dom_cvr":0.0,"dom_share":0.0})

        X = ensure_feature_matrix(grid, feat_cols)
        score = ranker.predict(X)  # 랭커 점수

        # Decomposition: click × cvr
        yhat_clk = np.maximum(0.0, click_reg.predict(X))
        yhat_cvr_logit = cvr_reg.predict(X)
        yhat_cvr = np.clip(_sigmoid(yhat_cvr_logit), 0.0, 1.0)
        yhat_turn = yhat_clk * yhat_cvr

        grid2 = grid[["ads_idx","mda_idx","ads_category","mda_cvr_global","mda_pop_norm","mda_clk_global","mda_conv_global"]].copy()
        grid2["score"] = score.astype(float)
        grid2["yhat_turn"] = yhat_turn.astype(float)

        for ad, g in grid2.groupby("ads_idx", sort=False):
            top = g.nlargest(K, "score")
            out[int(ad)] = top.sort_values("score", ascending=False).reset_index(drop=True)
        print(f"[Predict+Count] processed ads {i+len(ad_batch)}/{len(ad_ids)}")
    return out

# -------------------------------
# 8) 평가
# -------------------------------
def _precision_recall_hit_at_k(preds_dict, gt_dict, k=10):
    P,R,H=[],[],[]
    for ad, df in preds_dict.items():
        if ad not in gt_dict: continue
        pred = df["mda_idx"].astype(int).tolist()[:k]
        true = set(gt_dict[ad]); if_not = (not true)
        if if_not: continue
        inter = len(set(pred)&true)
        P.append(inter/max(1,len(pred))); R.append(inter/len(true)); H.append(1.0 if inter>0 else 0.0)
    return (float(np.mean(P)) if P else 0.0,
            float(np.mean(R)) if R else 0.0,
            float(np.mean(H)) if H else 0.0)

def _map_at_k(preds_dict, gt_dict, k=10):
    APs=[]
    for ad, df in preds_dict.items():
        if ad not in gt_dict: continue
        true=set(gt_dict[ad]); 
        if not true: continue
        ranked = df["mda_idx"].astype(int).tolist()[:k]
        hits=cum_prec=0
        for i,m in enumerate(ranked, start=1):
            if m in true:
                hits+=1; cum_prec += hits/i
        APs.append(cum_prec/min(len(true),k) if hits>0 else 0.0)
    return float(np.mean(APs)) if APs else 0.0

def _auc_flat(preds_dict, gt_pairs_dict, score_col="score"):
    y_true, y_score = [], []
    for ad, df in preds_dict.items():
        true_mdas = set(gt_pairs_dict.get(ad, []))
        for _, r in df.iterrows():
            y_true.append(1 if int(r["mda_idx"]) in true_mdas else 0)
            y_score.append(float(r[score_col]))
    if len(set(y_true))<2: return 0.5
    try: return float(roc_auc_score(y_true, y_score))
    except Exception: return 0.5

def evaluate_all(preds_with_counts: Dict[int, pd.DataFrame], tgt: pd.DataFrame, k=10):
    gt_pairs = tgt.groupby("ads_idx")["mda_idx"].apply(lambda s: list(pd.Series(s).dropna().astype(int).unique())).to_dict()
    prec, rec, hit = _precision_recall_hit_at_k(preds_with_counts, gt_pairs, k=k)
    mapk = _map_at_k(preds_with_counts, gt_pairs, k=k)
    auc_rank = _auc_flat(preds_with_counts, gt_pairs, score_col="score")
    auc_reg  = _auc_flat(preds_with_counts, gt_pairs, score_col="yhat_turn")
    return {f"precision@{k}":prec, f"recall@{k}":rec, f"map@{k}":mapk,
            f"hit_rate@{k}":hit, "auc_ranker":auc_rank, "auc_regressor":auc_reg}

# -------------------------------
# 9) 편의
# -------------------------------
def get_expected_conversions_for_ad(preds_with_counts: Dict[int, pd.DataFrame],
                                    ad_id: int, sort_by="yhat_turn", top=20) -> pd.DataFrame:
    df = preds_with_counts.get(int(ad_id))
    if df is None or df.empty:
        return pd.DataFrame(columns=["mda_idx","score","yhat_turn"])
    sort_by = "yhat_turn" if sort_by not in ("yhat_turn","score") else sort_by
    out = df.sort_values(sort_by, ascending=False).copy()
    return out.head(top) if top is not None else out

# =========================================================
# ==============   메인 플로우 (예시)   ====================
# =========================================================
# 요구: ads_time, ads_list, ads_segment(ads_size, domain), media_portfolio(옵션)

# (A) 윈도우
obs, tgt, start, end, cut = split_obs_tgt_by_dates(
    ads_time, obs_start="2025-07-25", tgt_start="2025-08-20"
)
print(f"[Window] OBS: {start.date()} → {cut.date()}  |  TGT: {(cut+pd.Timedelta(days=1)).date()} → {end.date()}")

# (B) ads_list 확장 (ads_size, domain 병합)
ads_list_ext = ads_list.merge(
    ads_segment[["ads_idx","ads_size","domain"]].rename(columns={"domain":"ads_domain"}),
    on="ads_idx", how="left"
)

# (C) LARGE만
ads_list_large = ads_list_ext[ads_list_ext["ads_size"].astype(str).str.strip().str.upper()=="LARGE"].copy()
large_ids = set(ads_list_large["ads_idx"].astype(int))
tgt_large  = tgt[tgt["ads_idx"].astype(int).isin(large_ids)].copy()

# (D) 학습 데이터
train_df, actx = prepare_training_attr_only(
    obs, tgt_large, ads_list_large,
    topC=10, add_random=2, cat_topM=5,
    min_active_clk=200, min_active_conv=20,
    max_train_ads=20000, min_pos_in_tgt=1,
    media_portfolio=None
)
print("train_df size:", len(train_df))

# (E) 학습 (랭커 + 클릭 + CVR)
train_df_ds = downsample_negatives_per_ad(train_df, ratio=4)
ranker, feat_cols   = train_attr_ranker(train_df_ds)
click_reg, click_md = train_click_regressor(train_df_ds, feat_cols, tweedie_p=1.1)
cvr_reg, cvr_md     = train_cvr_regressor(train_df_ds, feat_cols)
print("feat_cols used:", feat_cols)

# (F) 예측 & 평가
preds_with_counts = predict_all_mda_with_counts_batched(
    ranker, click_reg, cvr_reg, feat_cols, actx, ads_list_large,
    K=20, batch_size=5000, max_predict_ads=20000, media_portfolio=None
)
metrics_k5  = evaluate_all(preds_with_counts, tgt_large, k=5)
metrics_k10 = evaluate_all(preds_with_counts, tgt_large, k=10)
print("Eval@5:", metrics_k5)
print("Eval@10:", metrics_k10)

# (G) 예: 특정 광고 top-5 (예상 전환수 기준)
# ad_id = 446406
# top5 = get_expected_conversions_for_ad(preds_with_counts, ad_id, sort_by="yhat_turn", top=5)
# print(top5[["mda_idx","yhat_turn","score"]])

[Window] OBS: 2025-07-25 → 2025-08-19  |  TGT: 2025-08-20 → 2025-08-25
[Candidates] pairs=10,093 | ads=601 | active_mda=148 | topC=10, rnd=2, cat_topM=5, per_ad≤20
train_df size: 10093
feat_cols used: ['mda_clk_global', 'mda_conv_global', 'mda_cvr_global', 'mda_pop_norm', 'cat_cvr', 'cat_share', 'price_reward_log', 'price_contract_log', 'price_ratio', 'dom_cvr', 'dom_share', 'mda_day_ratio', 'mda_weekend_ratio', 'adv_cvr_global', 'adv_pop_norm', 'mda_size', 'active_ratio', 'day_ratio', 'weekend_ratio']
[Predict+Count] processed ads 2643/2643
Eval@5: {'precision@5': 0.3694968553459119, 'recall@5': 0.8075908935578746, 'map@5': 0.7100952131376659, 'hit_rate@5': 0.9685534591194969, 'auc_ranker': 0.8482440594528651, 'auc_regressor': 0.8203499547386209}
Eval@10: {'precision@10': 0.22594339622641513, 'recall@10': 0.8905724298412978, 'map@10': 0.7350510823069036, 'hit_rate@10': 0.9905660377358491, 'auc_ranker': 0.8482440594528651, 'auc_regressor': 0.8203499547386209}

In [ ]:
# 예: 학습 후 전체 검증(TGT) 구간 평가
metrics_k5  = evaluate_all(preds_with_counts, tgt_large, k=5)
metrics_k10 = evaluate_all(preds_with_counts, tgt_large, k=10)

print("[Eval@5]")
print("  precision@5 :", metrics_k5["precision@5"])
print("  recall@5    :", metrics_k5["recall@5"])
print("  map@5       :", metrics_k5["map@5"])
print("  auc_ranker  :", metrics_k5["auc_ranker"])
print("  auc_regress :", metrics_k5["auc_regressor"])

print("\n[Eval@10]")
print("  precision@10:", metrics_k10["precision@10"])
print("  recall@10   :", metrics_k10["recall@10"])
print("  map@10      :", metrics_k10["map@10"])
print("  auc_ranker  :", metrics_k10["auc_ranker"])
print("  auc_regress :", metrics_k10["auc_regressor"])

ma / rmse 예측 성과

[Eval@5]
  precision@5 : 0.3694968553459119
  recall@5    : 0.8075908935578746
  map@5       : 0.7100952131376659
  auc_ranker  : 0.8482440594528651
  auc_regress : 0.8203499547386209

[Eval@10]
  precision@10: 0.22594339622641513
  recall@10   : 0.8905724298412978
  map@10      : 0.7350510823069036
  auc_ranker  : 0.8482440594528651
  auc_regress : 0.8203499547386209

In [157]:
# TGT 구간 확인 (2025-08-20 ~ 2025-08-25)
tgt_period = tgt[
    (tgt["date"] >= pd.to_datetime("2025-08-20")) &
    (tgt["date"] <= pd.to_datetime("2025-08-25"))
].copy()

# 광고별 집계 (전환 합계 포함)
tgt_ads_summary = (
    tgt_period.groupby("ads_idx", as_index=False)
    .agg(clicks=("rpt_time_clk", "sum"),
         turns=("rpt_time_turn", "sum"),
         mdas=("mda_idx", "nunique"))
    .sort_values("turns", ascending=False)
)

# LARGE 광고 ID 집합
large_ids = set(ads_list_large["ads_idx"].astype(int))

# TGT 요약에서 LARGE만 필터링
tgt_ads_summary_large = tgt_ads_summary[
    tgt_ads_summary["ads_idx"].astype(int).isin(large_ids)
].copy()

print("=== TGT 기간 광고별 요약 (LARGE만, 2025-08-20 ~ 2025-08-25) ===")
print(tgt_ads_summary_large.head(20))

=== TGT 기간 광고별 요약 (LARGE만, 2025-08-20 ~ 2025-08-25) ===
      ads_idx  clicks  turns  mdas
920    443285    1951   1146     7
775    439163    2357    659     6
282    131204     873    601     7
1240   444946    1788    593     6
2180   446406     405    322     5
128     28051    1770    298     3
2040   446164     387    293     2
2320   446698     371    268     3
1956   446053     329    261     3
1592   445562     429    233     7
2301   446671     430    232     6
1508   445452     375    227     2
2114   446285     396    216     5
2129   446300     287    213     5
483    334540    1014    206    10
484    334542     759    206     9
485    334543     708    206    10
1965   446070     302    205     6
1410   445333     250    204     2
2187   446418     243    204     2

In [ ]:
# (G) 예: 특정 광고 top-5 (예상 전환수 기준)
ad_id = 22232
top5 = get_expected_conversions_for_ad(preds_with_counts, ad_id, sort_by="yhat_turn", top=5)
print(top5[["mda_idx","yhat_turn","score"]])

   mda_idx   yhat_turn     score
0       22  599.372128  4.871929
1      496  480.184964  3.437047
3      270   42.537119  1.355760
6       54   25.013968 -0.613628
8      761    8.715921 -1.501533

In [159]:
def get_expected_vs_actual_for_ad(preds_with_counts: Dict[int, pd.DataFrame],
                                  tgt: pd.DataFrame,
                                  ad_id: int,
                                  sort_by: str = "yhat_turn",
                                  top: Optional[int] = 20) -> pd.DataFrame:
    """
    특정 광고의 매체사별 Top-K 추천 결과에서
    예측 전환수(yhat_turn), 점수(score), 실제 전환수(tgt_turn)를 같이 반환
    """
    df_pred = preds_with_counts.get(int(ad_id))
    if df_pred is None or df_pred.empty:
        return pd.DataFrame(columns=["mda_idx","score","yhat_turn","tgt_turn"])

    # 실제 전환수 집계 (TGT 기준)
    tgt_g = (tgt[tgt["ads_idx"]==ad_id]
               .groupby("mda_idx", as_index=False)
               .agg(tgt_turn=("rpt_time_turn","sum")))

    df = df_pred.merge(tgt_g, on="mda_idx", how="left").fillna({"tgt_turn":0.0})

    sort_by = "yhat_turn" if sort_by not in ("yhat_turn","score") else sort_by
    df = df.sort_values(sort_by, ascending=False)
    return df.head(top) if top is not None else df

In [177]:
ad_id = 443285
top5_cmp = get_expected_vs_actual_for_ad(
    preds_with_counts, tgt_large, ad_id=ad_id,
    sort_by="yhat_turn", top=10
)

print(f"=== Ad {ad_id} 추천 매체사 Top-10 (예상 전환수 vs 실제 전환수) ===")
print(top5_cmp[["mda_idx","yhat_turn","tgt_turn","score"]])

=== Ad 443285 추천 매체사 Top-10 (예상 전환수 vs 실제 전환수) ===
    mda_idx   yhat_turn  tgt_turn     score
0        22  599.372128     453.0  4.871929
1       496  480.184964     398.0  3.437047
3       270   42.537119      59.0  1.355760
6        54   25.013968      26.0 -0.613628
8       761    8.715921     199.0 -1.501533
4       246    6.112913       6.0 -0.202180
11      645    4.702746       5.0 -2.295956
7       848    2.789174       0.0 -1.058276
2       371    1.368531       0.0  2.500271
5       290    0.530539       0.0 -0.294814

In [166]:
# 0) 전제: 아래 객체들이 이미 준비되어 있어야 함
#   - actx: OBS로 만든 컨텍스트(build_attr_context 결과)
#   - ranker, click_reg, cvr_reg, feat_cols: 직전에 학습한 모델들
#   - predict_all_mda_with_counts_batched, get_expected_conversions_for_ad: 이전 정의 함수

# 1) 신규 광고 메타 준비
#   (ads_new 예시 컬럼: ['ads_idx','ads_type','ads_category','ads_name','ads_os_type',
#                      'ads_contract_price','ads_media_price','ads_reward_price',
#                      'ads_rejoin_type','domain'])
ads_new_meta = ads_new.copy()

# 우리 파이프라인이 기대하는 컬럼명으로 맞추기
ads_new_meta = ads_new_meta.rename(columns={
    "domain": "ads_domain"
})

# 숫자형 정리(가격)
for c in ["ads_contract_price", "ads_reward_price"]:
    if c in ads_new_meta.columns:
        ads_new_meta[c] = pd.to_numeric(ads_new_meta[c], errors="coerce").fillna(0)

# 카테고리/도메인 정규화(낙관적 기본값 처리)
ads_new_meta["ads_category"] = (
    ads_new_meta["ads_category"]
    .astype(str).str.strip().str.lower()
    .replace({"<na>":"__na__", "nan":"__na__", "none":"__na__", "nat":"__na__"})
)
ads_new_meta["ads_domain"] = (
    ads_new_meta["ads_domain"]
    .astype(str).str.strip().str.lower()
    .replace({"<na>":"__na__", "nan":"__na__", "none":"__na__", "nat":"__na__"})
)

# (선택) adv_idx 있으면 가져가고, 없으면 0으로 채움
if "adv_idx" not in ads_new_meta.columns:
    ads_new_meta["adv_idx"] = 0

# 예측에 필요한 최소 컬럼만 남겨도 됨
ads_new_meta = ads_new_meta[[
    "ads_idx", "ads_category", "ads_domain",
    "ads_contract_price", "ads_reward_price", "adv_idx"
]]

# 2) 예측 실행: 신규 광고만 넣어서 예측(학습된 actx와 매체 통계 사용)
preds_new = predict_all_mda_with_counts_batched(
    ranker=ranker,
    click_reg=click_reg,
    cvr_reg=cvr_reg,
    feat_cols=feat_cols,
    actx=actx,                       # OBS에서 만든 컨텍스트(그대로 사용)
    ads_list_with_domain=ads_new_meta,  # ★ 신규 광고만 투입
    K=20,
    batch_size=5000,
    max_predict_ads=None,            # 제한 없이
    media_portfolio=None
)

# 3) 광고별 Top-5 결과 보기 (예상 전환수 기준)
for ad in ads_new_meta["ads_idx"].astype(int).tolist():
    top5 = get_expected_conversions_for_ad(preds_new, ad_id=ad, sort_by="yhat_turn", top=5)
    print(f"\n=== 신규 광고 {ad} 추천 매체사 Top-5 (예상 전환수 기준) ===")
    if top5.empty:
        print("(예측 없음: 후보 매체가 없거나 컨텍스트가 비어있을 수 있음)")
    else:
        print(top5[["mda_idx","yhat_turn","score"]])

[Predict+Count] processed ads 8/8

=== 신규 광고 500000 추천 매체사 Top-5 (예상 전환수 기준) ===
    mda_idx  yhat_turn     score
1       634   0.004583 -3.316352
0       270   0.001140 -3.065564
15      496   0.000612 -4.195602
3       980   0.000415 -3.558058
14      851   0.000338 -4.193136

=== 신규 광고 500001 추천 매체사 Top-5 (예상 전환수 기준) ===
   mda_idx  yhat_turn     score
3      761  24.020499  1.837828
0      563   2.910245  6.150732
1      371   1.595841  3.223704
2      562   0.406377  2.443147
7      645   0.190282 -1.389569

=== 신규 광고 500002 추천 매체사 Top-5 (예상 전환수 기준) ===
    mda_idx  yhat_turn     score
0       761   2.477358  1.337013
3       371   1.825052  0.683859
12      291   1.000618 -0.887503
4       790   0.613124  0.250106
8       645   0.434980 -0.195832

=== 신규 광고 500003 추천 매체사 Top-5 (예상 전환수 기준) ===
   mda_idx  yhat_turn     score
0       22   1.500759  3.566391
2      398   0.795406  0.905209
1       14   0.617327  1.549063
5      401   0.112794  0.487981
7       12   0.017736 -0.347829

=== 신규 광고 500004 추천 매체사 Top-5 (예상 전환수 기준) ===
    mda_idx  yhat_turn     score
0        22   5.229129  1.150712
5       270   1.407962 -0.990698
10       12   0.495430 -1.364466
1       371   0.178250  1.011943
7        54   0.046876 -1.046616

=== 신규 광고 500005 추천 매체사 Top-5 (예상 전환수 기준) ===
    mda_idx  yhat_turn     score
0        58   2.953673  3.611618
18      817   0.031842 -3.289920
5       270   0.024482  0.032286
9       371   0.012757 -2.318844
8        22   0.007978 -1.550089

=== 신규 광고 500006 추천 매체사 Top-5 (예상 전환수 기준) ===
    mda_idx  yhat_turn     score
10      563   0.293834  0.333455
1       540   0.118665  2.492692
0        14   0.090166  2.626833
17      634   0.086051 -1.232609
7       643   0.078031  0.921803

=== 신규 광고 500007 추천 매체사 Top-5 (예상 전환수 기준) ===
    mda_idx  yhat_turn     score
3       540   0.322442  1.576387
5       563   0.170638  0.935461
14      634   0.113355 -1.103597
0        14   0.099294  2.418559
8       375   0.079696  0.692902

In [161]:
ads_new_meta = ads_new.copy()
ads_new_meta = ads_new_meta.rename(columns={"domain": "ads_domain"})

# 가격 숫자화
for c in ["ads_contract_price", "ads_reward_price"]:
    ads_new_meta[c] = pd.to_numeric(ads_new_meta.get(c, 0), errors="coerce").fillna(0)

# 카테고리/도메인 정규화
ads_new_meta["ads_category"] = (
    ads_new_meta.get("ads_category","__na__")
    .astype(str).str.strip().str.lower()
    .replace({"<na>":"__na__","nan":"__na__","none":"__na__","nat":"__na__"})
)
ads_new_meta["ads_domain"] = (
    ads_new_meta.get("ads_domain","__na__")
    .astype(str).str.strip().str.lower()
    .replace({"<na>":"__na__","nan":"__na__","none":"__na__","nat":"__na__"})
)

# adv_idx/ads_name 기본값
ads_new_meta["adv_idx"]  = ads_new_meta.get("adv_idx", 0)
ads_new_meta["ads_name"] = ads_new_meta.get("ads_name", "").astype(str)

# 예측에 필요한 컬럼(ads_name 포함)만 유지
ads_new_meta = ads_new_meta[[
    "ads_idx","ads_category","ads_domain",
    "ads_contract_price","ads_reward_price","adv_idx","ads_name"  # ← 포함!
]].drop_duplicates("ads_idx")

In [162]:
preds_new = predict_all_mda_with_counts_batched(
    ranker, click_reg, cvr_reg, feat_cols, actx,
    ads_list_with_domain=ads_new_meta,
    K=20, batch_size=5000, max_predict_ads=None, media_portfolio=None
)

for ad in ads_new_meta["ads_idx"].astype(int):
    top5 = get_expected_conversions_for_ad(preds_new, ad, sort_by="yhat_turn", top=5)
    print(f"\n=== 신규 광고 {ad} 추천 매체사 Top-5 (yhat_turn 기준) ===")
    print("[EMPTY] 이 광고는 예측 결과가 없습니다." if top5.empty else top5[["mda_idx","yhat_turn","score"]])

[Predict+Count] processed ads 8/8

=== 신규 광고 500000 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
4       634   0.183193 -3.947494
6       344   0.006734 -4.325198
0       270   0.005709 -3.393299
2        22   0.001796 -3.927919
12      563   0.001787 -4.617729

=== 신규 광고 500001 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
0      563   2.834244  6.694795
2      761   2.811726  2.565953
8      645   0.531498 -1.693402
9      790   0.088987 -2.352940
1      371   0.055422  3.215654

=== 신규 광고 500002 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
2      371   4.473921  1.458189
0      270   3.706649  1.740088
1      761   1.521165  1.512758
4      817   0.704295  0.300374
7      645   0.665452 -0.615812

=== 신규 광고 500003 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
1        14  16.987511  2.734970
0        22   5.134284  3.898190
2       398   4.678629  2.230773
5       401   1.032783  0.638468
16      634   0.113939 -2.401888

=== 신규 광고 500004 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
6      270   1.055981 -0.885016
2      371   0.341852  0.208268
1       22   0.286013  0.794686
5       54   0.182659 -0.496071
4      667   0.180485 -0.393183

=== 신규 광고 500005 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
0        58   1.134142  1.515557
14      817   0.048997 -2.982963
17      563   0.022661 -3.531883
4       270   0.017671 -0.042961
7        22   0.004264 -1.622501

=== 신규 광고 500006 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
0       540   0.256611  1.980724
3        58   0.097717  1.877215
1        14   0.046179  1.976704
2       270   0.044372  1.914353
10      375   0.032197  0.356102

=== 신규 광고 500007 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
2       540   0.586280  1.964520
1       270   0.349315  2.055460
4        58   0.316887  1.747618
10      375   0.211759  0.320593
0        14   0.175377  2.373798

In [163]:
ㅋㅋㅋㅋ

NameError: name 'ᄏᄏᄏᄏ' is not defined

In [ ]:
# =========================================================
# 신규 광고(ads_new) → 매체사 추천 Top-K (yhat_turn 기준)
#  - ads_name 포함 (이름 피처는 predict 함수 내부에서 자동 부착됨)
#  - (옵션) easy_coldstart_blend_v2로 신규 폭주 완화
# 전제: actx, ranker, click_reg, cvr_reg, feat_cols, 
#       predict_all_mda_with_counts_batched, get_expected_conversions_for_ad,
#       _attach_name_features / build_name_features 포함된 최신 코드가 이미 로드되어 있음
# =========================================================

# 0) (선택) 블렌딩 함수가 없다면 정의
try:
    easy_coldstart_blend_v2
except NameError:
    import numpy as np
    def easy_coldstart_blend_v2(df, actx, tgt=None, cvr_cap=0.12, w=0.7, click_budget=None):
        if df is None or df.empty: return df
        mda_all = actx["mda_all"].copy()
        glb_clk = float(mda_all["mda_clk_global"].sum())
        glb_conv = float(mda_all["mda_conv_global"].sum())
        glb_cvr = (glb_conv / glb_clk) if glb_clk > 0 else 0.0
        glb_cvr = min(glb_cvr, cvr_cap)
        if click_budget is None:
            if (tgt is not None) and ("rpt_time_clk" in tgt.columns):
                per_ad_clk = tgt.groupby("ads_idx")["rpt_time_clk"].sum()
                click_budget = max(30.0, float(per_ad_clk.median()) if len(per_ad_clk) else 50.0)
            else:
                click_budget = 50.0
        base_clk = df["mda_clk_global"].astype(float).clip(lower=0.0)
        share = base_clk / max(1.0, base_clk.sum())
        clk_prior = share * click_budget
        turn_prior = clk_prior * glb_cvr
        out = df.copy()
        turn_model = out["yhat_turn"].astype(float).clip(lower=0.0)
        out["yhat_turn"] = w*turn_model + (1.0 - w)*turn_prior
        if turn_model.notnull().sum() > 0 and (turn_model > 0).any():
            cap_val = max(1.0, float(np.percentile(turn_model[turn_model>0], 99)) * 3.0)
            out["yhat_turn"] = np.minimum(out["yhat_turn"], cap_val)
        return out

# 1) 신규 광고 메타 준비 (ads_name 포함!)
ads_new_meta = ads_new.copy()
ads_new_meta = ads_new_meta.rename(columns={"domain": "ads_domain"})

# 숫자형 정리
for c in ["ads_contract_price", "ads_reward_price"]:
    if c not in ads_new_meta.columns:
        ads_new_meta[c] = 0
    ads_new_meta[c] = pd.to_numeric(ads_new_meta[c], errors="coerce").fillna(0)

# 카테고리/도메인 정규화
ads_new_meta["ads_category"] = (
    ads_new_meta.get("ads_category","__na__")
    .astype(str).str.strip().str.lower()
    .replace({"<na>":"__na__", "nan":"__na__", "none":"__na__", "nat":"__na__"})
)
ads_new_meta["ads_domain"] = (
    ads_new_meta.get("ads_domain","__na__")
    .astype(str).str.strip().str.lower()
    .replace({"<na>":"__na__", "nan":"__na__", "none":"__na__", "nat":"__na__"})
)

# adv_idx 기본값
if "adv_idx" not in ads_new_meta.columns:
    ads_new_meta["adv_idx"] = 0

# 예측에 필요한 최소 컬럼(★ ads_name 포함)
cols_keep = [
    "ads_idx", "ads_category", "ads_domain",
    "ads_contract_price", "ads_reward_price", "adv_idx",
]
if "ads_name" in ads_new_meta.columns:
    cols_keep.append("ads_name")
ads_new_meta = ads_new_meta[cols_keep].drop_duplicates("ads_idx").copy()

# 2) 예측 실행 (신규 광고만 투입)
preds_new = predict_all_mda_with_counts_batched(
    ranker=ranker,
    click_reg=click_reg,
    cvr_reg=cvr_reg,
    feat_cols=feat_cols,
    actx=actx,
    ads_list_with_domain=ads_new_meta,  # 신규 광고 배치
    K=20,
    batch_size=5000,
    max_predict_ads=None,
    media_portfolio=None
)

# 2-1) (선택) 콜드스타트 블렌딩 적용
APPLY_BLEND = True
if APPLY_BLEND:
    for ad in ads_new_meta["ads_idx"].astype(int):
        preds_new[ad] = easy_coldstart_blend_v2(
            preds_new.get(ad), actx, tgt=tgt,  # tgt 있으면 전달 (없어도 동작)
            cvr_cap=0.10,   # 보수적 컷
            w=0.7,          # 모델:prior = 70:30
            click_budget=None
        )

# 3) 광고별 Top-5 출력 (yhat_turn 기준)
def _show_new_ads_topk(preds_dict, ad_ids, k=5):
    for ad in list(map(int, ad_ids)):
        topk = get_expected_conversions_for_ad(preds_dict, ad_id=ad, sort_by="yhat_turn", top=k)
        print(f"\n=== 신규 광고 {ad} 추천 매체사 Top-{k} (yhat_turn 기준) ===")
        if topk.empty:
            print("[EMPTY] 이 광고는 예측 결과가 없습니다.")
        else:
            cols = ["mda_idx","yhat_turn","score"]
            print(topk[cols])

_show_new_ads_topk(preds_new, ads_new_meta["ads_idx"].tolist(), k=5)

[Predict+Count] processed ads 8/8

=== 신규 광고 500000 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
12      563   0.334154 -4.617729
4       634   0.131704 -3.947494
2        22   0.051424 -3.927919
11      761   0.045003 -4.553074
0       270   0.042408 -3.393299

=== 신규 광고 500001 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
0      563   2.379667  6.694795
2      761   2.021672  2.565953
8      645   0.372767 -1.693402
4      270   0.070684  0.118599
9      790   0.063358 -2.352940

=== 신규 광고 500002 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
2      371   3.155706  1.458189
0      270   2.641406  1.740088
1      761   1.119561  1.512758
4      817   0.493860  0.300374
7      645   0.466553 -0.615812

=== 신규 광고 500003 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
1        14  11.929184  2.734970
0        22   3.628440  3.898190
2       398   3.278044  2.230773
5       401   0.723096  0.638468
18      563   0.240002 -2.983457

=== 신규 광고 500004 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
6      270   0.784127 -0.885016
2      371   0.262329  0.208268
1       22   0.258902  0.794686
7       12   0.202928 -2.074746
4      667   0.155990 -0.393183

=== 신규 광고 500005 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
0        58   0.805988  1.515557
16      539   0.517578 -3.135771
14      817   0.034332 -2.982963
17      563   0.031962 -3.531883
4       270   0.014227 -0.042961

=== 신규 광고 500006 추천 매체사 Top-5 (yhat_turn 기준) ===
    mda_idx  yhat_turn     score
19      539   0.531177 -1.535902
0       540   0.179987  1.980724
3        58   0.080467  1.877215
1        14   0.034992  1.976704
2       270   0.032915  1.914353

=== 신규 광고 500007 추천 매체사 Top-5 (yhat_turn 기준) ===
   mda_idx  yhat_turn     score
2      540   0.415150  1.964520
4       58   0.381346  1.747618
3      563   0.313355  1.839050
1      270   0.269035  2.055460
0       14   0.158020  2.373798

In [ ]:
ㅋㅋㅋㅋㅋㅋㅋ

NameError: name 'ᄏᄏᄏᄏᄏᄏᄏ' is not defined

In [ ]:
def _per_ad_labels_scores(preds_with_counts: dict, tgt_df: pd.DataFrame, score_col: str = "score"):
    """
    각 ads_idx마다 Top-K 예측(rows)에서의 (y_true, y_score) 배열을 뽑아줌.
    y_true는 해당 mda_idx가 GT에 포함되면 1, 아니면 0.
    """
    gt_pairs = (
        tgt_df.groupby("ads_idx")["mda_idx"]
        .apply(lambda s: list(pd.Series(s).dropna().astype(int).unique()))
        .to_dict()
    )

    out = {}
    for ad, df in preds_with_counts.items():
        true_mdas = set(gt_pairs.get(ad, []))
        if len(df) == 0:
            continue
        y_true = (df["mda_idx"].astype(int).isin(true_mdas)).astype(int).values
        y_score = df[score_col].astype(float).values
        # AUC 계산이 불가능한 올-양성/올-음성 케이스는 건너뜀
        if len(np.unique(y_true)) < 2:
            continue
        out[ad] = (y_true, y_score)
    return out

def summarize_auc(preds_with_counts: dict, tgt_df: pd.DataFrame, score_col: str = "score"):
    """
    per-ad ROC AUC / PR-AUC(average precision) 분포를 요약.
    score_col: "score"(랭커) 또는 "yhat_turn"(회귀)
    """
    per_ad = _per_ad_labels_scores(preds_with_counts, tgt_df, score_col=score_col)
    aucs, ap_aucs = [], []
    for ad, (y_true, y_score) in per_ad.items():
        try:
            aucs.append(roc_auc_score(y_true, y_score))
        except Exception:
            pass
        try:
            ap_aucs.append(average_precision_score(y_true, y_score))
        except Exception:
            pass

    def _stats(x):
        if not x:
            return {"count": 0, "mean": np.nan, "median": np.nan, "p25": np.nan, "p75": np.nan}
        x = np.array(x, float)
        return {
            "count": int(len(x)),
            "mean": float(np.mean(x)),
            "median": float(np.median(x)),
            "p25": float(np.percentile(x, 25)),
            "p75": float(np.percentile(x, 75)),
        }

    return {
        "per_ad_roc_auc": _stats(aucs),
        "per_ad_pr_auc": _stats(ap_aucs),
    }

# ======================
# 사용: (LARGE 기준이라면 tgt_large 사용)
# ======================

auc_ranker_detail   = summarize_auc(preds_with_counts, tgt_large, score_col="score")
auc_regressor_detail= summarize_auc(preds_with_counts, tgt_large, score_col="yhat_turn")

print("\n=== AUC (전체) @k=5 ===")
print(metrics)  # evaluate_all(...) 출력값에 auc_ranker/auc_regressor 포함됨

print("\n=== Per-Ad ROC-AUC / PR-AUC 분포 요약 (Ranker: score) ===")
print(auc_ranker_detail)

print("\n=== Per-Ad ROC-AUC / PR-AUC 분포 요약 (Regressor: yhat_turn) ===")
print(auc_regressor_detail)

=== AUC (전체) @k=5 ===
{'precision@5': 0.3594339622641509, 'recall@5': 0.7775031964890455, 'map@5': 0.6857106044723968, 'hit_rate@5': 0.9669811320754716, 'auc_ranker': 0.846276147728455, 'auc_regressor': 0.8298741516318361}

=== Per-Ad ROC-AUC / PR-AUC 분포 요약 (Ranker: score) ===
{'per_ad_roc_auc': {'count': 635, 'mean': 0.8930818655140802, 'median': 0.9607843137254902, 'p25': 0.8770604395604396, 'p75': 1.0}, 'per_ad_pr_auc': {'count': 635, 'mean': 0.7717749111304111, 'median': 0.8333333333333333, 'p25': 0.6875, 'p75': 1.0}}

=== Per-Ad ROC-AUC / PR-AUC 분포 요약 (Regressor: yhat_turn) ===
{'per_ad_roc_auc': {'count': 635, 'mean': 0.9191186645924249, 'median': 1.0, 'p25': 0.9217218137254901, 'p75': 1.0}, 'per_ad_pr_auc': {'count': 635, 'mean': 0.8494606869185638, 'median': 1.0, 'p25': 0.8048611111111111, 'p75': 1.0}}

In [ ]:
ad_id = 12345
print(get_expected_conversions_for_ad(preds_with_counts, ad_id, sort_by="yhat_turn", top=20))

Empty DataFrame
Columns: [mda_idx, score, yhat_turn]
Index: []

In [ ]:
# ======================================
# Top-10 정/오예측 비교 분석 유틸
# ======================================

def build_gt_pairs(tgt_df: pd.DataFrame) -> dict:
    # ads_idx별 정답 mda_idx 집합
    return (
        tgt_df.groupby("ads_idx")["mda_idx"]
        .apply(lambda s: list(pd.Series(s).dropna().astype(int).unique()))
        .to_dict()
    )

def make_cmp_df(preds_with_counts: dict, gt_pairs: dict, topk: int = 10) -> pd.DataFrame:
    records = []
    for ad, df in preds_with_counts.items():
        if ad not in gt_pairs:
            continue
        true_set = set(gt_pairs[ad])
        # 상위 K만 평가
        for pos, row in enumerate(df.head(topk).itertuples(index=False), start=1):
            mda = int(row.mda_idx)
            score = float(row.score)
            yhat_turn = float(row.yhat_turn)
            is_correct = 1 if mda in true_set else 0
            records.append({
                "ads_idx": int(ad),
                "mda_idx": mda,
                "rank": pos,
                "score": score,
                "yhat_turn": yhat_turn,
                "is_correct": is_correct
            })
    return pd.DataFrame.from_records(records)

def compare_correct_vs_incorrect(cmp_df: pd.DataFrame,
                                 actx: dict,
                                 ads_list_large: pd.DataFrame,
                                 media_portfolio: pd.DataFrame | None = None) -> dict:
    out = {}

    # ---- 메타 병합 (매체 / 광고)
    # mda 전역 특성
    mda_all = actx["mda_all"][["mda_idx","mda_clk_global","mda_conv_global","mda_cvr_global","mda_pop_norm"]].copy()
    mda_all["mda_idx"] = mda_all["mda_idx"].astype(int)
    cmpm = cmp_df.merge(mda_all, on="mda_idx", how="left")

    # 광고 메타(카테고리/가격)
    ad_meta_cols = [c for c in ["ads_idx","ads_category","ads_reward_price","ads_contract_price"] if c in ads_list_large.columns]
    if "ads_category" in ad_meta_cols:
        ad_meta = ads_list_large[ad_meta_cols].drop_duplicates("ads_idx").copy()
        cmpm = cmpm.merge(ad_meta, on="ads_idx", how="left")

    # (선택) media_portfolio 병합
    if media_portfolio is not None:
        cols = [c for c in ["mda_idx","mda_size","active_ratio","day_ratio","weekend_ratio"] if c in media_portfolio.columns]
        if "mda_idx" in cols:
            cmpm = cmpm.merge(media_portfolio[cols], on="mda_idx", how="left")

    out["cmp_df"] = cmpm

    # ---- 전체 요약
    total = len(cmpm)
    correct = int(cmpm["is_correct"].sum())
    prec_at_k = correct / total if total else 0.0
    out["summary"] = {
        "samples": total,
        "correct": correct,
        "incorrect": total - correct,
        "precision_empirical": prec_at_k
    }

    # ---- 분포 비교: score / yhat_turn / mda 지표
    num_cols = [c for c in ["score","yhat_turn","mda_cvr_global","mda_pop_norm","mda_clk_global","mda_conv_global",
                            "mda_size","active_ratio","day_ratio","weekend_ratio"]
                if c in cmpm.columns]
    out["by_label_describe"] = cmpm.groupby("is_correct")[num_cols].describe().transpose()

    # ---- 순위 포지션별 정답률
    out["rank_position_accuracy"] = (
        cmpm.groupby("rank")["is_correct"].mean().rename("accuracy_by_rank").to_frame()
    )

    # ---- 카테고리별 정/오예측 비율
    if "ads_category" in cmpm.columns:
        out["category_correct_rate"] = (
            cmpm.groupby("ads_category")["is_correct"].mean().sort_values(ascending=False).to_frame("correct_rate")
        )
        out["category_counts"] = (
            cmpm.groupby(["ads_category","is_correct"]).size().unstack(fill_value=0)
            .rename(columns={0:"incorrect",1:"correct"}).sort_values("correct", ascending=False)
        )

    # ---- 매체사별 오예측 특성 (False Positive가 많은 mda)
    mda_stats = cmpm.groupby("mda_idx").agg(
        total=("is_correct","size"),
        correct=("is_correct","sum"),
        score_mean=("score","mean"),
        yhat_mean=("yhat_turn","mean"),
        mda_cvr_global=("mda_cvr_global","mean"),
        mda_pop_norm=("mda_pop_norm","mean")
    )
    mda_stats["incorrect"] = mda_stats["total"] - mda_stats["correct"]
    mda_stats["correct_rate"] = mda_stats["correct"] / mda_stats["total"]
    out["mda_false_positive_hotlist"] = (
        mda_stats.sort_values(["incorrect","correct_rate"], ascending=[False, True]).head(30)
    )

    # ---- 광고별 커버리지 (Top-10에 정답 존재 여부)
    ad_hit = cmpm.groupby("ads_idx")["is_correct"].max().rename("has_any_correct_in_top10")
    out["ad_hit_rate"] = {
        "ads_with_any_correct_top10": int(ad_hit.sum()),
        "ads_total": int(ad_hit.size),
        "rate": float(ad_hit.mean()) if ad_hit.size else 0.0
    }

    # ---- 정/오예측 평균 차이표 (간단한 mean gap)
    def _mean_gap(col):
        if col not in cmpm.columns: return None
        g = cmpm.groupby("is_correct")[col].mean()
        return pd.Series({
            "correct_mean": g.get(1, np.nan),
            "incorrect_mean": g.get(0, np.nan),
            "gap(correct - incorrect)": g.get(1, np.nan) - g.get(0, np.nan)
        })
    key_cols = [c for c in ["score","yhat_turn","mda_cvr_global","mda_pop_norm","mda_clk_global","mda_conv_global",
                            "mda_size","active_ratio","day_ratio","weekend_ratio"]
                if c in cmpm.columns]
    gap_tbl = pd.concat({c: _mean_gap(c) for c in key_cols}, axis=1).T.sort_values("gap(correct - incorrect)", ascending=False)
    out["mean_gaps"] = gap_tbl

    return out

# =========================
# 실행 (K=5 기준)
# =========================

# 1) GT 생성
gt_pairs = build_gt_pairs(tgt_large if 'tgt_large' in globals() else tgt)

# 2) 비교용 DF 생성 (★ topk=5로 변경)
cmp_df_k5 = make_cmp_df(preds_with_counts, gt_pairs, topk=5)

# 3) 비교 분석 실행
analysis_k5 = compare_correct_vs_incorrect(
    cmp_df=cmp_df_k5,
    actx=actx,
    ads_list_large=ads_list_large if 'ads_list_large' in globals() else ads_list,
    media_portfolio=None  # 있으면 넣기
)

# 4) 주요 결과 출력
print("\n=== SUMMARY (Top-5) ===")
print(analysis_k5["summary"])

print("\n=== BY LABEL DESCRIBE (score, yhat_turn, mda metrics) ===")
print(analysis_k5["by_label_describe"])

print("\n=== RANK POSITION ACCURACY (Top-5 내 순위별 정답률) ===")
print(analysis_k5["rank_position_accuracy"])

if "category_correct_rate" in analysis_k5:
    print("\n=== CATEGORY CORRECT RATE (정답률 높은 카테고리) ===")
    print(analysis_k5["category_correct_rate"].head(20))

    print("\n=== CATEGORY COUNTS (정/오예측 건수) ===")
    print(analysis_k5["category_counts"].head(20))

print("\n=== MDA FALSE POSITIVE HOTLIST (오예측 많이 발생한 매체 Top-30) ===")
print(analysis_k5["mda_false_positive_hotlist"].head(30))

print("\n=== MEAN GAPS (정/오예측 간 평균 차이) ===")
print(analysis_k5["mean_gaps"])

=== SUMMARY (Top-5) ===
{'samples': 3180, 'correct': 1143, 'incorrect': 2037, 'precision_empirical': 0.3594339622641509}

=== BY LABEL DESCRIBE (score, yhat_turn, mda metrics) ===
is_correct                        0             1
score           count  2.037000e+03  1.143000e+03
                mean   1.318327e+00  4.114461e+00
                std    1.455441e+00  2.777740e+00
                min   -4.589903e+00 -1.453916e+00
                25%    6.244200e-01  2.309047e+00
                50%    9.423745e-01  3.414585e+00
                75%    2.658476e+00  7.376601e+00
                max    6.702010e+00  7.376601e+00
yhat_turn       count  2.037000e+03  1.143000e+03
                mean   1.564323e+00  1.634562e+01
                std    2.634145e+00  2.116598e+01
                min    0.000000e+00  0.000000e+00
                25%    5.201536e-01  1.725321e+00
                50%    9.163970e-01  3.993635e+00
                75%    2.365714e+00  2.724357e+01
                max    6.836502e+01  1.340248e+02
mda_cvr_global  count  2.037000e+03  1.143000e+03
                mean   3.774262e-01  5.054861e-01
                std    1.832043e-01  1.311935e-01
                min    4.242578e-04  4.242578e-04
                25%    1.781694e-01  4.801424e-01
                50%    4.389840e-01  5.696886e-01
                75%    4.801424e-01  5.739605e-01
                max    8.346304e-01  6.771160e-01
mda_pop_norm    count  2.037000e+03  1.143000e+03
                mean   4.489647e-01  4.920840e+00
                std    1.152758e+00  5.308619e+00
                min   -2.498233e-01 -2.458660e-01
                25%    2.228593e-01  2.228593e-01
                50%    2.307262e-01  8.562177e-01
                75%    2.683921e-01  1.120975e+01
                max    1.120975e+01  1.120975e+01
mda_clk_global  count  2.037000e+03  1.143000e+03
                mean   4.773815e+05  5.356670e+05
                std    2.376218e+06  2.094162e+06
                min    5.900000e+01  1.400000e+02
                25%    1.740600e+04  1.740600e+04
                50%    3.187900e+04  5.658100e+04
                75%    5.658100e+04  4.187640e+05
                max    1.345644e+07  1.345644e+07
mda_conv_global count  2.037000e+03  1.143000e+03
                mean   1.465831e+04  1.084510e+05
                std    2.417784e+04  1.113425e+05
                min    2.000000e+00  8.500000e+01
                25%    9.916000e+03  9.916000e+03
                50%    1.008100e+04  2.320000e+04
                75%    1.087100e+04  2.403540e+05
                max    2.403540e+05  2.403540e+05

=== RANK POSITION ACCURACY (Top-5 내 순위별 정답률) ===
      accuracy_by_rank
rank
1             0.886792
2             0.160377
3             0.452830
4             0.062893
5             0.234277

=== CATEGORY CORRECT RATE (정답률 높은 카테고리) ===
              correct_rate
ads_category
13                0.800000
0                 0.533333
5                 0.418750
7                 0.400000
4                 0.365010
2                 0.342857
8                 0.318919
1                 0.300000
3                 0.300000
11                0.283333
10                0.228571
6                 0.200000

=== CATEGORY COUNTS (정/오예측 건수) ===
is_correct    incorrect  correct
ads_category
4                  1597      918
5                    93       67
8                   126       59
10                   81       24
11                   43       17
0                    14       16
2                    23       12
13                    2        8
6                    28        7
1                    14        6
7                     9        6
3                     7        3

=== MDA FALSE POSITIVE HOTLIST (오예측 많이 발생한 매체 Top-30) ===
         total  correct  score_mean  yhat_mean  mda_cvr_global  mda_pop_norm  \
mda_idx
761        533       24    0.931945   2.288826        0.178169      0.230726
371        503       51    2.980721   0.400193        0.438984      0.268392
270        497      182    0.514437   1.544984        0.480142      0.856218
562        503      242    2.456002   2.714852        0.569689      0.222859
539         95       29    1.797667   2.694222        0.000424      0.022277
634         85       20   -0.502396   0.650260        0.648946     -0.114894
817         46        1    1.053702   2.932796        0.668934     -0.221788
58          42       11    1.480883   2.250289        0.287768      4.064252
14          38       10    1.165770   3.001880        0.271225      0.648722
294         38       10    1.497207   1.148477        0.189530     -0.226270
583         24        3    1.216881   0.980977        0.041567     -0.234137
654         21        1    1.307721   2.006288        0.050739     -0.197854
563        490      473    6.781697  32.347546        0.573961     11.209750
667         22        7    1.101071   0.717294        0.275605      0.168983
540         20        6    1.361618  18.761060        0.324939     -0.104738
645         17        4    1.800464   1.947270        0.591327     -0.228463
22          30       18    2.223581  17.842263        0.398567      0.949286
385         11        1    1.076329   1.857839        0.232062     -0.215686
398         11        1    1.479128   1.394377        0.168241     -0.205769
343         15        5   -0.570531   3.392464        0.479523      2.588275
344         15        5    1.121074   3.670536        0.557369      0.762911
54          18        8    0.165279   1.038276        0.337562     -0.082472
716          8        0   -4.341654   0.033701        0.735043     -0.241718
108          6        0   -4.335929   0.052599        0.834630     -0.229465
848          6        0    1.544583   2.350784        0.097111     -0.206007
849          6        0    1.062398   0.869089        0.125170     -0.219214
1016         6        0   -4.285120   0.032386        0.815789     -0.245485
496         17       11    2.343105  18.935000        0.199126      0.692777
715          5        0   -4.337871   0.000000        0.796610     -0.247678
655          9        4    0.945526   3.831466        0.607143     -0.245866

         incorrect  correct_rate
mda_idx
761            509      0.045028
371            452      0.101392
270            315      0.366197
562            261      0.481113
539             66      0.305263
634             65      0.235294
817             45      0.021739
58              31      0.261905
14              28      0.263158
294             28      0.263158
583             21      0.125000
654             20      0.047619
563             17      0.965306
667             15      0.318182
540             14      0.300000
645             13      0.235294
22              12      0.600000
385             10      0.090909
398             10      0.090909
343             10      0.333333
344             10      0.333333
54              10      0.444444
716              8      0.000000
108              6      0.000000
848              6      0.000000
849              6      0.000000
1016             6      0.000000
496              6      0.647059
715              5      0.000000
655              5      0.444444

=== MEAN GAPS (정/오예측 간 평균 차이) ===
                  correct_mean  incorrect_mean  gap(correct - incorrect)
mda_conv_global  108450.999125    14658.312224              93792.686901
mda_clk_global   535667.012248   477381.544428              58285.467820
yhat_turn            16.345621        1.564323                 14.781298
mda_pop_norm          4.920840        0.448965                  4.471875
score                 4.114461        1.318327                  2.796134
mda_cvr_global        0.505486        0.377426                  0.128060

In [ ]:
# k=5 기준 정/오예측 분석
analysis_k5 = analyze_correct_incorrect_at_k(preds_with_counts, tgt_large, k=5)

print("=== SUMMARY ===")
print(analysis_k5["summary"])

print("\n=== BY LABEL DESCRIBE ===")
print(analysis_k5["by_label"])

print("\n=== RANK POSITION ACCURACY ===")
print(analysis_k5["acc_by_rank"])

print("\n=== CATEGORY CORRECT RATE ===")
print(analysis_k5["cat_rate"].head(10))

print("\n=== CATEGORY COUNTS ===")
print(analysis_k5["cat_counts"])

print("\n=== MDA FALSE POSITIVE HOTLIST ===")
print(analysis_k5["mda_hotlist"])

print("\n=== MEAN GAPS ===")
print(analysis_k5["mean_gaps"])

=== SUMMARY ===
{'samples': 3180, 'correct': 1143, 'incorrect': 2037, 'precision_empirical': np.float64(0.3594339622641509)}

=== BY LABEL DESCRIBE ===
is_correct                 0            1
score     count  2037.000000  1143.000000
          mean      1.318327     4.114461
          std       1.455441     2.777740
          min      -4.589903    -1.453916
          25%       0.624420     2.309047
          50%       0.942375     3.414585
          75%       2.658476     7.376601
          max       6.702010     7.376601
yhat_turn count  2037.000000  1143.000000
          mean      1.564323    16.345621
          std       2.634145    21.165977
          min       0.000000     0.000000
          25%       0.520154     1.725321
          50%       0.916397     3.993635
          75%       2.365714    27.243571
          max      68.365025   134.024780

=== RANK POSITION ACCURACY ===
      accuracy_by_rank
rank
0             0.886792
1             0.160377
2             0.452830
3             0.062893
4             0.234277

=== CATEGORY CORRECT RATE ===
Empty DataFrame
Columns: [correct_rate]
Index: []

=== CATEGORY COUNTS ===
Empty DataFrame
Columns: []
Index: []

=== MDA FALSE POSITIVE HOTLIST ===
         total  correct  score_mean  yhat_mean mda_cvr_global mda_pop_norm
mda_idx
761        509        0    0.938379   2.300331            NaN          NaN
371        452        0    2.742602   0.331727            NaN          NaN
270        315        0    0.017459   0.585413            NaN          NaN
562        261        0    2.501238   2.411195            NaN          NaN
539         66        0    1.665349   2.788339            NaN          NaN
634         65        0   -0.609760   0.629362            NaN          NaN
817         45        0    1.059408   2.934674            NaN          NaN
58          31        0    1.489795   2.381037            NaN          NaN
14          28        0    1.166468   2.007287            NaN          NaN
294         28        0    1.495994   1.030429            NaN          NaN
583         21        0    1.180530   0.931437            NaN          NaN
654         20        0    1.301201   1.983864            NaN          NaN
563         17        0    1.168856   1.041146            NaN          NaN
667         15        0    0.660162   0.970026            NaN          NaN
540         14        0    0.817872  11.589946            NaN          NaN
645         13        0    1.799685   1.372958            NaN          NaN
22          12        0    1.532467   2.796180            NaN          NaN
398         10        0    1.449434   1.480470            NaN          NaN
54          10        0    0.140265   1.422155            NaN          NaN
385         10        0    0.959829   1.706478            NaN          NaN
344         10        0    0.372520   3.276691            NaN          NaN
343         10        0   -1.420587   1.952296            NaN          NaN
716          8        0   -4.341654   0.033701            NaN          NaN
1016         6        0   -4.285120   0.032386            NaN          NaN
848          6        0    1.544583   2.350784            NaN          NaN
108          6        0   -4.335929   0.052599            NaN          NaN
496          6        0    1.764641   0.787069            NaN          NaN
849          6        0    1.062398   0.869089            NaN          NaN
655          5        0    0.410235   1.935471            NaN          NaN
715          5        0   -4.337871   0.000000            NaN          NaN

=== MEAN GAPS ===
is_correct              0          1 gap(correct - incorrect)
score            1.318327   4.114461                 2.796134
yhat_turn        1.564323  16.345621                14.781298
mda_pop_norm          NaN        NaN                      NaN
mda_clk_global        NaN        NaN                      NaN
mda_conv_global       NaN        NaN                      NaN
mda_cvr_global        NaN        NaN                      NaN

In [ ]:
# ads_list_large에 ads_category 컬럼이 있는지 확인
print("컬럼 목록:", ads_list_large.columns.tolist())

# ads_category 값 확인
if "ads_category" in ads_list_large.columns:
    print("\n=== ads_list_large['ads_category'] 샘플 ===")
    print(ads_list_large["ads_category"].head(20))

    print("\n=== NaN/Null 개수 ===")
    print(ads_list_large["ads_category"].isna().sum(), "/", len(ads_list_large))

    print("\n=== 고유값 개수 ===")
    print(ads_list_large["ads_category"].nunique(dropna=True))

    print("\n=== 고유값 Top-20 ===")
    print(ads_list_large["ads_category"].value_counts(dropna=False).head(20))
else:
    print("⚠️ ads_category 컬럼이 존재하지 않습니다.")

컬럼 목록: ['ads_idx', 'ads_code', 'aff_idx', 'adv_idx', 'ads_type', 'ads_category', 'ads_name', 'ads_icon_img', 'ads_summary', 'ads_save_way', 'ads_day_cap', 'ads_sdate', 'ads_edate', 'ads_age_min', 'ads_age_max', 'ads_os_type', 'ads_contract_price', 'ads_reward_price', 'ads_order', 'ads_rejoin_type', 'regdate', 'ads_size']

=== ads_list_large['ads_category'] 샘플 ===
8287      8
9762      3
11202     8
11488     8
12196     1
12338     8
12666    10
14762     8
14767     8
15128    10
18449    10
18451    10
19227     8
19632     3
20412     8
20677     8
23121     5
24591     8
25847    10
26185     7
Name: ads_category, dtype: int64

=== NaN/Null 개수 ===
0 / 2643

=== 고유값 개수 ===
12

=== 고유값 Top-20 ===
ads_category
4     2472
8       48
5       34
10      21
11      15
1       14
2       12
0        8
6        7
3        5
7        4
13       3
Name: count, dtype: int64

In [ ]:
def build_simple_features(ads_time, ads_list, ads_domain):
    # 1) 매체사별 전역 클릭수 (과거 성과의 세부 페어 데이터 제외)
    mda_perf = (
        ads_time.groupby("mda_idx", as_index=False)
                .agg(mda_clicks=("rpt_time_clk", "sum"))
    )

    # 2) 광고 메타
    ad_meta = ads_list[["ads_idx", "ads_category", "ads_os_type",
                        "ads_contract_price", "ads_reward_price"]].copy()

    # 3) 광고 도메인
    ad_domain = ads_domain[["ads_idx", "domain"]].copy()

    # 4) 광고 × 매체 cross-join + 피처 결합
    X_simple = (
        ad_meta
        .merge(ad_domain, on="ads_idx", how="left")
        .assign(_key=1)
        .merge(mda_perf.assign(_key=1), on="_key", how="left")
        .drop(columns="_key")
    )

    # 선택: 카테고리형 정리 (LightGBM 등에서 바로 사용하려면)
    for c in ["ads_category", "ads_os_type", "domain"]:
        if c in X_simple.columns:
            X_simple[c] = X_simple[c].astype("category")

    return X_simple

# === 실행 ===
X_simple = build_simple_features(ads_time, ads_list, ads_domain)
# 확인
# X_simple.head()

In [ ]:
X_simple

,ads_idx,ads_category,ads_os_type,ads_contract_price,ads_reward_price,domain,mda_idx,mda_clicks
0,160,1,2,170,150,NaN,12,224440
1,160,1,2,170,150,NaN,14,84025
2,160,1,2,170,150,NaN,18,5776
3,160,1,2,170,150,NaN,22,80177
4,160,1,2,170,150,NaN,26,670
...,...,...,...,...,...,...,...,...
84112366,446918,8,7,300,225,미디어/컨텐츠,1050,1
84112367,446918,8,7,300,225,미디어/컨텐츠,1051,1
84112368,446918,8,7,300,225,미디어/컨텐츠,1055,3
84112369,446918,8,7,300,225,미디어/컨텐츠,1059,6
84112370,446918,8,7,300,225,미디어/컨텐츠,1061,9

In [ ]:
# ==============================================
# Attr-only Ranking with Rich Features (No Pair History)
# Split: OBS(학습)=최근7일 이전 전체 / TGT(테스트)=최근7일
# LARGE 광고만 대상, 후보 Top-M, 다운샘플링, Graded relevance
# ==============================================

# -----------------------------
# 0) 유틸
# -----------------------------
def _to_num(s): return pd.to_numeric(s, errors="coerce").fillna(0)
def _to_dt(s):  return pd.to_datetime(s, errors="coerce")

def _mode(s: pd.Series):
    if s.isna().all(): return np.nan
    m = s.mode()
    return m.iloc[0] if len(m) else np.nan

def _norm_cat(s):
    return pd.Series(s, copy=False).astype("string").str.strip().str.lower()

def _pick_col(cols, cands):
    for c in cands:
        if c in cols: return c
    return None

# -----------------------------
# 1) 날짜 스플릿 (최근 7일 TEST)
# -----------------------------
ads_time = ads_time.copy()
ads_time["rpt_time_date"] = _to_dt(ads_time["rpt_time_date"])
max_date = ads_time["rpt_time_date"].max()
cutoff   = (max_date - pd.Timedelta(days=7)).normalize()
print(f"Cutoff: {cutoff.date()} ~ {max_date.date()}")

ads_time_tr = ads_time[ads_time["rpt_time_date"] <= cutoff].copy()   # OBS
ads_time_te = ads_time[ads_time["rpt_time_date"] >  cutoff].copy()   # TGT

# -----------------------------
# 2) LARGE 광고만 대상으로 df_base 제한
# -----------------------------
large_ads = ads_segment.loc[ads_segment["ads_size"]=="LARGE","ads_idx"].unique()
df_base   = X_simple[X_simple["ads_idx"].isin(large_ads)].copy()

# -----------------------------
# 3) 라벨 (TGT/OBS 각각)
# -----------------------------
label_tr = (ads_time_tr.groupby(["ads_idx","mda_idx"], as_index=False)
            .agg(mda_convs=("rpt_time_turn","sum")))
label_te = (ads_time_te.groupby(["ads_idx","mda_idx"], as_index=False)
            .agg(mda_convs=("rpt_time_turn","sum")))

# -----------------------------
# 4) ATTR 컨텍스트 (OBS만 사용) - 1~5번 피처의 재료
# -----------------------------
def build_attr_context(obs: pd.DataFrame, ads_list: pd.DataFrame):
    t = obs.copy()
    t["clk"]  = _to_num(t.get("rpt_time_clk", 0))
    t["conv"] = _to_num(t.get("rpt_time_turn", 0))

    # 1) 매체 전반
    mda_all = (t.groupby("mda_idx", as_index=False)
                 .agg(mda_clk_global=("clk","sum"),
                      mda_conv_global=("conv","sum")))
    mda_all["mda_cvr_global"] = (mda_all["mda_conv_global"] /
                                 mda_all["mda_clk_global"].replace(0, np.nan)).fillna(0.0)
    mu = mda_all["mda_conv_global"].mean()
    sd = mda_all["mda_conv_global"].std(ddof=0)
    mda_all["mda_pop_norm"] = (mda_all["mda_conv_global"] - mu) / (sd + 1e-9)

    # 광고 카테고리 붙여서 2) 카테고리×매체
    al = ads_list[["ads_idx","ads_category"]].drop_duplicates("ads_idx").copy()
    al["ads_category"] = _norm_cat(al["ads_category"])
    t2 = t.merge(al, on="ads_idx", how="left")
    cat_mda = (t2.groupby(["mda_idx","ads_category"], as_index=False)
                 .agg(clk=("clk","sum"), conv=("conv","sum")))
    cat_mda["cat_cvr"] = (cat_mda["conv"] / cat_mda["clk"].replace(0, np.nan)).fillna(0.0)
    mda_tot = cat_mda.groupby("mda_idx", as_index=False).agg(mda_conv_total=("conv","sum"))
    cat_mda = cat_mda.merge(mda_tot, on="mda_idx", how="left")
    cat_mda["cat_share"] = (cat_mda["conv"] /
                            cat_mda["mda_conv_total"].replace(0, np.nan)).fillna(0.0)
    cat_mda.drop(columns=["mda_conv_total"], inplace=True)

    # 4) 도메인×매체
    dom_col = _pick_col(t.columns, ["req_domain","domain","site_domain","publisher_domain","ads_domain"])
    dom_mda = None
    if dom_col is not None:
        t_dom = t.copy()
        t_dom[dom_col] = _norm_cat(t_dom[dom_col])
        dom_mda = (t_dom.groupby(["mda_idx", dom_col], as_index=False)
                        .agg(clk=("clk","sum"), conv=("conv","sum")))
        dom_mda["dom_cvr"] = (dom_mda["conv"] / dom_mda["clk"].replace(0, np.nan)).fillna(0.0)
        mt2 = dom_mda.groupby("mda_idx", as_index=False).agg(mda_conv_total=("conv","sum"))
        dom_mda = dom_mda.merge(mt2, on="mda_idx", how="left")
        dom_mda["dom_share"] = (dom_mda["conv"] /
                                dom_mda["mda_conv_total"].replace(0, np.nan)).fillna(0.0)
        dom_mda = dom_mda.rename(columns={dom_col: "ads_domain"})
        dom_mda.drop(columns=["mda_conv_total"], inplace=True)

    # 5) OS×매체
    os_col = _pick_col(t.columns, ["os_type","device_os","os","ads_os_type"])
    os_mda = None
    if os_col is not None:
        t_os = t.copy()
        t_os[os_col] = _norm_cat(t_os[os_col])
        os_mda = (t_os.groupby(["mda_idx", os_col], as_index=False)
                        .agg(clk=("clk","sum"), conv=("conv","sum")))
        os_mda["os_cvr"] = (os_mda["conv"] / os_mda["clk"].replace(0, np.nan)).fillna(0.0)
        mt3 = os_mda.groupby("mda_idx", as_index=False).agg(mda_conv_total=("conv","sum"))
        os_mda = os_mda.merge(mt3, on="mda_idx", how="left")
        os_mda["os_share"] = (os_mda["conv"] /
                              os_mda["mda_conv_total"].replace(0, np.nan)).fillna(0.0)
        os_mda = os_mda.rename(columns={os_col: "os_type"})
        os_mda.drop(columns=["mda_conv_total"], inplace=True)

    return {"mda_all": mda_all, "cat_mda": cat_mda, "dom_mda": dom_mda, "os_mda": os_mda}

actx = build_attr_context(ads_time_tr, ads_list)

# -----------------------------
# 5) 광고 가격/속성 파생 (3번 피처)
# -----------------------------
ad_meta = ads_list[["ads_idx","ads_category","ads_os_type",
                    "ads_contract_price","ads_reward_price"]].drop_duplicates("ads_idx").copy()
ad_meta["ads_category"] = _norm_cat(ad_meta["ads_category"])
ad_meta["os_type"] = _norm_cat(ad_meta.get("ads_os_type", np.nan))
ad_meta["ads_reward_price"]   = _to_num(ad_meta["ads_reward_price"])
ad_meta["ads_contract_price"] = _to_num(ad_meta["ads_contract_price"])
ad_meta["price_reward_log"]   = np.log1p(ad_meta["ads_reward_price"])
ad_meta["price_contract_log"] = np.log1p(ad_meta["ads_contract_price"])
ad_meta["price_ratio"]        = (ad_meta["ads_reward_price"] /
                                 ad_meta["ads_contract_price"].replace(0, np.nan)).fillna(0.0)

# 광고 도메인(있으면) 정규화
ad_dom_col = _pick_col(ads_list.columns, ["ads_domain","domain","site_domain","publisher_domain"])
if ad_dom_col is not None:
    ad_meta["ads_domain"] = _norm_cat(ads_list[[ad_dom_col,"ads_idx"]]
                                      .drop_duplicates("ads_idx")[ad_dom_col])
else:
    ad_meta["ads_domain"] = "__na__"

# -----------------------------
# (선택) 6) media_portfolio 병합
# -----------------------------
def attach_media_portfolio(df, media_portfolio):
    if media_portfolio is None:  # 없으면 0/UNKNOWN 채움
        for c in ["mda_size","active_ratio","day_ratio","weekend_ratio"]:
            df[c] = 0.0
        return df
    mp = media_portfolio.copy()
    keep = [c for c in ["mda_idx","mda_size","active_ratio","day_ratio","weekend_ratio"] if c in mp.columns]
    if "mda_idx" not in keep:
        for c in ["mda_size","active_ratio","day_ratio","weekend_ratio"]:
            df[c] = 0.0
        return df
    df = df.merge(mp[keep], on="mda_idx", how="left")
    for c in ["active_ratio","day_ratio","weekend_ratio"]:
        if c in df.columns:
            df[c] = _to_num(df[c])
        else:
            df[c] = 0.0
    if "mda_size" not in df.columns:
        df["mda_size"] = 0.0
    return df

# -----------------------------
# 7) Train/Test 빌드 + 피처 결합(1~6)
# -----------------------------
def build_featured(df_base, label, ad_meta, actx, media_portfolio=None):
    # 기본(광고×매체)
    df = df_base.merge(label, on=["ads_idx","mda_idx"], how="left")
    df["mda_convs"] = _to_num(df["mda_convs"])
    # 광고 속성 붙이기
    df = df.merge(ad_meta[["ads_idx","ads_category","os_type","ads_reward_price","ads_contract_price",
                           "price_reward_log","price_contract_log","price_ratio","ads_domain"]],
                  on="ads_idx", how="left")

    # 1) 매체 전반
    mda_all = actx["mda_all"]
    df = df.merge(mda_all, on="mda_idx", how="left")

    # 2) 카테고리×매체
    cat_mda = actx["cat_mda"].copy()
    df["ads_category"] = _norm_cat(df["ads_category"])
    cat_mda["ads_category"] = _norm_cat(cat_mda["ads_category"])
    df = df.merge(cat_mda[["mda_idx","ads_category","cat_cvr","cat_share"]],
                  on=["mda_idx","ads_category"], how="left")

    # 4) 도메인×매체
    if actx["dom_mda"] is not None:
        dom_mda = actx["dom_mda"].copy()
        dom_mda["ads_domain"] = _norm_cat(dom_mda["ads_domain"])
        df["ads_domain"] = _norm_cat(df["ads_domain"])
        df = df.merge(dom_mda[["mda_idx","ads_domain","dom_cvr","dom_share"]],
                      on=["mda_idx","ads_domain"], how="left")
    else:
        df["dom_cvr"]=0.0; df["dom_share"]=0.0

    # 5) OS×매체
    if actx["os_mda"] is not None:
        os_mda = actx["os_mda"].copy()
        os_mda["os_type"] = _norm_cat(os_mda["os_type"])
        df["os_type"]     = _norm_cat(df["os_type"])
        df = df.merge(os_mda[["mda_idx","os_type","os_cvr","os_share"]],
                      on=["mda_idx","os_type"], how="left")
    else:
        df["os_cvr"]=0.0; df["os_share"]=0.0

    # 6) media_portfolio
    df = attach_media_portfolio(df, media_portfolio)

    # 결측 처리
    for c in ["mda_clk_global","mda_conv_global","mda_cvr_global","mda_pop_norm",
              "cat_cvr","cat_share","dom_cvr","dom_share","os_cvr","os_share"]:
        if c in df.columns: df[c] = df[c].fillna(0.0)

    # graded relevance (0,1,2,3)
    y = df["mda_convs"].astype(float)
    rel = np.zeros(len(df), dtype=int)
    pos = y > 0
    if pos.sum() > 0:
        # 상위 전환을 더 높은 등급으로
        ylog = np.log1p(y[pos])
        try:
            bins = pd.qcut(ylog, q=3, labels=False, duplicates="drop") # 3분위 → 1..3
            rel[pos] = bins.astype(int) + 1
        except ValueError:
            rel[pos] = 1
    df["relevance"] = rel

    # prior feature
    df["prior_expected"] = df["mda_clk_global"] * df["mda_cvr_global"]
    df["prior_expected_log1p"] = np.log1p(df["prior_expected"])

    # 라벨 보존
    df["label_cls"] = (df["mda_convs"] > 0).astype(int)
    df["label_reg"] = y
    return df

train_df = build_featured(df_base, label_tr, ad_meta, actx, media_portfolio=None)
test_df  = build_featured(df_base, label_te, ad_meta, actx, media_portfolio=None)

print("Train size:", len(train_df), " Test size:", len(test_df))

# -----------------------------
# 8) 후보 Top-M 축소 (학습/평가 공통)
# -----------------------------
def restrict_topM(df, M=150):
    return (df.sort_values(["ads_idx","prior_expected"], ascending=[True,False])
              .groupby("ads_idx", group_keys=False).head(M))

train_df = restrict_topM(train_df, M=150)
test_df  = restrict_topM(test_df,  M=150)

# -----------------------------
# 9) 다운샘플링 (광고별 neg:pos ≈ 4:1)
# -----------------------------
def downsample_per_ad(df, ratio=4, seed=42):
    rng = np.random.RandomState(seed)
    out = []
    for ad, g in df.groupby("ads_idx", sort=False):
        pos = g[g["label_cls"]==1]
        neg = g[g["label_cls"]==0]
        if len(pos)==0:
            continue
        cap = len(pos) * ratio
        if len(neg) > cap:
            neg = neg.sample(cap, random_state=rng)
        out.append(pd.concat([pos,neg], ignore_index=True))
    return pd.concat(out, ignore_index=True) if out else df

train_df = downsample_per_ad(train_df, ratio=4)

# -----------------------------
# 10) 학습 준비
# -----------------------------
FEATS = [
    # 1) 매체 전반
    "mda_clk_global","mda_conv_global","mda_cvr_global","mda_pop_norm",
    # 2) 카테고리×매체
    "cat_cvr","cat_share",
    # 3) 광고 가격/속성
    "price_reward_log","price_contract_log","price_ratio",
    # 4) 도메인×매체
    "dom_cvr","dom_share",
    # 5) OS×매체
    "os_cvr","os_share",
    # 6) media_portfolio (없으면 0)
    "mda_size","active_ratio","day_ratio","weekend_ratio",
    # prior feature
    "prior_expected","prior_expected_log1p"
]
def ensure_X(df, cols):
    X = df.copy()
    for c in cols:
        if c not in X.columns:
            X[c] = 0.0
        X[c] = _to_num(X[c])
    return X[cols].astype(np.float32)

Xtr = ensure_X(train_df, FEATS)
Xte = ensure_X(test_df,  FEATS)
ytr = train_df["relevance"].astype(int).values
yte = test_df["relevance"].astype(int).values
group_tr = train_df.groupby("ads_idx").size().astype(int).tolist()
group_te = test_df.groupby("ads_idx").size().astype(int).tolist()

# -----------------------------
# 11) Ranker (LambdaRank, graded relevance)
# -----------------------------
ranker = lgb.LGBMRanker(
    objective="lambdarank", metric="ndcg", eval_at=[5,10,20],
    learning_rate=0.05, n_estimators=1200, num_leaves=63,
    min_data_in_leaf=40, subsample=0.85, colsample_bytree=0.85,
    label_gain=[0,1,4,12], random_state=42, verbosity=-1
)
ranker.fit(
    Xtr, ytr, group=group_tr,
    eval_set=[(Xte, yte)], eval_group=[group_te]
)

test_df["pred_score"] = ranker.predict(Xte)

# -----------------------------
# 12) Top-K 추천 & 평가
# -----------------------------
final_rec = (test_df.sort_values(["ads_idx","pred_score"], ascending=[True,False])
                    .groupby("ads_idx", group_keys=False).head(20)
                    .reset_index(drop=True))

def _avg_precision_at_k(labels_sorted, K):
    lab = np.asarray(labels_sorted)[:K]
    if lab.sum()==0: return 0.0
    precisions, hits = [], 0
    for i,y in enumerate(lab, start=1):
        if y==1:
            hits += 1
            precisions.append(hits/i)
    return float(np.mean(precisions)) if precisions else 0.0

def _precision_at_k(labels_sorted, K):
    lab = np.asarray(labels_sorted)[:K]
    return float(lab.mean()) if len(lab) else 0.0

def _recall_at_k(labels_sorted, K, total_pos):
    if total_pos==0: return 0.0
    lab = np.asarray(labels_sorted)[:K]
    return float(lab.sum()/total_pos)

def evaluate_ranking(df_scored, use_col="pred_score", ks=(5,10,20)):
    out = {}
    g = df_scored.sort_values(["ads_idx", use_col], ascending=[True, False]).groupby("ads_idx")
    for K in ks:
        P,R,AP = [],[],[]
        for _, grp in g:
            y_sorted = grp["label_cls"].values
            total_pos = int(grp["label_cls"].sum())
            P.append(_precision_at_k(y_sorted, K))
            R.append(_recall_at_k(y_sorted, K, total_pos))
            AP.append(_avg_precision_at_k(y_sorted, K))
        out[f"P@{K}"]   = float(np.mean(P)) if P else np.nan
        out[f"R@{K}"]   = float(np.mean(R)) if R else np.nan
        out[f"MAP@{K}"] = float(np.mean(AP)) if AP else np.nan
    return out

metrics = evaluate_ranking(final_rec[["ads_idx","label_cls","pred_score"]].copy())
print("=== Final (Attr-only + Rich Features) ===")
print(metrics)

Cutoff: 2025-08-18 ~ 2025-08-25

KeyError: 'ads_category'

In [ ]:
show_ad_all(57056).head(50)

NameError: name 'show_ad_all' is not defined

In [ ]:
# test 데이터셋에서 실제 라벨과 예측값 준비
y_true = test_df["label_cls"].values
y_score = test_df["pred_convs"].values   # 최종 예측 전환수 기반 점수

try:
    auc = roc_auc_score(y_true, y_score)
except ValueError:
    auc = np.nan   # 만약 y_true가 전부 0/1 한쪽으로만 치우친 경우
print("=== AUC (Final pred_convs) ===")
print(auc)

In [ ]:
def show_ad_topk(ad_id, K=5):
    plist = pred.get(ad_id, [])[:K]
    pred_df = pd.DataFrame(plist, columns=["mda_idx","pred_convs"])   # 🔹 pred_convs 포함
    
    # 실제 전환 매체 set
    true_set = gt.get(ad_id, set())
    
    # 실제 전환수 맵핑
    true_conv_map = (test_df.loc[test_df["ads_idx"]==ad_id, ["mda_idx","label_reg"]]
                               .drop_duplicates()
                               .set_index("mda_idx")["label_reg"]
                               .to_dict())
    pred_df["true_convs"] = pred_df["mda_idx"].map(true_conv_map).fillna(0).astype(int)
    pred_df["is_true"] = pred_df["mda_idx"].isin(true_set)

    print(f"\n광고 ID: {ad_id}")
    print(f"예측 Top-{K}: {pred_df['mda_idx'].tolist()}")
    print(f"실제 전환 매체: {sorted(list(true_set))}")

    return pred_df[["mda_idx","pred_convs","true_convs","is_true"]]

In [ ]:
show_ad_topk(57056, K=5)

In [ ]:
# 광고별 Top-K 추천 (예: K=10)
K = 10
topk_rec = (
    final_rec.sort_values(["ads_idx","pred_convs","rank_score"], ascending=[True,False,False])
             .groupby("ads_idx", group_keys=False)
             .head(K)
             .reset_index(drop=True)
)

# 보기 좋게 출력
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

topk_rec.head(5)   # 여러 광고 섞여서 상위 30행만 미리보기

In [ ]:
# --------------------------------------------
# 준비: test_df(라벨)와 final_rec(예측결과)에서
#  - 광고별 실제 전환 매체 리스트(gt)
#  - 광고별 예측 Top-K 리스트(preds: (mda_idx, pred_convs))
# --------------------------------------------
def build_ground_truth(test_df):
    # 실제 전환된 매체: label_cls == 1
    gt = (
        test_df.loc[test_df["label_cls"] == 1, ["ads_idx", "mda_idx"]]
               .groupby("ads_idx")["mda_idx"].apply(set)
               .to_dict()
    )
    return gt

def build_predictions(final_rec, K=10):
    # 최종 결과에서 광고별 Top-K (pred_convs 우선, 동점 시 rank_score)
    preds = {}
    ordered = (final_rec
               .sort_values(["ads_idx", "pred_convs", "rank_score"], ascending=[True, False, False])
               .groupby("ads_idx", group_keys=False)
               .head(K))
    for ad, grp in ordered.groupby("ads_idx"):
        preds[ad] = list(zip(grp["mda_idx"].tolist(), grp["pred_convs"].tolist()))
    return preds

gt   = build_ground_truth(test_df)
pred = build_predictions(final_rec, K=10)

# --------------------------------------------
# 보기: 특정 광고(ad_id) 대해 표와 비교 세트 출력
# --------------------------------------------
def show_ad_topk(ad_id, K=10):
    # 예측 Top-K
    plist = pred.get(ad_id, [])[:K]
    pred_mda = [m for m,_ in plist]
    pred_df = pd.DataFrame(plist, columns=["mda_idx","pred_convs"])
    # 실제 전환 매체 set
    true_set = gt.get(ad_id, set())
    # 맞춘/놓친
    hits      = set(pred_mda) & true_set
    miss_pred = set(pred_mda) - true_set
    miss_true = true_set - set(pred_mda)
    # 표에 실제 전환 여부/실제 전환수(있으면) 추가
    if "mda_convs" in test_df.columns:
        true_conv_map = (test_df.loc[test_df["ads_idx"]==ad_id, ["mda_idx","mda_convs"]]
                              .drop_duplicates()
                              .set_index("mda_idx")["mda_convs"]
                              .to_dict())
        pred_df["true_convs"] = pred_df["mda_idx"].map(true_conv_map).fillna(0).astype(int)
    pred_df["is_true"] = pred_df["mda_idx"].isin(true_set)

    print(f"\n광고 ID: {ad_id}")
    print(f"예측 Top-{K}: {[m for m,_ in plist]}")
    print(f"실제 전환 매체: {sorted(list(true_set))}")
    print("맞춘 매체 :", hits)
    print("추천했지만 실패 :", miss_pred)
    print("놓친 실제 매체 :", miss_true)

    # 예측표 보기 좋게
    display_cols = ["mda_idx","pred_convs","is_true"]
    if "true_convs" in pred_df.columns:
        display_cols.insert(2,"true_convs")
    return pred_df[display_cols]

# 예시 실행
# ad_id = list(pred.keys())[0]   # 하나 골라보기
# show_ad_topk(ad_id, K=10)

In [ ]:
ad_id = list(pred.keys())[0]   # 하나 골라보기
show_ad_topk(ad_id, K=10)